/**
 * Emits src/css/tokens.css from the TypeScript tokens. The TS is the source of
 * truth; the CSS is a build artifact so the web can use custom properties
 * without importing JS at render time. Run via `pnpm --filter @sachmuch/ui build:css`.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { palette, type Scheme } from '../src/tokens/color';
import { clayShadow } from '../src/tokens/clay';
import { radius, space, easing } from '../src/tokens/space';
import { fontSize, typeScales } from '../src/tokens/type';
import { brandGradient, categoryTint } from '../src/tokens/tint';
import { CATEGORY_COUNT } from '../src/tokens/categories';

const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

function schemeVars(scheme: Scheme): string {
  const p = palette[scheme];
  const lines: string[] = [];
  for (const [k, v] of Object.entries(p)) lines.push(`  --clay-${kebab(k)}: ${v};`);
  for (const level of [1, 2, 3] as const) {
    lines.push(`  --clay-raised-${level}: ${clayShadow({ scheme, level, state: 'raised' })};`);
    lines.push(`  --clay-pressed-${level}: ${clayShadow({ scheme, level, state: 'pressed' })};`);
  }
  lines.push(`  --brand-gradient: ${brandGradient(scheme)};`);
  for (let i = 0; i < CATEGORY_COUNT; i++) {
    const t = categoryTint(i, CATEGORY_COUNT, scheme);
    lines.push(
      `  --cat-${i}-bg: ${t.bg}; --cat-${i}-surface: ${t.surface}; ` +
      `--cat-${i}-accent: ${t.accent}; --cat-${i}-accent-to: ${t.accentTo}; ` +
      `--cat-${i}-gradient: ${t.gradient};`,
    );
  }
  return lines.join('\n');
}

const staticVars = [
  ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${typeof v === 'number' ? `${v}px` : v};`),
  ...Object.entries(space).map(([k, v]) => `  --space-${k}: ${v}px;`),
  ...Object.entries(fontSize).map(([k, v]) => `  --size-${k}: ${v}px;`),
  ...Object.entries(easing).map(([k, v]) => `  --ease-${k}: ${v};`),
  ...Object.entries(typeScales).map(([k, v]) => `  --type-scale-${k}: ${v};`),
  `  --font-display: 'Baloo 2', system-ui, sans-serif;`,
  `  --font-body-latin: 'Mulish', system-ui, sans-serif;`,
  `  --font-body-devanagari: 'Noto Sans Devanagari', 'Baloo 2', system-ui, sans-serif;`,
  `  --type-scale: 1;`,
].join('\n');

const css = `/* GENERATED by packages/ui/scripts/emit-css.ts — do not edit by hand. */

/*
 * DARK-FIRST. The feed is a full-bleed surface people scroll on a phone, often
 * at night, so dark is the design and light is the accommodation. Light is a
 * separate recipe rather than an inversion.
 */
:root {
${staticVars}
${schemeVars('dark')}
}

:root[data-scheme='light'] {
${schemeVars('light')}
}

@media (prefers-color-scheme: light) {
  :root:not([data-scheme='dark']) {
${schemeVars('light')}
  }
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;

const out = resolve(dirname(fileURLToPath(import.meta.url)), '../src/css/tokens.css');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, css, 'utf8');
console.log(`wrote ${out} (${css.length} bytes)`);
