import type { CategoryDef } from '../taxonomy-types.js';

export const metaverse: CategoryDef = {
  id: 6,
  slug: 'metaverse-xr',
  en: 'Metaverse & XR',
  hi: 'मेटावर्स और एक्सआर',
  emoji: '🥽',
  kidsSafe: true,
  subtopics: [
    { slug: 'sensorama-and-early-vr', en: 'Sensorama and the first VR machines', hi: 'सेंसोरामा और शुरुआती वीआर मशीनें', qids: ['Q1093450'], keywords: ['Sensorama', 'Morton Heilig', 'Sword of Damocles', 'Ivan Sutherland'] },
    { slug: 'jaron-lanier-vpl', en: 'Jaron Lanier, VPL Research and the DataGlove', hi: 'जैरन लेनियर, वीपीएल रिसर्च और डेटाग्लव', qids: ['Q92862'], keywords: ['Jaron Lanier', 'VPL Research', 'DataGlove', 'virtual reality term'] },
    { slug: 'head-mounted-displays', en: 'How a headset tricks your eyes', hi: 'हेडसेट आपकी आँखों को कैसे बहलाता है', qids: ['Q1333980'], keywords: ['head-mounted display', 'stereoscopic 3D', 'lens distortion', 'field of view'] },
    { slug: 'oculus-rift-kickstarter', en: 'The Oculus Rift Kickstarter and the Facebook buyout', hi: 'ऑकुलस रिफ़्ट का किकस्टार्टर और फ़ेसबुक की ख़रीद', qids: ['Q3274429'], keywords: ['Oculus Rift', 'Palmer Luckey', 'Kickstarter 2012', 'Facebook acquisition 2014'] },
    { slug: 'meta-quest', en: 'Meta Quest and standalone headsets', hi: 'मेटा क्वेस्ट और स्टैंडअलोन हेडसेट', qids: ['Q63777286'], keywords: ['Meta Quest', 'standalone VR', 'inside-out tracking', 'Horizon Worlds'] },
    { slug: 'apple-vision-pro', en: 'Apple Vision Pro and spatial computing', hi: 'ऐपल विज़न प्रो और स्पेशियल कंप्यूटिंग', qids: ['Q117715451'], keywords: ['Apple Vision Pro', 'spatial computing', 'visionOS', 'passthrough'] },
    { slug: 'htc-vive-room-scale', en: 'HTC Vive and room-scale tracking', hi: 'एचटीसी वाइव और रूम-स्केल ट्रैकिंग', qids: ['Q19414112'], keywords: ['HTC Vive', 'Lighthouse tracking', 'room-scale VR', 'SteamVR'] },
    { slug: 'google-cardboard', en: 'Google Cardboard and phone-based VR', hi: 'गूगल कार्डबोर्ड और फ़ोन वाला वीआर', qids: ['Q17558104'], keywords: ['Google Cardboard', 'Daydream', 'phone VR', 'cheap headset'] },
    { slug: 'google-glass', en: 'Google Glass and why it failed', hi: 'गूगल ग्लास और उसका फ़ेल होना', qids: ['Q575092'], keywords: ['Google Glass', 'Explorer Edition', 'privacy backlash', 'smart glasses'] },
    { slug: 'hololens-and-mixed-reality', en: 'HoloLens and mixed reality at work', hi: 'होलोलेंस और काम में मिक्स्ड रियलिटी', qids: ['Q18844389'], keywords: ['Microsoft HoloLens', 'mixed reality', 'enterprise AR', 'IVAS'] },
    { slug: 'pokemon-go', en: 'Pokémon Go and AR that went outdoors', hi: 'पोकेमॉन गो और बाहर निकला एआर', qids: ['Q20966579'], keywords: ['Pokemon Go', 'Niantic', 'location-based AR', '2016 launch'] },
    { slug: 'ar-filters-and-lenses', en: 'Snapchat lenses and Instagram AR filters', hi: 'स्नैपचैट लेंस और इंस्टाग्राम एआर फ़िल्टर', qids: ['Q107361304'], keywords: ['Snapchat lens', 'AR filter', 'face tracking', 'Spark AR'] },
    { slug: 'second-life', en: 'Second Life, the metaverse before the word', hi: 'सेकंड लाइफ़, मेटावर्स शब्द से पहले का मेटावर्स', qids: ['Q106827'], keywords: ['Second Life', 'Linden Lab', 'Linden dollar', 'virtual economy'] },
    { slug: 'roblox', en: 'Roblox and user-built worlds', hi: 'रोब्लॉक्स और यूज़र के बनाए वर्ल्ड', keywords: ['Roblox', 'user generated games', 'Robux', 'developer exchange'] },
    { slug: 'fortnite-virtual-concerts', en: 'Fortnite concerts and in-game events', hi: 'फ़ोर्टनाइट कॉन्सर्ट और गेम के अंदर इवेंट', keywords: ['Fortnite concert', 'Travis Scott Astronomical', 'in-game event', 'Epic Games'] },
    { slug: 'vrchat-social-vr', en: 'VRChat and social VR', hi: 'वीआरचैट और सोशल वीआर', qids: ['Q47044629'], keywords: ['VRChat', 'social VR', 'avatar worlds', 'full body tracking'] },
    { slug: 'virtual-land-and-decentraland', en: 'Virtual land: Decentraland and The Sandbox', hi: 'वर्चुअल ज़मीन: डिसेंट्रालैंड और द सैंडबॉक्स', qids: ['Q107210481'], keywords: ['Decentraland', 'The Sandbox', 'virtual land sale', 'metaverse real estate'] },
    { slug: 'nfts-and-digital-ownership', en: 'NFTs and owning digital things', hi: 'एनएफ़टी और डिजिटल चीज़ों की मिल्कियत', keywords: ['NFT', 'digital ownership', 'blockchain token', 'marketplace crash'] },
    { slug: 'avatars-and-digital-identity', en: 'Avatars and digital identity', hi: 'अवतार और डिजिटल पहचान', qids: ['Q790261'], keywords: ['avatar', 'digital identity', 'Ready Player Me', 'avatar customisation'] },
    { slug: 'motion-capture', en: 'Motion capture, from Gollum to Avatar', hi: 'मोशन कैप्चर: गॉलम से अवतार तक', qids: ['Q676252'], keywords: ['motion capture', 'performance capture', 'Andy Serkis', 'mocap suit'] },
    { slug: 'haptics', en: 'Haptics: making virtual things feel solid', hi: 'हैप्टिक्स: वर्चुअल चीज़ों को छूने का एहसास', qids: ['Q101704012'], keywords: ['haptic feedback', 'force feedback glove', 'rumble', 'tactile interface'] },
    { slug: 'eye-tracking-foveated-rendering', en: 'Eye tracking and foveated rendering', hi: 'आई ट्रैकिंग और फ़ोवीएटेड रेंडरिंग', qids: ['Q970687'], keywords: ['eye tracking', 'foveated rendering', 'gaze interaction', 'GPU savings'] },
    { slug: 'cybersickness', en: 'Why VR makes people queasy', hi: 'वीआर से जी क्यों मिचलाता है', qids: ['Q94687934'], keywords: ['cybersickness', 'simulator sickness', 'latency motion-to-photon', 'vestibular mismatch'] },
    { slug: 'flight-simulators', en: 'Flight simulators and pilot training', hi: 'फ़्लाइट सिम्युलेटर और पायलट ट्रेनिंग', qids: ['Q214932'], keywords: ['flight simulator', 'full motion simulator', 'pilot training hours', 'Link Trainer'] },
    { slug: 'vr-in-surgery', en: 'VR in surgical and medical training', hi: 'सर्जरी और मेडिकल ट्रेनिंग में वीआर', keywords: ['surgical simulation', 'VR medical training', 'laparoscopic trainer', 'anatomy VR'] },
    { slug: 'digital-twins', en: 'Digital twins of factories and cities', hi: 'फ़ैक्ट्री और शहरों के डिजिटल ट्विन', qids: ['Q25099680'], keywords: ['digital twin', 'industrial metaverse', 'Omniverse', 'smart city model'] },
    { slug: 'cave-systems', en: 'CAVE projection rooms', hi: 'CAVE प्रोजेक्शन रूम', qids: ['Q1051821'], keywords: ['CAVE automatic virtual environment', 'projection VR', 'stereoscopic room', 'research visualisation'] },
    { slug: 'spatial-audio', en: 'Spatial audio and 3D sound', hi: 'स्पेशियल ऑडियो और थ्रीडी आवाज़', qids: ['Q107209417'], keywords: ['spatial audio', 'HRTF', 'binaural sound', 'ambisonics'] },
    { slug: 'volumetric-capture-holograms', en: 'Volumetric capture and hologram illusions', hi: 'वॉल्यूमेट्रिक कैप्चर और होलोग्राम का भ्रम', qids: ['Q55080150'], keywords: ['volumetric video', 'hologram', 'Pepper’s ghost', 'light field'] },
    { slug: 'snow-crash-and-fiction', en: 'Snow Crash and the metaverse in fiction', hi: 'स्नो क्रैश और कहानियों का मेटावर्स', qids: ['Q58883506'], keywords: ['Snow Crash', 'Neal Stephenson', 'Ready Player One', 'cyberspace fiction'] },
    { slug: 'webxr', en: 'WebXR: VR inside the browser', hi: 'वेबएक्सआर: ब्राउज़र के अंदर वीआर', qids: ['Q1441585'], keywords: ['WebXR', 'browser VR', 'A-Frame', 'three.js'] },
    { slug: '360-video-journalism', en: '360 video and immersive journalism', hi: '360 वीडियो और इमर्सिव जर्नलिज़्म', qids: ['Q6004904'], keywords: ['360 video', 'immersive journalism', 'VR documentary', 'panoramic camera'] },
    { slug: 'xr-in-indian-education', en: 'XR in Indian classrooms and heritage tourism', hi: 'भारतीय क्लासरूम और विरासत पर्यटन में एक्सआर', keywords: ['VR education India', 'virtual heritage tour', 'ASI monuments AR', 'skill training simulator'] },
    { slug: 'metaverse-hype-and-decline', en: 'The metaverse hype cycle and the crash', hi: 'मेटावर्स का हाइप और फिर गिरावट', qids: ['Q2303838'], keywords: ['metaverse hype', 'Meta rebrand 2021', 'Reality Labs losses', 'hype cycle'] },
    { slug: 'ar-in-shopping-and-maps', en: 'AR in shopping apps and live navigation', hi: 'शॉपिंग ऐप और नेविगेशन में एआर', keywords: ['AR try-on', 'IKEA Place', 'Google Live View', 'AR navigation'] },
  ],
};
