import type { CategoryDef } from '../taxonomy-types.js';

export const actors: CategoryDef = {
  id: 4,
  slug: 'actors-actresses',
  en: 'Actors & Actresses',
  hi: 'अभिनेता और अभिनेत्रियाँ',
  emoji: '🌟',
  kidsSafe: true,
  subtopics: [
    { slug: 'dilip-kumar', en: 'Dilip Kumar, the tragedy king', hi: 'दिलीप कुमार, ट्रैजेडी किंग', qids: ['Q102426403'], keywords: ['Dilip Kumar', 'Devdas 1955', 'Mughal-e-Azam', 'Yusuf Khan'] },
    { slug: 'raj-kapoor-actor', en: 'Raj Kapoor as actor and showman', hi: 'राज कपूर: ऐक्टर और शोमैन', qids: ['Q55407'], keywords: ['Raj Kapoor', 'Shree 420', 'tramp persona', 'RK Films'] },
    { slug: 'dev-anand', en: 'Dev Anand and the evergreen style', hi: 'देव आनंद और उनका सदाबहार अंदाज़', qids: ['Q320115'], keywords: ['Dev Anand', 'Guide', 'Navketan Films', 'Jewel Thief'] },
    { slug: 'amitabh-bachchan', en: 'Amitabh Bachchan', hi: 'अमिताभ बच्चन', qids: ['Q9570'], keywords: ['Amitabh Bachchan', 'Deewaar', 'Sholay', 'Kaun Banega Crorepati'] },
    { slug: 'the-three-khans', en: 'The three Khans of the 1990s', hi: '90 के दशक के तीन ख़ान', qids: ['Q9535'], keywords: ['Shah Rukh Khan', 'Salman Khan', 'Aamir Khan', 'Bollywood 1990s stars'] },
    { slug: 'rajinikanth', en: 'Rajinikanth and the superstar phenomenon', hi: 'रजनीकांत और सुपरस्टार का जादू', qids: ['Q60068'], keywords: ['Rajinikanth', 'Tamil cinema', 'Baashha', 'fan clubs'] },
    { slug: 'kamal-haasan', en: 'Kamal Haasan and transformation roles', hi: 'कमल हासन और उनके बदलते किरदार', qids: ['Q381477'], keywords: ['Kamal Haasan', 'Nayakan', 'Dasavathaaram', 'prosthetic makeup'] },
    { slug: 'mgr-and-ntr-actor-politicians', en: 'MGR, NTR and actors who became chief ministers', hi: 'एमजीआर, एनटीआर और मुख्यमंत्री बने ऐक्टर', qids: ['Q127868'], keywords: ['M. G. Ramachandran', 'N. T. Rama Rao', 'Jayalalithaa', 'actor turned politician'] },
    { slug: 'waheeda-rehman', en: 'Waheeda Rehman', hi: 'वहीदा रहमान', qids: ['Q465859'], keywords: ['Waheeda Rehman', 'Pyaasa', 'Guide', 'Chaudhvin Ka Chand'] },
    { slug: 'nutan-and-nargis', en: 'Nutan and Nargis', hi: 'नूतन और नरगिस', qids: ['Q159169'], keywords: ['Nutan', 'Nargis', 'Bandini', 'Mother India'] },
    { slug: 'sridevi', en: 'Sridevi across four film industries', hi: 'चार फ़िल्म इंडस्ट्री की श्रीदेवी', qids: ['Q270691'], keywords: ['Sridevi', 'Chandni', 'Mr. India', 'Tamil Telugu Hindi films'] },
    { slug: 'madhuri-dixit', en: 'Madhuri Dixit', hi: 'माधुरी दीक्षित', qids: ['Q232451'], keywords: ['Madhuri Dixit', 'Hum Aapke Hain Koun', 'Tezaab', 'Devdas'] },
    { slug: 'shabana-and-smita', en: 'Shabana Azmi and Smita Patil', hi: 'शबाना आज़मी और स्मिता पाटिल', qids: ['Q465863'], keywords: ['Shabana Azmi', 'Smita Patil', 'parallel cinema actresses', 'Arth'] },
    { slug: 'irrfan-khan', en: 'Irrfan Khan’s crossover career', hi: 'इरफ़ान ख़ान का क्रॉसओवर करियर', qids: ['Q360927'], keywords: ['Irrfan Khan', 'The Lunchbox', 'Life of Pi', 'Paan Singh Tomar'] },
    { slug: 'naseeruddin-shah-om-puri', en: 'Naseeruddin Shah and Om Puri', hi: 'नसीरुद्दीन शाह और ओम पुरी', qids: ['Q469945'], keywords: ['Naseeruddin Shah', 'Om Puri', 'NSD', 'Ardh Satya'] },
    { slug: 'villains-of-hindi-cinema', en: 'Pran, Amrish Puri and the great villains', hi: 'प्राण, अमरीश पुरी और मशहूर विलेन', qids: ['Q333443'], keywords: ['Pran actor', 'Amrish Puri', 'Mogambo', 'Bollywood villain'] },
    { slug: 'comedians-of-hindi-cinema', en: 'Johnny Walker, Mehmood and film comedians', hi: 'जॉनी वॉकर, महमूद और फ़िल्मी कॉमेडियन', qids: ['Q100943999'], keywords: ['Johnny Walker', 'Mehmood', 'Kishore Kumar comedy', 'comic sidekick'] },
    { slug: 'priyanka-chopra-crossover', en: 'Priyanka Chopra and Indian actors in Hollywood', hi: 'प्रियंका चोपड़ा और हॉलीवुड में भारतीय कलाकार', qids: ['Q158957'], keywords: ['Priyanka Chopra', 'Quantico', 'Indian actors Hollywood', 'crossover career'] },
    { slug: 'charlie-chaplin', en: 'Charlie Chaplin and the Tramp', hi: 'चार्ली चैप्लिन और उनका ट्रैंप', qids: ['Q882'], keywords: ['Charlie Chaplin', 'The Tramp', 'City Lights', 'The Great Dictator'] },
    { slug: 'marlon-brando', en: 'Marlon Brando', hi: 'मार्लन ब्रैंडो', qids: ['Q34012'], keywords: ['Marlon Brando', 'On the Waterfront', 'The Godfather', 'Oscar refusal'] },
    { slug: 'audrey-hepburn', en: 'Audrey Hepburn', hi: 'ऑड्रे हेपबर्न', qids: ['Q42786'], keywords: ['Audrey Hepburn', 'Roman Holiday', 'Breakfast at Tiffany’s', 'UNICEF'] },
    { slug: 'meryl-streep', en: 'Meryl Streep and the record for nominations', hi: 'मेरिल स्ट्रीप और सबसे ज़्यादा नामांकन', qids: ['Q873'], keywords: ['Meryl Streep', 'accent work', 'Oscar nominations record', 'Sophie’s Choice'] },
    { slug: 'tom-hanks', en: 'Tom Hanks', hi: 'टॉम हैंक्स', qids: ['Q2263'], keywords: ['Tom Hanks', 'Forrest Gump', 'Cast Away', 'back-to-back Oscars'] },
    { slug: 'leonardo-dicaprio', en: 'Leonardo DiCaprio', hi: 'लियोनार्डो डिकैप्रियो', qids: ['Q38111'], keywords: ['Leonardo DiCaprio', 'Titanic', 'The Revenant', 'first Oscar 2016'] },
    { slug: 'denzel-and-poitier', en: 'Sidney Poitier and Denzel Washington', hi: 'सिडनी पोइटियर और डेन्ज़ल वॉशिंगटन', qids: ['Q104049'], keywords: ['Sidney Poitier', 'Denzel Washington', 'first Black Best Actor', 'Training Day'] },
    { slug: 'bruce-lee', en: 'Bruce Lee', hi: 'ब्रूस ली', qids: ['Q16397'], keywords: ['Bruce Lee', 'Enter the Dragon', 'Jeet Kune Do', 'martial arts cinema'] },
    { slug: 'jackie-chan-stunts', en: 'Jackie Chan and doing his own stunts', hi: 'जैकी चैन और उनके अपने स्टंट', qids: ['Q36970'], keywords: ['Jackie Chan', 'Hong Kong action cinema', 'stunt injuries', 'Police Story'] },
    { slug: 'toshiro-mifune-kurosawa', en: 'Toshiro Mifune and Kurosawa', hi: 'तोशीरो मिफ़ुने और कुरोसावा', qids: ['Q37001'], keywords: ['Toshiro Mifune', 'Akira Kurosawa', 'Seven Samurai', 'Yojimbo'] },
    { slug: 'typecasting', en: 'Typecasting and how actors escape it', hi: 'टाइपकास्टिंग और उससे निकलना', qids: ['Q444259'], keywords: ['typecasting', 'image change', 'against type casting', 'career reinvention'] },
    { slug: 'body-transformation-roles', en: 'Actors who transformed their bodies for a role', hi: 'किरदार के लिए शरीर बदलने वाले ऐक्टर', qids: ['Q45772'], keywords: ['weight gain for role', 'physical transformation actor', 'Christian Bale', 'Aamir Khan Dangal'] },
    { slug: 'child-stars', en: 'Child actors and what happened to them', hi: 'बाल कलाकार और उनका आगे क्या हुआ', qids: ['Q970153'], keywords: ['child actor', 'Masoom', 'Shirley Temple', 'child star career'] },
    { slug: 'stunt-doubles-and-body-doubles', en: 'Stunt doubles and body doubles', hi: 'स्टंट डबल और बॉडी डबल', qids: ['Q7628798'], keywords: ['stunt double', 'body double', 'fight master India', 'uncredited performer'] },
    { slug: 'dubbing-artists', en: 'Dubbing artists and the voices behind stars', hi: 'डबिंग आर्टिस्ट और सितारों के पीछे की आवाज़ें', qids: ['Q107389581'], keywords: ['dubbing artist', 'voice actor India', 'Hindi dub', 'looping'] },
    { slug: 'highest-paid-actors', en: 'The highest-paid actors and how fees work', hi: 'सबसे ज़्यादा फ़ीस लेने वाले ऐक्टर', keywords: ['highest paid actor', 'backend points', 'profit participation', 'star fee'] },
    { slug: 'acting-schools', en: 'NSD, RADA and the acting schools', hi: 'एनएसडी, राडा और ऐक्टिंग स्कूल', qids: ['Q3595808'], keywords: ['National School of Drama', 'RADA', 'Juilliard', 'drama school'] },
  ],
};
