import type { CategoryDef } from '../taxonomy-types.js';

export const animals: CategoryDef = {
  id: 14,
  slug: 'animals-wildlife',
  en: 'Animals & Wildlife',
  hi: 'जानवर और वन्यजीव',
  emoji: '🐘',
  kidsSafe: true,
  subtopics: [
    { slug: 'bengal-tiger-and-project-tiger', en: 'The Bengal tiger and Project Tiger', hi: 'बंगाल टाइगर और प्रोजेक्ट टाइगर', qids: ['Q19939'], keywords: ['Bengal tiger', 'Project Tiger', 'tiger reserve', 'Ranthambore'] },
    { slug: 'asiatic-lions-of-gir', en: 'The Asiatic lions of Gir', hi: 'गिर के एशियाई शेर', qids: ['Q140'], keywords: ['Asiatic lion', 'Gir forest', 'Gujarat', 'population census'] },
    { slug: 'indian-elephants', en: 'Indian elephants', hi: 'भारतीय हाथी', qids: ['Q591305'], keywords: ['Indian elephant', 'Elephas maximus', 'elephant corridor', 'herd'] },
    { slug: 'one-horned-rhino-of-kaziranga', en: 'The one-horned rhino of Kaziranga', hi: 'काज़ीरंगा का एक सींग वाला गैंडा', qids: ['Q47910'], keywords: ['Indian rhinoceros', 'Kaziranga', 'Assam', 'poaching'] },
    { slug: 'snow-leopard-of-the-himalayas', en: 'The snow leopard of the Himalayas', hi: 'हिमालय का हिम तेंदुआ', qids: ['Q30197'], keywords: ['snow leopard', 'Ladakh', 'Hemis', 'camera trap'] },
    { slug: 'indian-peafowl', en: 'The Indian peafowl', hi: 'मोर', qids: ['Q61865'], keywords: ['Indian peafowl', 'peacock', 'national bird', 'courtship display'] },
    { slug: 'king-cobra-and-indian-snakes', en: 'The king cobra and India’s snakes', hi: 'किंग कोबरा और भारत के साँप', qids: ['Q48186'], keywords: ['king cobra', 'Russell viper', 'big four snakes', 'Agumbe'] },
    { slug: 'olive-ridley-arribada', en: 'Olive Ridley turtles and the arribada', hi: 'ऑलिव रिडले कछुए और अरिबाडा', qids: ['Q282385'], keywords: ['Olive Ridley turtle', 'arribada', 'Gahirmatha', 'Odisha nesting'] },
    { slug: 'great-indian-bustard', en: 'The Great Indian Bustard', hi: 'गोडावण, ग्रेट इंडियन बस्टर्ड', qids: ['Q864359'], keywords: ['Great Indian Bustard', 'Godawan', 'Desert National Park', 'power lines'] },
    { slug: 'western-ghats-endemic-frogs', en: 'Endemic frogs of the Western Ghats', hi: 'पश्चिमी घाट के अनोखे मेंढक', qids: ['Q311152'], keywords: ['purple frog', 'Western Ghats', 'endemic amphibian', 'Nasikabatrachus'] },
    { slug: 'sundarbans-wildlife', en: 'Wildlife of the Sundarbans mangroves', hi: 'सुंदरबन के जंगल के जानवर', qids: ['Q4526'], keywords: ['Sundarbans', 'mangrove', 'swimming tiger', 'estuarine crocodile'] },
    { slug: 'indian-vulture-decline', en: 'The collapse of India’s vultures', hi: 'भारत में गिद्धों की घटती आबादी', qids: ['Q248086'], keywords: ['Indian vulture', 'diclofenac', 'vulture decline', 'scavenger'] },
    { slug: 'cheetah-reintroduction-in-india', en: 'Bringing cheetahs back to India', hi: 'भारत में चीतों की वापसी', qids: ['Q23907'], keywords: ['cheetah', 'Kuno National Park', 'reintroduction', 'Namibia'] },
    { slug: 'indian-cattle-breeds', en: 'Indian cattle breeds', hi: 'भारतीय गाय की नस्लें', qids: ['Q830'], keywords: ['Gir cow', 'Sahiwal', 'zebu', 'humped cattle'] },
    { slug: 'crocodiles-and-gharials', en: 'Crocodiles and the gharial', hi: 'मगरमच्छ और घड़ियाल', qids: ['Q17134'], keywords: ['gharial', 'mugger crocodile', 'Chambal', 'saltwater crocodile'] },
    { slug: 'siberian-cranes-and-bird-migration', en: 'Bird migration and the Siberian crane', hi: 'पक्षियों का प्रवास और साइबेरियन सारस', qids: ['Q216507'], keywords: ['bird migration', 'Siberian crane', 'flyway', 'Bharatpur'] },
    { slug: 'blue-whale', en: 'The blue whale', hi: 'ब्लू व्हेल', qids: ['Q98411645'], keywords: ['blue whale', 'largest animal', 'baleen', 'whale song'] },
    { slug: 'octopus-intelligence', en: 'How clever an octopus is', hi: 'ऑक्टोपस कितना समझदार होता है', qids: ['Q611843'], keywords: ['octopus', 'cephalopod', 'camouflage', 'problem solving'] },
    { slug: 'deep-sea-creatures', en: 'Creatures of the deep sea', hi: 'गहरे समंदर के जीव', qids: ['Q114477253'], keywords: ['anglerfish', 'hydrothermal vent', 'bioluminescence', 'deep sea'] },
    { slug: 'great-white-shark', en: 'The great white shark', hi: 'ग्रेट व्हाइट शार्क', qids: ['Q381941'], keywords: ['great white shark', 'shark teeth', 'breaching', 'tagging'] },
    { slug: 'penguins-of-the-southern-ocean', en: 'Penguins of the southern ocean', hi: 'दक्षिणी समंदर के पेंगुइन', qids: ['Q9147'], keywords: ['penguin', 'emperor penguin', 'Antarctica', 'colony'] },
    { slug: 'honey-bees-and-the-waggle-dance', en: 'Honey bees and the waggle dance', hi: 'शहद की मक्खियाँ और उनका वैगल डांस', qids: ['Q11223525'], keywords: ['honey bee', 'waggle dance', 'hive', 'pollination'] },
    { slug: 'ant-colonies', en: 'How ant colonies work', hi: 'चींटियों की कॉलोनी कैसे चलती है', qids: ['Q796575'], keywords: ['ant colony', 'pheromone trail', 'leafcutter ant', 'queen ant'] },
    { slug: 'monarch-butterfly-migration', en: 'The monarch butterfly migration', hi: 'मोनार्क तितली का सफ़र', qids: ['Q18148122'], keywords: ['monarch butterfly', 'migration', 'Mexico overwintering', 'milkweed'] },
    { slug: 'dinosaurs-of-the-cretaceous', en: 'Dinosaurs of the Cretaceous', hi: 'क्रिटेशियस युग के डायनासोर', qids: ['Q430'], keywords: ['Tyrannosaurus', 'Triceratops', 'Cretaceous', 'fossil'] },
    { slug: 'woolly-mammoth-and-ice-age-fauna', en: 'The woolly mammoth and ice age animals', hi: 'ऊनी मैमथ और हिम युग के जानवर', qids: ['Q3699044'], keywords: ['woolly mammoth', 'ice age', 'sabre-tooth cat', 'permafrost'] },
    { slug: 'the-dodo-and-extinction', en: 'The dodo and how species vanish', hi: 'डोडो और जानवरों का विलुप्त होना', qids: ['Q1027'], keywords: ['dodo', 'Mauritius', 'extinction', 'passenger pigeon'] },
    { slug: 'giant-panda-conservation', en: 'Saving the giant panda', hi: 'जायंट पांडा को बचाने की कोशिश', qids: ['Q33602'], keywords: ['giant panda', 'bamboo diet', 'Sichuan', 'breeding centre'] },
    { slug: 'coral-reefs-and-their-life', en: 'Coral reefs and the life in them', hi: 'मूँगे की चट्टानें और उनका जीवन', qids: ['Q11292'], keywords: ['coral reef', 'bleaching', 'clownfish', 'Lakshadweep'] },
    { slug: 'animal-navigation', en: 'How animals find their way', hi: 'जानवर रास्ता कैसे ढूँढते हैं', qids: ['Q4086918'], keywords: ['animal navigation', 'magnetoreception', 'homing pigeon', 'star compass'] },
    { slug: 'venom-and-antivenom', en: 'Venom and antivenom', hi: 'ज़हर और एंटीवेनम', qids: ['Q38576222'], keywords: ['snake venom', 'antivenom', 'Irula snake catchers', 'toxin'] },
    { slug: 'domestication-of-dogs', en: 'How dogs became our companions', hi: 'कुत्ते इंसान के साथी कैसे बने', qids: ['Q144'], keywords: ['dog domestication', 'wolf ancestry', 'dog breeds', 'Indian pariah dog'] },
    { slug: 'cats-and-their-senses', en: 'Cats and their senses', hi: 'बिल्लियाँ और उनकी इंद्रियाँ', qids: ['Q146'], keywords: ['cat', 'whiskers', 'night vision', 'purring'] },
    { slug: 'bats-and-echolocation', en: 'Bats and echolocation', hi: 'चमगादड़ और इकोलोकेशन', qids: ['Q217270'], keywords: ['bat', 'echolocation', 'fruit bat', 'roost'] },
    { slug: 'animal-lifespans-and-heartbeats', en: 'Animal lifespans and heartbeats', hi: 'जानवरों की उम्र और दिल की धड़कन', qids: ['Q104841969'], keywords: ['lifespan', 'heart rate', 'tortoise age', 'metabolism'] },
    { slug: 'flightless-birds', en: 'Birds that cannot fly', hi: 'जो पंछी उड़ नहीं सकते', qids: ['Q7107739'], keywords: ['ostrich', 'emu', 'kiwi bird', 'flightless'] },
  ],
};
