import type { CategoryDef } from '../taxonomy-types.js';

export const technology: CategoryDef = {
  id: 16,
  slug: 'technology-internet',
  en: 'Technology & The Internet',
  hi: 'तकनीक और इंटरनेट',
  emoji: '💻',
  kidsSafe: true,
  subtopics: [
    { slug: 'arpanet-first-message', en: 'The first ARPANET message, 1969', hi: 'पहला अरपानेट मैसेज, 1969', keywords: ['ARPANET', '1969', 'UCLA Stanford', 'packet switching'] },
    { slug: 'world-wide-web-invention', en: 'Tim Berners-Lee invents the Web', hi: 'टिम बर्नर्स-ली और वर्ल्ड वाइड वेब', qids: ['Q466'], keywords: ['World Wide Web', 'CERN', '1989', 'first website'] },
    { slug: 'dns-and-domain-names', en: 'DNS and domain names', hi: 'डीएनएस और डोमेन नेम', qids: ['Q32635'], keywords: ['DNS', 'domain name', 'root servers', 'dot in domain'] },
    { slug: 'undersea-internet-cables', en: 'The undersea cables that carry the internet', hi: 'समंदर के नीचे बिछी इंटरनेट केबलें', qids: ['Q104711251'], keywords: ['submarine cable', 'fibre optic', 'cable landing station', 'SEA-ME-WE'] },
    { slug: 'http-and-the-404-error', en: 'HTTP and the 404 error', hi: 'एचटीटीपी और 404 एरर', qids: ['Q140185855'], keywords: ['HTTP', 'status code', '404 not found', 'web protocol'] },
    { slug: 'unix-at-bell-labs', en: 'Unix at Bell Labs', hi: 'बेल लैब्स का यूनिक्स', qids: ['Q217365'], keywords: ['Unix', 'Bell Labs', 'Ken Thompson', 'Dennis Ritchie'] },
    { slug: 'linux-and-linus-torvalds', en: 'Linux and Linus Torvalds', hi: 'लिनक्स और लिनस टोरवाल्ड्स', qids: ['Q34253'], keywords: ['Linux', 'Torvalds', 'open source', 'kernel'] },
    { slug: 'python-programming-language', en: 'The Python programming language', hi: 'पायथन प्रोग्रामिंग भाषा', qids: ['Q28865'], keywords: ['Python', 'Guido van Rossum', 'Monty Python', 'indentation'] },
    { slug: 'javascript-in-ten-days', en: 'JavaScript, written in ten days', hi: 'दस दिन में बनी जावास्क्रिप्ट', qids: ['Q2005'], keywords: ['JavaScript', 'Brendan Eich', 'Netscape', '1995'] },
    { slug: 'grace-hopper-and-cobol', en: 'Grace Hopper and COBOL', hi: 'ग्रेस हॉपर और कोबोल', qids: ['Q11641'], keywords: ['Grace Hopper', 'COBOL', 'compiler', 'first computer bug'] },
    { slug: 'ada-lovelace-first-program', en: 'Ada Lovelace and the first program', hi: 'एडा लवलेस और दुनिया का पहला प्रोग्राम', qids: ['Q7259'], keywords: ['Ada Lovelace', 'Analytical Engine', 'Charles Babbage', 'Note G'] },
    { slug: 'alan-turing-and-the-turing-test', en: 'Alan Turing and the Turing test', hi: 'एलन ट्यूरिंग और ट्यूरिंग टेस्ट', qids: ['Q7251'], keywords: ['Alan Turing', 'Turing test', 'Enigma', 'Bletchley Park'] },
    { slug: 'eniac-and-early-computers', en: 'ENIAC and the first computers', hi: 'एनिऐक और शुरुआती कंप्यूटर', qids: ['Q3574371'], keywords: ['ENIAC', 'vacuum tube', 'Colossus', 'women programmers'] },
    { slug: 'transistor-invention-1947', en: 'The invention of the transistor, 1947', hi: 'ट्रांज़िस्टर का आविष्कार, 1947', qids: ['Q5339'], keywords: ['transistor', 'Bell Labs', 'Bardeen Brattain', 'Shockley'] },
    { slug: 'moores-law', en: 'Moore’s law', hi: 'मूर का नियम', qids: ['Q178655'], keywords: ['Moore law', 'Gordon Moore', 'transistor count', 'Intel'] },
    { slug: 'macintosh-1984-ad', en: 'The Macintosh and the 1984 ad', hi: 'मैकिन्टॉश और 1984 वाला विज्ञापन', qids: ['Q75687'], keywords: ['Macintosh', '1984 Apple ad', 'Ridley Scott', 'Super Bowl'] },
    { slug: 'microsoft-and-windows', en: 'Microsoft, MS-DOS and Windows', hi: 'माइक्रोसॉफ़्ट, एमएस-डॉस और विंडोज़', qids: ['Q2283'], keywords: ['Microsoft', 'MS-DOS', 'Windows 95', 'Bill Gates'] },
    { slug: 'google-and-pagerank', en: 'Google and PageRank', hi: 'गूगल और पेजरैंक', qids: ['Q95'], keywords: ['Google', 'PageRank', 'Larry Page', 'Sergey Brin'] },
    { slug: 'wikipedia-and-crowdsourcing', en: 'Wikipedia and crowdsourced knowledge', hi: 'विकिपीडिया और भीड़ का जमा किया ज्ञान', qids: ['Q52'], keywords: ['Wikipedia', 'Jimmy Wales', 'Nupedia', 'edit war'] },
    { slug: 'y2k-bug', en: 'The Y2K bug', hi: 'वाई-टू-के बग', qids: ['Q218941'], keywords: ['Y2K', 'millennium bug', 'two digit year', 'Indian IT industry'] },
    { slug: 'email-and-the-at-sign', en: 'Email and the @ sign', hi: 'ईमेल और @ का निशान', qids: ['Q3930642'], keywords: ['email', 'Ray Tomlinson', 'at sign', 'SMTP'] },
    { slug: 'spam-phishing-and-scams', en: 'Spam, phishing and online scams', hi: 'स्पैम, फ़िशिंग और ऑनलाइन ठगी', qids: ['Q135005'], keywords: ['spam', 'phishing', 'advance fee fraud', 'Monty Python spam'] },
    { slug: 'computer-viruses-and-worms', en: 'Computer viruses and worms', hi: 'कंप्यूटर वायरस और वर्म', qids: ['Q485'], keywords: ['computer virus', 'Morris worm', 'ILOVEYOU', 'Stuxnet'] },
    { slug: 'public-key-cryptography', en: 'Public key cryptography', hi: 'पब्लिक-की क्रिप्टोग्राफ़ी', qids: ['Q201339'], keywords: ['RSA', 'public key', 'Diffie-Hellman', 'encryption'] },
    { slug: 'emoji-and-unicode', en: 'Emoji and Unicode', hi: 'इमोजी और यूनिकोड', qids: ['Q13219644'], keywords: ['Unicode', 'emoji', 'Shigetaka Kurita', 'UTF-8'] },
    { slug: 'qwerty-keyboard-layout', en: 'Why the keyboard says QWERTY', hi: 'कीबोर्ड पर क्वर्टी क्यों लिखा है', qids: ['Q253'], keywords: ['QWERTY', 'typewriter', 'Dvorak layout', 'Christopher Sholes'] },
    { slug: 'the-mother-of-all-demos', en: 'The mouse and the 1968 demo', hi: 'माउस और 1968 वाला मशहूर डेमो', qids: ['Q92614'], keywords: ['Douglas Engelbart', 'computer mouse', 'Mother of All Demos', 'hypertext'] },
    { slug: 'the-smartphone-arrives', en: 'When the smartphone arrived', hi: 'स्मार्टफ़ोन का दौर शुरू हुआ', qids: ['Q22645'], keywords: ['smartphone', 'iPhone 2007', 'BlackBerry', 'Nokia 3310'] },
    { slug: 'indias-it-boom-bengaluru', en: 'India’s IT boom and Bengaluru', hi: 'भारत का आईटी उछाल और बेंगलुरु', keywords: ['Infosys', 'TCS', 'Bangalore software', 'body shopping'] },
    { slug: 'aadhaar-and-digital-identity', en: 'Aadhaar and digital identity', hi: 'आधार और डिजिटल पहचान', qids: ['Q12052688'], keywords: ['Aadhaar', 'UIDAI', 'biometric', 'digital identity'] },
    { slug: 'jio-and-cheap-mobile-data', en: 'Jio and the cheapest mobile data', hi: 'जियो और सबसे सस्ता मोबाइल डेटा', qids: ['Q18643672'], keywords: ['Reliance Jio', 'mobile data price', '4G rollout India', 'telecom'] },
    { slug: 'youtube-and-online-video', en: 'YouTube and online video', hi: 'यूट्यूब और ऑनलाइन वीडियो', qids: ['Q866'], keywords: ['YouTube', 'Me at the zoo', 'creator economy', 'video streaming'] },
    { slug: 'cloud-computing-and-data-centres', en: 'Cloud computing and data centres', hi: 'क्लाउड कंप्यूटिंग और डेटा सेंटर', qids: ['Q483639'], keywords: ['cloud computing', 'AWS', 'data centre cooling', 'server farm'] },
    { slug: 'machine-learning-and-neural-nets', en: 'Machine learning and neural networks', hi: 'मशीन लर्निंग और न्यूरल नेटवर्क', qids: ['Q126568737'], keywords: ['machine learning', 'neural network', 'deep learning', 'backpropagation'] },
  ],
};
