import type { CategoryDef } from '../taxonomy-types.js';

export const physicsChemistry: CategoryDef = {
  id: 15,
  slug: 'physics-chemistry',
  en: 'Physics & Chemistry',
  hi: 'भौतिकी और रसायन विज्ञान',
  emoji: '⚗️',
  kidsSafe: true,
  subtopics: [
    { slug: 'newtons-laws-of-motion', en: 'Newton’s laws of motion', hi: 'न्यूटन के गति के नियम', qids: ['Q935'], keywords: ['Newton laws', 'inertia', 'Principia', 'action reaction'] },
    { slug: 'gravity-and-falling-bodies', en: 'Gravity and falling bodies', hi: 'गुरुत्वाकर्षण और गिरती हुई चीज़ें', qids: ['Q11412'], keywords: ['gravity', 'free fall', 'Galileo', 'escape velocity'] },
    { slug: 'einstein-and-relativity', en: 'Einstein and relativity', hi: 'आइंस्टाइन और सापेक्षता', qids: ['Q937'], keywords: ['relativity', 'E=mc2', 'time dilation', 'spacetime'] },
    { slug: 'the-speed-of-light', en: 'The speed of light', hi: 'रोशनी की रफ़्तार', qids: ['Q3824775'], keywords: ['speed of light', 'Romer', 'light year', 'vacuum constant'] },
    { slug: 'the-atom-and-its-parts', en: 'The atom and its parts', hi: 'परमाणु और उसके हिस्से', qids: ['Q9121'], keywords: ['atom', 'nucleus', 'Rutherford', 'Bohr model'] },
    { slug: 'the-electron', en: 'The electron', hi: 'इलेक्ट्रॉन', qids: ['Q2225'], keywords: ['electron', 'J J Thomson', 'charge', 'cathode ray'] },
    { slug: 'quantum-mechanics-basics', en: 'The strange rules of quantum mechanics', hi: 'क्वांटम मैकेनिक्स के अजीब नियम', qids: ['Q944'], keywords: ['quantum mechanics', 'uncertainty principle', 'superposition', 'Schrodinger'] },
    { slug: 'the-double-slit-experiment', en: 'The double slit experiment', hi: 'डबल स्लिट एक्सपेरिमेंट', qids: ['Q217785'], keywords: ['double slit', 'interference', 'Young experiment', 'wave particle duality'] },
    { slug: 'michelson-morley-experiment', en: 'The Michelson–Morley experiment', hi: 'माइकल्सन-मॉर्ली प्रयोग', qids: ['Q154844'], keywords: ['Michelson Morley', 'luminiferous aether', 'interferometer', '1887'] },
    { slug: 'the-periodic-table', en: 'The periodic table', hi: 'पीरियोडिक टेबल', qids: ['Q10693'], keywords: ['periodic table', 'Mendeleev', 'atomic number', 'element groups'] },
    { slug: 'noble-gases', en: 'The noble gases', hi: 'नोबल गैसें', qids: ['Q81217042'], keywords: ['noble gas', 'helium', 'neon sign', 'argon'] },
    { slug: 'alkali-metals', en: 'The alkali metals', hi: 'अल्कली धातुएँ', qids: ['Q19557'], keywords: ['alkali metal', 'sodium', 'potassium', 'reactivity'] },
    { slug: 'hydrogen', en: 'Hydrogen, the first element', hi: 'हाइड्रोजन, पहला तत्व', qids: ['Q556'], keywords: ['hydrogen', 'fuel cell', 'isotope', 'deuterium'] },
    { slug: 'oxygen-and-breathing', en: 'Oxygen and breathing', hi: 'ऑक्सीजन और साँस', qids: ['Q629'], keywords: ['oxygen', 'combustion', 'Lavoisier', 'ozone'] },
    { slug: 'carbon-and-its-forms', en: 'Carbon: diamond, graphite, graphene', hi: 'कार्बन: हीरा, ग्रेफ़ाइट, ग्राफ़ीन', qids: ['Q623'], keywords: ['carbon', 'diamond', 'graphite', 'graphene'] },
    { slug: 'iron-rust-and-steel', en: 'Iron, rust and steel', hi: 'लोहा, जंग और स्टील', qids: ['Q677'], keywords: ['iron', 'rust', 'steel', 'Delhi iron pillar'] },
    { slug: 'gold-and-precious-metals', en: 'Gold and the precious metals', hi: 'सोना और कीमती धातुएँ', qids: ['Q897'], keywords: ['gold', 'karat', 'platinum', 'malleability'] },
    { slug: 'water-and-its-strange-properties', en: 'Water and its strange properties', hi: 'पानी और उसकी अजीब ख़ूबियाँ', qids: ['Q283'], keywords: ['water', 'hydrogen bond', 'surface tension', 'ice density'] },
    { slug: 'states-of-matter-and-plasma', en: 'States of matter, including plasma', hi: 'पदार्थ की अवस्थाएँ और प्लाज़्मा', qids: ['Q87280720'], keywords: ['states of matter', 'plasma', 'sublimation', 'phase change'] },
    { slug: 'absolute-zero-and-extreme-cold', en: 'Absolute zero and extreme cold', hi: 'परम शून्य और कड़ाके की ठंड', qids: ['Q2822035'], keywords: ['absolute zero', 'kelvin', 'cryogenics', 'liquid nitrogen'] },
    { slug: 'laws-of-thermodynamics', en: 'The laws of thermodynamics', hi: 'ऊष्मागतिकी के नियम', qids: ['Q50682525'], keywords: ['thermodynamics', 'entropy', 'heat engine', 'Carnot'] },
    { slug: 'electricity-and-circuits', en: 'Electricity and circuits', hi: 'बिजली और सर्किट', qids: ['Q11651'], keywords: ['electric current', 'Ohm law', 'voltage', 'circuit'] },
    { slug: 'magnets-and-magnetism', en: 'Magnets and magnetism', hi: 'चुंबक और चुंबकत्व', qids: ['Q993899'], keywords: ['magnet', 'magnetic field', 'Faraday induction', 'compass'] },
    { slug: 'light-reflection-and-refraction', en: 'Reflection, refraction and rainbows', hi: 'परावर्तन, अपवर्तन और इंद्रधनुष', qids: ['Q72277'], keywords: ['refraction', 'prism', 'rainbow', 'lens'] },
    { slug: 'sound-and-waves', en: 'Sound and waves', hi: 'आवाज़ और तरंगें', qids: ['Q7564733'], keywords: ['sound wave', 'Doppler effect', 'decibel', 'ultrasound'] },
    { slug: 'the-raman-effect', en: 'The Raman effect', hi: 'रामन इफ़ेक्ट', qids: ['Q61773290'], keywords: ['Raman effect', 'C V Raman', 'Raman scattering', 'Nobel 1930'] },
    { slug: 'bose-einstein-statistics', en: 'Bose–Einstein statistics and the boson', hi: 'बोस-आइंस्टाइन सांख्यिकी और बोसॉन', qids: ['Q45789'], keywords: ['Satyendra Nath Bose', 'boson', 'Bose Einstein condensate', 'quantum statistics'] },
    { slug: 'saha-ionisation-equation', en: 'The Saha ionisation equation', hi: 'साहा आयनन समीकरण', qids: ['Q377898'], keywords: ['Meghnad Saha', 'ionisation equation', 'stellar spectra', 'astrophysics'] },
    { slug: 'homi-bhabha-and-indian-nuclear-science', en: 'Homi Bhabha and Indian nuclear science', hi: 'होमी भाभा और भारत का परमाणु विज्ञान', qids: ['Q117036303'], keywords: ['Homi Bhabha', 'TIFR', 'BARC', 'cosmic rays'] },
    { slug: 'radioactivity-and-marie-curie', en: 'Radioactivity and Marie Curie', hi: 'रेडियोऐक्टिविटी और मैरी क्यूरी', qids: ['Q7186'], keywords: ['radioactivity', 'radium', 'polonium', 'half life'] },
    { slug: 'uranium-and-nuclear-fission', en: 'Uranium and nuclear fission', hi: 'यूरेनियम और नाभिकीय विखंडन', qids: ['Q1098'], keywords: ['uranium', 'nuclear fission', 'chain reaction', 'reactor'] },
    { slug: 'acids-bases-and-ph', en: 'Acids, bases and pH', hi: 'अम्ल, क्षार और पीएच', qids: ['Q6648610'], keywords: ['acid', 'base', 'pH scale', 'litmus'] },
    { slug: 'chemical-reactions-and-catalysts', en: 'Chemical reactions and catalysts', hi: 'रासायनिक क्रियाएँ और कैटेलिस्ट', qids: ['Q12385831'], keywords: ['catalyst', 'reaction rate', 'Haber process', 'enzyme'] },
    { slug: 'superconductors', en: 'Superconductors', hi: 'सुपरकंडक्टर', qids: ['Q62678863'], keywords: ['superconductivity', 'Meissner effect', 'critical temperature', 'maglev'] },
    { slug: 'lasers-and-how-they-work', en: 'How lasers work', hi: 'लेज़र कैसे काम करते हैं', qids: ['Q36603912'], keywords: ['laser', 'stimulated emission', 'coherent light', 'ruby laser'] },
    { slug: 'plastics-and-polymers', en: 'Plastics and polymers', hi: 'प्लास्टिक और पॉलिमर', qids: ['Q3395619'], keywords: ['polymer', 'plastic', 'Bakelite', 'recycling codes'] },
  ],
};
