import type { CategoryDef } from '../taxonomy-types.js';

export const numbers: CategoryDef = {
  id: 28,
  slug: 'numbers-maths',
  en: 'Numbers & Maths',
  hi: 'संख्याएँ और गणित',
  emoji: '🔢',
  kidsSafe: true,
  subtopics: [
    { slug: 'invention-of-zero', en: 'The invention of zero', hi: 'शून्य का आविष्कार', qids: ['Q204'], keywords: ['zero', 'shunya', 'Gwalior inscription', 'place value'] },
    { slug: 'hindu-arabic-numerals', en: 'How Indian numerals reached the world', hi: 'भारतीय अंक दुनिया तक कैसे पहुँचे', qids: ['Q3059346'], keywords: ['Hindu-Arabic numeral system', 'Fibonacci Liber Abaci', 'al-Khwarizmi', 'decimal'] },
    { slug: 'aryabhata', en: 'Aryabhata', hi: 'आर्यभट', qids: ['Q11359', 'Q3518429'], keywords: ['Aryabhata', 'Aryabhatiya', 'value of pi 3.1416', 'earth rotation'] },
    { slug: 'brahmagupta', en: 'Brahmagupta and the rules for zero', hi: 'ब्रह्मगुप्त और शून्य के नियम', qids: ['Q202943', 'Q1290001'], keywords: ['Brahmagupta', 'Brahmasphutasiddhanta', 'negative numbers', 'cyclic quadrilateral'] },
    { slug: 'bhaskara-ii', en: 'Bhaskara II and the Lilavati', hi: 'भास्कराचार्य और लीलावती', qids: ['Q213385', 'Q3289114'], keywords: ['Bhaskara II', 'Lilavati', 'Siddhanta Shiromani', 'Pell equation'] },
    { slug: 'kerala-school-and-madhava', en: 'The Kerala school and Madhava', hi: 'केरल स्कूल और माधव', qids: ['Q1765138', 'Q115590'], keywords: ['Kerala school', 'Madhava of Sangamagrama', 'infinite series', 'Yuktibhasa'] },
    { slug: 'shulba-sutras', en: 'The geometry of the Shulba Sutras', hi: 'शुल्बसूत्र की ज्यामिति', qids: ['Q84052'], keywords: ['Shulba Sutras', 'Baudhayana', 'altar geometry', 'square root of 2'] },
    { slug: 'bakhshali-manuscript', en: 'The Bakhshali manuscript', hi: 'बख़्शाली पांडुलिपि', qids: ['Q115690'], keywords: ['Bakhshali manuscript', 'birch bark', 'carbon dating', 'earliest zero dot'] },
    { slug: 'pingala-and-binary', en: 'Pingala and binary before binary', hi: 'पिंगल — बाइनरी से पहले की बाइनरी', qids: ['Q527384'], keywords: ['Pingala', 'Chandahshastra', 'binary numbers', 'Meru Prastara'] },
    { slug: 'srinivasa-ramanujan', en: 'Srinivasa Ramanujan', hi: 'श्रीनिवास रामानुजन', qids: ['Q83163'], keywords: ['Srinivasa Ramanujan', 'G. H. Hardy', 'partition function', 'mock theta'] },
    { slug: 'taxicab-number-1729', en: '1729, the taxicab number', hi: '1729 — रामानुजन वाली टैक्सी', qids: ['Q825176'], keywords: ['1729', 'taxicab number', 'sum of two cubes', 'Hardy Ramanujan'] },
    { slug: 'shakuntala-devi', en: 'Shakuntala Devi, the human computer', hi: 'शकुंतला देवी — इंसानी कंप्यूटर', qids: ['Q3181898'], keywords: ['Shakuntala Devi', 'mental calculation', '23rd root', 'Guinness record'] },
    { slug: 'lakh-crore-and-number-names', en: 'Lakh, crore, arab, kharab', hi: 'लाख, करोड़, अरब, खरब', qids: ['Q1143810'], keywords: ['Indian numbering system', 'lakh', 'crore', 'digit grouping'] },
    { slug: 'pi', en: 'Pi', hi: 'पाई (π)', qids: ['Q167'], keywords: ['pi', 'circle constant', 'digits of pi', 'Buffon needle'] },
    { slug: 'eulers-number', en: 'e, the number of growth', hi: 'e — बढ़त वाली संख्या', qids: ['Q82435'], keywords: ['e mathematical constant', 'compound interest', 'natural logarithm', 'Euler'] },
    { slug: 'golden-ratio', en: 'The golden ratio', hi: 'स्वर्णिम अनुपात', qids: ['Q41690'], keywords: ['golden ratio', 'phi', 'Fibonacci link', 'pentagon'] },
    { slug: 'eulers-identity', en: 'Euler’s identity', hi: 'यूलर की पहचान', qids: ['Q204819'], keywords: ['Euler identity', 'e i pi plus one', 'most beautiful equation'] },
    { slug: 'imaginary-numbers', en: 'Imaginary and complex numbers', hi: 'काल्पनिक और सम्मिश्र संख्याएँ', qids: ['Q193796'], keywords: ['imaginary unit', 'complex number', 'square root of minus one', 'Argand plane'] },
    { slug: 'prime-numbers', en: 'Prime numbers', hi: 'अभाज्य संख्याएँ', qids: ['Q49008'], keywords: ['prime number', 'sieve of Eratosthenes', 'infinitude of primes', 'twin primes'] },
    { slug: 'mersenne-primes', en: 'Mersenne primes and the hunt for the biggest', hi: 'मर्सेन अभाज्य और सबसे बड़ी अभाज्य की खोज', qids: ['Q186875'], keywords: ['Mersenne prime', 'GIMPS', 'largest known prime', 'Lucas-Lehmer test'] },
    { slug: 'perfect-numbers', en: 'Perfect numbers', hi: 'पूर्ण संख्याएँ', qids: ['Q170043'], keywords: ['perfect number', '6 and 28', 'aliquot sum', 'odd perfect number'] },
    { slug: 'irrational-numbers', en: 'Irrational numbers', hi: 'अपरिमेय संख्याएँ', qids: ['Q607728'], keywords: ['irrational number', 'square root of 2', 'Hippasus', 'proof by contradiction'] },
    { slug: 'transcendental-numbers', en: 'Transcendental numbers', hi: 'अबीजीय संख्याएँ', qids: ['Q173091'], keywords: ['transcendental number', 'Liouville', 'Lindemann', 'squaring the circle'] },
    { slug: 'fibonacci-sequence', en: 'The Fibonacci sequence', hi: 'फ़िबोनाची शृंखला', qids: ['Q23835349'], keywords: ['Fibonacci sequence', 'Virahanka numbers', 'Sanskrit prosody', 'sunflower spirals'] },
    { slug: 'magic-squares', en: 'Magic squares', hi: 'जादुई वर्ग', qids: ['Q192089'], keywords: ['magic square', 'Khajuraho chautisa yantra', 'Lo Shu', 'Durer Melencolia'] },
    { slug: 'cantor-and-infinity', en: 'Cantor and the sizes of infinity', hi: 'कैंटर और अनंत के आकार', qids: ['Q76420', 'Q205'], keywords: ['Georg Cantor', 'countable set', 'diagonal argument', 'aleph null'] },
    { slug: 'googol-and-large-numbers', en: 'Googol and absurdly large numbers', hi: 'गूगोल और बेतुकी बड़ी संख्याएँ', qids: ['Q507'], keywords: ['googol', 'googolplex', "Graham's number", 'large numbers'] },
    { slug: 'pythagorean-theorem', en: 'The Pythagorean theorem', hi: 'पाइथागोरस प्रमेय', qids: ['Q11518'], keywords: ['Pythagorean theorem', 'Baudhayana', 'Plimpton 322', 'many proofs'] },
    { slug: 'euclids-elements', en: 'Euclid’s Elements', hi: 'यूक्लिड की एलिमेंट्स', qids: ['Q172891'], keywords: ["Euclid's Elements", 'axioms', 'parallel postulate', 'most printed textbook'] },
    { slug: 'fermats-last-theorem', en: 'Fermat’s Last Theorem', hi: 'फ़र्मा की अंतिम प्रमेय', qids: ['Q132469'], keywords: ['Fermat Last Theorem', 'Andrew Wiles', 'margin note', '358 years'] },
    { slug: 'four-colour-theorem', en: 'The four colour theorem', hi: 'चार रंग प्रमेय', qids: ['Q184410'], keywords: ['four color theorem', 'map colouring', 'computer-assisted proof', 'Appel Haken'] },
    { slug: 'goldbach-conjecture', en: 'Goldbach’s conjecture', hi: 'गोल्डबाख का अनुमान', qids: ['Q485520'], keywords: ['Goldbach conjecture', 'even numbers', 'sum of two primes', 'unsolved'] },
    { slug: 'collatz-conjecture', en: 'The Collatz conjecture', hi: 'कोलैट्ज़ अनुमान', qids: ['Q837314'], keywords: ['Collatz conjecture', '3n plus 1', 'hailstone numbers', 'Erdos'] },
    { slug: 'riemann-hypothesis', en: 'The Riemann hypothesis', hi: 'रीमान परिकल्पना', qids: ['Q205966'], keywords: ['Riemann hypothesis', 'zeta function', 'critical line', 'prime distribution'] },
    { slug: 'millennium-prize-problems', en: 'The Millennium Prize Problems', hi: 'मिलेनियम प्राइज़ की समस्याएँ', qids: ['Q727000'], keywords: ['Millennium Prize Problems', 'Clay Institute', 'Poincare conjecture', 'Perelman refusal'] },
    { slug: 'fields-medal', en: 'The Fields Medal', hi: 'फ़ील्ड्स मेडल', qids: ['Q28835'], keywords: ['Fields Medal', 'under 40', 'Manjul Bhargava', 'no Nobel for maths'] },
  ],
};
