import type { CategoryDef } from '../taxonomy-types.js';

export const bollywood: CategoryDef = {
  id: 2,
  slug: 'bollywood',
  en: 'Bollywood',
  hi: 'बॉलीवुड',
  emoji: '🎬',
  kidsSafe: true,
  subtopics: [
    { slug: 'raja-harishchandra-1913', en: 'Raja Harishchandra and Dadasaheb Phalke', hi: 'राजा हरिश्चंद्र और दादासाहेब फाल्के', qids: ['Q2985396'], keywords: ['Raja Harishchandra', 'Dadasaheb Phalke', '1913', 'first Indian feature film'] },
    { slug: 'alam-ara-first-talkie', en: 'Alam Ara, India’s first talkie', hi: 'आलम आरा, भारत की पहली बोलती फ़िल्म', qids: ['Q1280536'], keywords: ['Alam Ara', '1931', 'Ardeshir Irani', 'first sound film India'] },
    { slug: 'bombay-talkies-studio', en: 'Bombay Talkies and the studio era', hi: 'बॉम्बे टॉकीज़ और स्टूडियो का ज़माना', qids: ['Q497661'], keywords: ['Bombay Talkies', 'Himanshu Rai', 'Devika Rani', 'New Theatres'] },
    { slug: 'prithvi-theatres', en: 'Prithviraj Kapoor and Prithvi Theatres', hi: 'पृथ्वीराज कपूर और पृथ्वी थिएटर', qids: ['Q560197'], keywords: ['Prithvi Theatres', 'Prithviraj Kapoor', 'travelling theatre', '1944'] },
    { slug: 'rk-films-raj-kapoor', en: 'RK Films and the Raj Kapoor showman era', hi: 'आरके फ़िल्म्स और राज कपूर का दौर', qids: ['Q55407'], keywords: ['RK Studios', 'Raj Kapoor', 'Awaara', 'Shree 420'] },
    { slug: 'awaara-in-the-soviet-union', en: 'Why Awaara was a hit in the Soviet Union', hi: 'आवारा सोवियत संघ में क्यों छा गई', qids: ['Q858681'], keywords: ['Awaara', 'Soviet Union', 'Awara Hoon', 'Raj Kapoor popularity abroad'] },
    { slug: 'mother-india-1957', en: 'Mother India and the Oscar near-miss', hi: 'मदर इंडिया और ऑस्कर से चूकना', qids: ['Q1411238'], keywords: ['Mother India', 'Mehboob Khan', 'Nargis', '1957 Academy Award'] },
    { slug: 'mughal-e-azam', en: 'Mughal-e-Azam: nine years in the making', hi: 'मुग़ल-ए-आज़म: नौ साल की मेहनत', qids: ['Q1367294'], keywords: ['Mughal-e-Azam', 'K. Asif', 'Pyar Kiya To Darna Kya', 'colourisation'] },
    { slug: 'guru-dutt-films', en: 'Guru Dutt, Pyaasa and Kaagaz Ke Phool', hi: 'गुरु दत्त, प्यासा और काग़ज़ के फूल', qids: ['Q149136'], keywords: ['Guru Dutt', 'Pyaasa', 'Kaagaz Ke Phool', 'V.K. Murthy cinematography'] },
    { slug: 'bimal-roy-social-realism', en: 'Bimal Roy and social realism', hi: 'बिमल रॉय और समाज की सच्चाई वाला सिनेमा', qids: ['Q55405'], keywords: ['Bimal Roy', 'Do Bigha Zamin', 'Sujata', 'Bandini'] },
    { slug: 'playback-singing-system', en: 'How playback singing took over Hindi film', hi: 'हिंदी सिनेमा में प्लेबैक गायकी कैसे आई', qids: ['Q740552'], keywords: ['playback singing', 'Rai Chand Boral', 'lip sync', 'film music recording'] },
    { slug: 'lata-and-asha', en: 'Lata Mangeshkar and Asha Bhosle', hi: 'लता मंगेशकर और आशा भोसले', qids: ['Q156347'], keywords: ['Lata Mangeshkar', 'Asha Bhosle', 'playback singer', 'record catalogue'] },
    { slug: 'rafi-kishore-mukesh', en: 'Rafi, Kishore Kumar and Mukesh', hi: 'रफ़ी, किशोर कुमार और मुकेश', qids: ['Q156815'], keywords: ['Mohammed Rafi', 'Kishore Kumar', 'Mukesh', 'male playback singers'] },
    { slug: 'burman-and-film-composers', en: 'S.D. Burman, R.D. Burman and the music directors', hi: 'एस.डी. बर्मन, आर.डी. बर्मन और संगीतकार', qids: ['Q3351160'], keywords: ['S.D. Burman', 'R.D. Burman', 'Naushad', 'Shankar Jaikishan'] },
    { slug: 'film-lyricists', en: 'The lyricists: Sahir, Shailendra, Gulzar', hi: 'गीतकार: साहिर, शैलेंद्र, गुलज़ार', qids: ['Q1102757'], keywords: ['Sahir Ludhianvi', 'Shailendra', 'Gulzar', 'Majrooh Sultanpuri'] },
    { slug: 'filmfare-awards', en: 'The Filmfare Awards and the Black Lady', hi: 'फ़िल्मफ़ेयर अवॉर्ड और वो काली मूर्ति', qids: ['Q37049'], keywords: ['Filmfare Awards', 'Black Lady trophy', '1954', 'Best Actor'] },
    { slug: 'national-film-awards', en: 'The National Film Awards and Dadasaheb Phalke Award', hi: 'राष्ट्रीय फ़िल्म पुरस्कार और दादासाहेब फाल्के अवॉर्ड', qids: ['Q1350697'], keywords: ['National Film Awards', 'Dadasaheb Phalke Award', 'Swarna Kamal', 'jury'] },
    { slug: 'cbfc-censorship', en: 'The censor board and what it cut', hi: 'सेंसर बोर्ड और उसकी कैंचियाँ', qids: ['Q2944404'], keywords: ['CBFC', 'Central Board of Film Certification', 'banned films India', 'A certificate'] },
    { slug: 'angry-young-man-1970s', en: 'The angry young man of the 1970s', hi: '1970 के दशक का ऐंग्री यंग मैन', qids: ['Q16246674'], keywords: ['angry young man', 'Zanjeer', 'Deewaar', 'Salim-Javed'] },
    { slug: 'amitabh-bachchan-career', en: 'Amitabh Bachchan’s career arc', hi: 'अमिताभ बच्चन का पूरा सफ़र', qids: ['Q9570'], keywords: ['Amitabh Bachchan', 'Coolie accident', 'ABCL', 'Kaun Banega Crorepati'] },
    { slug: 'sholay-1975', en: 'Sholay and the making of Gabbar Singh', hi: 'शोले और गब्बर सिंह का बनना', qids: ['Q949228'], keywords: ['Sholay', 'Ramesh Sippy', 'Gabbar Singh', 'Minerva Theatre run'] },
    { slug: 'parallel-cinema-nfdc', en: 'Parallel cinema and the NFDC', hi: 'समानांतर सिनेमा और एनएफ़डीसी', qids: ['Q7134948'], keywords: ['parallel cinema', 'NFDC', 'Film Finance Corporation', 'Bhuvan Shome'] },
    { slug: 'shyam-benegal-films', en: 'Shyam Benegal: Ankur to Manthan', hi: 'श्याम बेनेगल: अंकुर से मंथन तक', qids: ['Q55406'], keywords: ['Shyam Benegal', 'Ankur', 'Manthan', 'Nishant'] },
    { slug: 'ftii-pune', en: 'FTII Pune and the film schools', hi: 'एफ़टीआईआई पुणे और फ़िल्म स्कूल', qids: ['Q1414326'], keywords: ['FTII Pune', 'Film and Television Institute of India', 'SRFTI', 'alumni'] },
    { slug: 'doordarshan-and-film-on-tv', en: 'Doordarshan, Chitrahaar and Sunday movies', hi: 'दूरदर्शन, चित्रहार और रविवार की फ़िल्म', qids: ['Q1763315'], keywords: ['Doordarshan', 'Chitrahaar', 'Rangoli', 'Sunday evening film'] },
    { slug: 'yash-chopra-foreign-locations', en: 'Yash Chopra and shooting in Switzerland', hi: 'यश चोपड़ा और स्विट्ज़रलैंड की शूटिंग', qids: ['Q30876'], keywords: ['Yash Chopra', 'Switzerland', 'song picturisation', 'chiffon sarees'] },
    { slug: 'ddlj-and-the-diaspora', en: 'DDLJ and the NRI audience', hi: 'डीडीएलजे और एनआरआई दर्शक', qids: ['Q114096233'], keywords: ['Dilwale Dulhania Le Jayenge', 'Maratha Mandir', 'NRI audience', 'overseas box office'] },
    { slug: 'production-houses', en: 'Yash Raj, Dharma and the big banners', hi: 'यशराज, धर्मा और बड़े बैनर', qids: ['Q1696916'], keywords: ['Yash Raj Films', 'Dharma Productions', 'Rajshri', 'production house'] },
    { slug: 'box-office-clubs', en: 'The 100-crore and 1000-crore clubs', hi: '100 करोड़ और 1000 करोड़ क्लब', qids: ['Q4951556'], keywords: ['box office India', '100 crore club', 'gross collection', 'opening weekend'] },
    { slug: 'remakes-and-regional-crossover', en: 'Hindi remakes of South Indian films', hi: 'साउथ की फ़िल्मों के हिंदी रीमेक', qids: ['Q15911952'], keywords: ['remake', 'Tamil to Hindi', 'Telugu remake', 'dubbed version'] },
    { slug: 'item-numbers-and-cabaret', en: 'From cabaret to the item number', hi: 'कैबरे से आइटम नंबर तक', qids: ['Q996838'], keywords: ['item number', 'Helen cabaret', 'dance number', 'Bollywood item song'] },
    { slug: 'choreography-saroj-khan', en: 'Saroj Khan and film choreography', hi: 'सरोज ख़ान और फ़िल्मी कोरियोग्राफ़ी', qids: ['Q3473673'], keywords: ['Saroj Khan', 'choreographer', 'Ek Do Teen', 'Bollywood dance'] },
    { slug: 'single-screen-to-multiplex', en: 'From single screens to multiplexes', hi: 'सिंगल स्क्रीन से मल्टीप्लेक्स तक', keywords: ['single screen cinema', 'multiplex India', 'PVR', 'ticket pricing'] },
    { slug: 'partition-and-hindi-cinema', en: 'Partition and the people who made Bombay cinema', hi: 'बँटवारा और बंबई सिनेमा के लोग', keywords: ['Partition 1947', 'Lahore film industry', 'migration to Bombay', 'Punjabi filmmakers'] },
    { slug: 'golden-age-heroines', en: 'Nargis, Meena Kumari, Madhubala', hi: 'नरगिस, मीना कुमारी, मधुबाला', qids: ['Q159169'], keywords: ['Nargis', 'Meena Kumari', 'Madhubala', 'golden age actresses'] },
  ],
};
