import type { CategoryDef } from '../taxonomy-types.js';

export const strange: CategoryDef = {
  id: 29,
  slug: 'strange-but-true',
  en: 'Strange But True',
  hi: 'अजीब मगर सच',
  emoji: '🤯',
  kidsSafe: true,
  subtopics: [
    { slug: 'odd-laws-still-on-the-books', en: 'Odd laws still on the books', hi: 'क़ानून की किताबों में अब भी दर्ज अजीब धाराएँ', qids: ['Q2907261'], keywords: ['unusual laws', 'blue law', 'obsolete statute', 'repealed'] },
    { slug: 'kite-flying-licence-india', en: 'Why kite flying technically needs a licence in India', hi: 'भारत में पतंग उड़ाने के लिए लाइसेंस क्यों चाहिए', qids: ['Q105470624'], keywords: ['Aircraft Act 1934', 'kite India law', 'definition of aircraft', 'balloon'] },
    { slug: 'india-bangladesh-enclaves', en: 'The India-Bangladesh enclaves', hi: 'भारत-बांग्लादेश की चिटमहल', qids: ['Q645659'], keywords: ['India Bangladesh enclaves', 'chhitmahal', 'Dahala Khagrabari', '2015 land swap'] },
    { slug: 'baarle-hertog-border', en: 'The tangled border of Baarle-Hertog', hi: 'बार्ले-हर्टोग की उलझी हुई सरहद', qids: ['Q244959'], keywords: ['Baarle-Hertog', 'Baarle-Nassau', 'enclave', 'border through house'] },
    { slug: 'half-hour-time-zones', en: 'Time zones off by half an hour', hi: 'आधे-आधे घंटे वाले टाइम ज़ोन', qids: ['Q604055', 'Q3297477', 'Q12143'], keywords: ['Indian Standard Time', 'Nepal Time UTC+5:45', 'time zone', 'China single zone'] },
    { slug: 'international-date-line', en: 'The International Date Line', hi: 'अंतरराष्ट्रीय तिथि रेखा', qids: ['Q131389'], keywords: ['International Date Line', 'Samoa skipped a day', 'Line Islands', 'zigzag'] },
    { slug: 'eleven-missing-days-1752', en: 'The eleven days that never happened', hi: '1752 के वे ग्यारह दिन जो कभी आए ही नहीं', keywords: ['Calendar Act 1750', 'Gregorian calendar', 'September 1752', 'calendar riots'] },
    { slug: 'leap-seconds', en: 'Leap seconds', hi: 'लीप सेकंड', qids: ['Q194230'], keywords: ['leap second', 'UT1', 'earth rotation slowing', '2035 abolition'] },
    { slug: 'unusual-units-of-measurement', en: 'Unusual units of measurement', hi: 'नापने की अजीब इकाइयाँ', keywords: ['smoot', 'barn unit', 'jiffy', 'unusual units'] },
    { slug: 'rai-stones-of-yap', en: 'The stone money of Yap', hi: 'याप द्वीप के पत्थर के सिक्के', qids: ['Q917019'], keywords: ['Rai stones', 'Yap', 'stone money', 'sunken stone still owned'] },
    { slug: 'pitch-drop-experiment', en: 'The pitch drop experiment', hi: 'पिच ड्रॉप प्रयोग', qids: ['Q899222'], keywords: ['pitch drop experiment', 'University of Queensland', '1927', 'nine drops'] },
    { slug: 'mpemba-effect', en: 'The Mpemba effect', hi: 'म्पेम्बा असर', qids: ['Q723510'], keywords: ['Mpemba effect', 'hot water freezing faster', 'Erasto Mpemba', 'replication'] },
    { slug: 'sailing-stones', en: 'The stones that move by themselves', hi: 'अपने आप खिसकने वाले पत्थर', qids: ['Q1546315'], keywords: ['sailing stones', 'Racetrack Playa', 'ice rafts', '2014 explanation'] },
    { slug: 'blood-falls', en: 'Blood Falls in Antarctica', hi: 'अंटार्कटिका का ख़ूनी झरना', qids: ['Q885118'], keywords: ['Blood Falls', 'Taylor Glacier', 'iron oxide', 'subglacial brine'] },
    { slug: 'darvaza-gas-crater', en: 'The Darvaza gas crater', hi: 'दरवाज़ा गैस क्रेटर', qids: ['Q70458'], keywords: ['Darvaza gas crater', 'Door to Hell', 'Turkmenistan', 'burning since 1971'] },
    { slug: 'lake-nyos-disaster', en: 'The lake that exploded with gas', hi: 'वह झील जो गैस के साथ फट पड़ी', qids: ['Q332628'], keywords: ['Lake Nyos', 'limnic eruption', 'carbon dioxide', 'degassing pipes'] },
    { slug: 'gravity-hills', en: 'Magnetic Hill and gravity hills', hi: 'मैग्नेटिक हिल और उल्टी ढलान वाली पहाड़ियाँ', qids: ['Q2086896'], keywords: ['gravity hill', 'Magnetic Hill Ladakh', 'optical illusion', 'false horizon'] },
    { slug: 'lonar-crater-lake', en: 'Lonar, the lake inside a meteor crater', hi: 'लोणार — उल्कापिंड के गड्ढे में बनी झील', qids: ['Q2572189'], keywords: ['Lonar Lake', 'basalt impact crater', 'Maharashtra', 'lake turned pink 2020'] },
    { slug: 'living-root-bridges', en: 'Meghalaya’s living root bridges', hi: 'मेघालय के जड़ों से बने ज़िंदा पुल', qids: ['Q18349989'], keywords: ['living root bridge', 'Khasi', 'Ficus elastica', 'Nongriat double decker'] },
    { slug: 'wettest-place-on-earth', en: 'The wettest place on earth', hi: 'धरती की सबसे ज़्यादा बारिश वाली जगह', keywords: ['Mawsynram', 'Cherrapunji', 'rainfall record', 'Meghalaya'] },
    { slug: 'jatinga-bird-phenomenon', en: 'The birds that fall out of the sky at Jatinga', hi: 'जतिंगा में आसमान से गिरते पक्षी', qids: ['Q3827773'], keywords: ['Jatinga', 'Assam', 'bird phenomenon', 'fog and lights explanation'] },
    { slug: 'red-rain-of-kerala', en: 'The red rain of Kerala', hi: 'केरल की लाल बारिश', qids: ['Q1999205'], keywords: ['red rain Kerala', '2001', 'Trentepohlia spores', 'coloured rain'] },
    { slug: 'shani-shingnapur', en: 'The village with no doors', hi: 'वह गाँव जहाँ दरवाज़े ही नहीं', qids: ['Q2723631'], keywords: ['Shani Shingnapur', 'doorless houses', 'Ahmednagar', 'bank without lock'] },
    { slug: 'tardigrades', en: 'Tardigrades, the animals that survive space', hi: 'टार्डिग्रेड — अंतरिक्ष में भी बच जाने वाले जीव', qids: ['Q5194'], keywords: ['tardigrade', 'water bear', 'cryptobiosis', 'vacuum survival'] },
    { slug: 'immortal-jellyfish', en: 'The jellyfish that can reset its age', hi: 'वह जेलीफ़िश जो अपनी उम्र रीसेट कर लेती है', qids: ['Q3322541'], keywords: ['Turritopsis dohrnii', 'immortal jellyfish', 'transdifferentiation', 'polyp stage'] },
    { slug: 'mantis-shrimp', en: 'The mantis shrimp’s punch', hi: 'मैंटिस श्रिंप का घूँसा', qids: ['Q334855'], keywords: ['mantis shrimp', 'cavitation bubble', 'punch speed', 'colour receptors'] },
    { slug: 'naked-mole-rat', en: 'The naked mole-rat', hi: 'नंगा तिल-चूहा', qids: ['Q276290'], keywords: ['naked mole-rat', 'eusocial mammal', 'cancer resistance', 'cold blooded mammal'] },
    { slug: 'platypus', en: 'The platypus', hi: 'प्लैटिपस', qids: ['Q15343'], keywords: ['platypus', 'egg-laying mammal', 'electroreception', 'venomous spur'] },
    { slug: 'octopus-biology', en: 'Three hearts and blue blood', hi: 'तीन दिल और नीला ख़ून', keywords: ['octopus', 'three hearts', 'haemocyanin', 'arm neurons'] },
    { slug: 'lyrebird-mimicry', en: 'The bird that imitates chainsaws', hi: 'वह पक्षी जो आरी की आवाज़ निकालता है', qids: ['Q757013'], keywords: ['superb lyrebird', 'vocal mimicry', 'camera shutter', 'Australia'] },
    { slug: 'waggle-dance', en: 'How bees give directions', hi: 'मधुमक्खियाँ रास्ता कैसे बताती हैं', qids: ['Q655280'], keywords: ['waggle dance', 'Karl von Frisch', 'honeybee', 'sun angle'] },
    { slug: 'shortest-war-in-history', en: 'The war that lasted 38 minutes', hi: 'वह जंग जो 38 मिनट चली', qids: ['Q170850'], keywords: ['Anglo-Zanzibar War', '1896', 'shortest war', 'Zanzibar'] },
    { slug: 'the-emu-war', en: 'The Emu War', hi: 'एमू वाली जंग', qids: ['Q14665'], keywords: ['Emu War', '1932 Australia', 'machine guns', 'Western Australia wheatbelt'] },
    { slug: 'great-molasses-flood', en: 'The great molasses flood', hi: 'गुड़ के शीरे की बाढ़', qids: ['Q1129089'], keywords: ['Great Molasses Flood', 'Boston 1919', 'burst tank', 'North End'] },
    { slug: 'dagen-h', en: 'The day Sweden switched sides of the road', hi: 'जिस दिन स्वीडन ने सड़क का पाला बदला', qids: ['Q376921'], keywords: ['Dagen H', '1967 Sweden', 'right hand traffic', 'accidents dropped'] },
    { slug: 'year-without-a-summer', en: 'The year without a summer', hi: 'वह साल जिसमें गर्मी आई ही नहीं', qids: ['Q209625'], keywords: ['Year Without a Summer', '1816', 'Mount Tambora', 'snow in June'] },
  ],
};
