import type { CategoryDef } from '../taxonomy-types.js';

export const football: CategoryDef = {
  id: 10,
  slug: 'football',
  en: 'Football',
  hi: 'फ़ुटबॉल',
  emoji: '⚽',
  kidsSafe: true,
  subtopics: [
    { slug: 'laws-of-the-game-1863', en: 'The Laws of the Game, 1863', hi: 'खेल के नियम, 1863', qids: ['Q2736'], keywords: ['Football Association', '1863', 'Laws of the Game', 'IFAB'] },
    { slug: 'fifa-world-cup-history', en: 'The history of the World Cup', hi: 'फ़ीफ़ा वर्ल्ड कप का इतिहास', qids: ['Q1936368'], keywords: ['World Cup', '1930 Uruguay', 'Jules Rimet', 'hosts'] },
    { slug: 'india-and-the-1950-world-cup', en: 'India and the 1950 World Cup', hi: '1950 वर्ल्ड कप और भारत का हटना', keywords: ['1950 World Cup', 'India withdrawal', 'AIFF', 'barefoot myth'] },
    { slug: 'mohun-bagan-1911', en: 'Mohun Bagan and the 1911 IFA Shield', hi: 'मोहन बागान और 1911 की आईएफ़ए शील्ड', qids: ['Q935022'], keywords: ['Mohun Bagan', '1911', 'IFA Shield', 'Calcutta'] },
    { slug: 'durand-cup', en: 'The Durand Cup', hi: 'डूरंड कप', qids: ['Q114941'], keywords: ['Durand Cup', '1888', 'Shimla', 'oldest tournament'] },
    { slug: 'santosh-trophy', en: 'The Santosh Trophy', hi: 'संतोष ट्रॉफ़ी', qids: ['Q3537111'], keywords: ['Santosh Trophy', 'state teams', '1941', 'Bengal'] },
    { slug: 'i-league-and-federation-cup', en: 'The I-League and Federation Cup', hi: 'आई-लीग और फ़ेडरेशन कप', qids: ['Q64690793'], keywords: ['I-League', 'National Football League', 'Federation Cup', 'promotion'] },
    { slug: 'indian-super-league', en: 'The Indian Super League', hi: 'इंडियन सुपर लीग', qids: ['Q16056350'], keywords: ['ISL', '2014', 'franchise football', 'marquee player'] },
    { slug: 'indian-footballs-golden-age', en: 'Indian football’s golden age', hi: 'भारतीय फ़ुटबॉल का सुनहरा दौर', qids: ['Q29267'], keywords: ['1951 Asian Games', '1962 Asian Games', 'Syed Abdul Rahim', 'Melbourne 1956'] },
    { slug: 'the-kolkata-derby', en: 'The Kolkata derby', hi: 'कोलकाता डर्बी', qids: ['Q3023607'], keywords: ['East Bengal', 'Mohun Bagan', 'derby', 'Salt Lake Stadium'] },
    { slug: 'football-in-kerala-and-goa', en: 'Football in Kerala and Goa', hi: 'केरल और गोवा की फ़ुटबॉल संस्कृति', qids: ['Q6393508'], keywords: ['Kerala football', 'Goa football', 'Sevens', 'Dempo'] },
    { slug: 'football-in-the-north-east', en: 'Football in the North-East', hi: 'पूर्वोत्तर भारत का फ़ुटबॉल', qids: ['Q1502'], keywords: ['Mizoram', 'Manipur', 'Aizawl FC', 'NEROCA'] },
    { slug: 'maradona-and-1986', en: 'Maradona and 1986', hi: 'मैराडोना और 1986', qids: ['Q55622123'], keywords: ['Maradona', '1986', 'Hand of God', 'Goal of the Century'] },
    { slug: 'pele-and-brazil', en: 'Pelé and Brazil, 1958-1970', hi: 'पेले और ब्राज़ील, 1958-1970', qids: ['Q155'], keywords: ['Pelé', 'Brazil', '1970', 'jogo bonito'] },
    { slug: 'total-football-1974', en: 'Total Football and the Dutch, 1974', hi: 'टोटल फ़ुटबॉल और नीदरलैंड्स, 1974', qids: ['Q3532675'], keywords: ['Total Football', 'Cruyff', 'Ajax', '1974'] },
    { slug: 'european-cup-to-champions-league', en: 'From European Cup to Champions League', hi: 'यूरोपियन कप से चैंपियंस लीग तक', qids: ['Q1681685'], keywords: ['European Cup', 'Champions League', 'UEFA', '1955'] },
    { slug: 'the-premier-league', en: 'The Premier League', hi: 'प्रीमियर लीग', qids: ['Q9448'], keywords: ['Premier League', '1992', 'broadcast money', 'Leicester 2016'] },
    { slug: 'la-liga-and-el-clasico', en: 'La Liga and El Clásico', hi: 'ला लीगा और एल क्लासिको', qids: ['Q324867'], keywords: ['La Liga', 'El Clásico', 'Barcelona', 'Real Madrid'] },
    { slug: 'serie-a-and-catenaccio', en: 'Serie A and catenaccio', hi: 'सीरी ए और कातेनाचो', qids: ['Q15804'], keywords: ['Serie A', 'catenaccio', 'Milan', 'Juventus'] },
    { slug: 'bundesliga-and-german-football', en: 'The Bundesliga and German football', hi: 'बुंडेसलीगा और जर्मन फ़ुटबॉल', qids: ['Q82595'], keywords: ['Bundesliga', 'Bayern Munich', '50+1 rule', 'Beckenbauer'] },
    { slug: 'african-football-and-afcon', en: 'African football and AFCON', hi: 'अफ़्रीकी फ़ुटबॉल और अफ़कॉन', qids: ['Q1009'], keywords: ['AFCON', 'Cameroon', 'Nigeria', 'Didier Drogba'] },
    { slug: 'south-american-football', en: 'Copa América and South American football', hi: 'कोपा अमेरिका और दक्षिण अमेरिकी फ़ुटबॉल', qids: ['Q178750'], keywords: ['Copa América', 'Libertadores', 'Argentina', 'Uruguay'] },
    { slug: 'asian-cup-and-afc', en: 'The AFC Asian Cup', hi: 'एएफ़सी एशियन कप', qids: ['Q157894'], keywords: ['Asian Cup', 'AFC', 'Japan', 'India 1964'] },
    { slug: 'womens-world-cup-football', en: 'The Women’s World Cup', hi: 'महिला फ़ुटबॉल वर्ल्ड कप', qids: ['Q4630361'], keywords: ['Women’s World Cup', '1991', 'USA', 'attendance records'] },
    { slug: 'messi-and-ronaldo-era', en: 'The Messi and Ronaldo era', hi: 'मेसी और रोनाल्डो का दौर', qids: ['Q615'], keywords: ['Lionel Messi', 'Cristiano Ronaldo', 'goal records', 'rivalry'] },
    { slug: 'goalkeeping', en: 'Goalkeeping', hi: 'गोलकीपिंग', qids: ['Q201330'], keywords: ['goalkeeper', 'gloves', 'sweeper keeper', 'clean sheet'] },
    { slug: 'free-kicks-and-set-pieces', en: 'Free kicks and set pieces', hi: 'फ़्री किक और सेट पीस', qids: ['Q1379266'], keywords: ['free kick', 'corner', 'set piece', 'knuckleball'] },
    { slug: 'the-offside-rule', en: 'The offside rule', hi: 'ऑफ़साइड का नियम', qids: ['Q18531'], keywords: ['offside', 'linesman', 'offside trap', 'rule change'] },
    { slug: 'var-and-goal-line-technology', en: 'VAR and goal-line technology', hi: 'वीएआर और गोल-लाइन तकनीक', qids: ['Q333717'], keywords: ['VAR', 'goal-line technology', 'Hawk-Eye', '2018'] },
    { slug: 'the-football-itself', en: 'The football itself', hi: 'फ़ुटबॉल की गेंद का सफ़र', qids: ['Q3851702'], keywords: ['match ball', 'Telstar', 'Jabulani', 'ball design'] },
    { slug: 'famous-stadiums', en: 'Famous football stadiums', hi: 'दुनिया के मशहूर फ़ुटबॉल स्टेडियम', qids: ['Q2089279'], keywords: ['Maracanã', 'Wembley', 'Camp Nou', 'Salt Lake'] },
    { slug: 'transfer-market-records', en: 'The transfer market and record fees', hi: 'ट्रांसफ़र बाज़ार और रिकॉर्ड सौदे', qids: ['Q322447'], keywords: ['transfer fee', 'Neymar', 'Bosman ruling', 'transfer window'] },
    { slug: 'ballon-dor-and-awards', en: 'The Ballon d’Or and football awards', hi: 'बैलन डी ओर और दूसरे अवॉर्ड', qids: ['Q2881323'], keywords: ['Ballon d’Or', 'FIFA award', 'Golden Boot', 'voting'] },
    { slug: 'formations-and-tactics', en: 'Formations and tactics', hi: 'फ़ॉर्मेशन और रणनीति', qids: ['Q1580095'], keywords: ['4-4-2', 'tiki-taka', 'gegenpressing', 'false nine'] },
    { slug: 'penalty-shootouts', en: 'Penalty shootouts', hi: 'पेनल्टी शूटआउट', qids: ['Q3334022'], keywords: ['penalty shootout', '1976', 'Panenka', 'spot kick'] },
    { slug: 'olympic-football', en: 'Olympic football', hi: 'ओलंपिक फ़ुटबॉल', qids: ['Q3922886'], keywords: ['Olympic football', 'under-23', '1908', 'Hungary'] },
  ],
};
