import type { CategoryDef } from '../taxonomy-types.js';

export const geography: CategoryDef = {
  id: 17,
  slug: 'geography-places',
  en: 'Geography & Places',
  hi: 'भूगोल और जगहें',
  emoji: '🗺️',
  kidsSafe: true,
  subtopics: [
    { slug: 'mount-everest', en: 'Mount Everest and the eight-thousanders', hi: 'माउंट एवरेस्ट और आठ हज़ारी चोटियाँ', qids: ['Q513'], keywords: ['Mount Everest', 'K2', 'eight-thousander', 'Tenzing Norgay'] },
    { slug: 'the-himalayas', en: 'The Himalayas', hi: 'हिमालय', qids: ['Q5451'], keywords: ['Himalaya', 'plate collision', 'glacier', 'Karakoram'] },
    { slug: 'the-western-ghats', en: 'The Western Ghats', hi: 'पश्चिमी घाट', qids: ['Q4527'], keywords: ['Western Ghats', 'Sahyadri', 'biodiversity hotspot', 'Nilgiris'] },
    { slug: 'the-thar-desert', en: 'The Thar desert', hi: 'थार का रेगिस्तान', qids: ['Q172691'], keywords: ['Thar desert', 'Rajasthan', 'sand dunes', 'Indira Gandhi canal'] },
    { slug: 'the-deccan-plateau', en: 'The Deccan plateau and the Deccan Traps', hi: 'दक्कन का पठार और डेक्कन ट्रैप', qids: ['Q169966'], keywords: ['Deccan plateau', 'Deccan Traps', 'basalt', 'black soil'] },
    { slug: 'the-sundarbans-delta', en: 'The Sundarbans delta', hi: 'सुंदरबन डेल्टा', qids: ['Q4526'], keywords: ['Sundarbans', 'mangrove delta', 'Ganges Brahmaputra delta', 'tidal creeks'] },
    { slug: 'the-indian-monsoon', en: 'The Indian monsoon', hi: 'भारतीय मानसून', qids: ['Q110652068'], keywords: ['monsoon', 'southwest monsoon', 'Mawsynram rainfall', 'onset date'] },
    { slug: 'the-ganga-river-system', en: 'The Ganga river system', hi: 'गंगा नदी तंत्र', qids: ['Q5089'], keywords: ['Ganges', 'Gangotri', 'tributaries', 'river basin'] },
    { slug: 'the-brahmaputra', en: 'The Brahmaputra', hi: 'ब्रह्मपुत्र', qids: ['Q133843549'], keywords: ['Brahmaputra', 'Tsangpo', 'Majuli island', 'floods'] },
    { slug: 'indian-states-and-borders', en: 'Indian states and how their borders were drawn', hi: 'भारत के राज्य और उनकी सीमाएँ कैसे बनीं', qids: ['Q3595306'], keywords: ['States Reorganisation', 'linguistic states', 'union territory', 'boundary'] },
    { slug: 'andaman-and-nicobar-islands', en: 'The Andaman and Nicobar islands', hi: 'अंडमान और निकोबार द्वीप', qids: ['Q65040352'], keywords: ['Andaman islands', 'Nicobar', 'Barren Island volcano', 'Sentinelese'] },
    { slug: 'the-rann-of-kutch', en: 'The Rann of Kutch', hi: 'कच्छ का रण', qids: ['Q4026866'], keywords: ['Rann of Kutch', 'salt marsh', 'wild ass sanctuary', 'flamingo'] },
    { slug: 'the-nile', en: 'The Nile', hi: 'नील नदी', qids: ['Q3392'], keywords: ['Nile', 'Blue Nile', 'Aswan dam', 'Nile delta'] },
    { slug: 'the-amazon-basin', en: 'The Amazon river and basin', hi: 'अमेज़न नदी और उसका बेसिन', qids: ['Q3783'], keywords: ['Amazon river', 'rainforest', 'discharge', 'Manaus'] },
    { slug: 'the-sahara-desert', en: 'The Sahara desert', hi: 'सहारा रेगिस्तान', qids: ['Q6583'], keywords: ['Sahara', 'erg dunes', 'oasis', 'Sahel'] },
    { slug: 'the-pacific-ocean', en: 'The Pacific Ocean', hi: 'प्रशांत महासागर', qids: ['Q98'], keywords: ['Pacific Ocean', 'ring of fire', 'atoll', 'currents'] },
    { slug: 'the-atlantic-ocean', en: 'The Atlantic Ocean', hi: 'अटलांटिक महासागर', qids: ['Q97'], keywords: ['Atlantic Ocean', 'Gulf Stream', 'mid-Atlantic ridge', 'Sargasso Sea'] },
    { slug: 'the-indian-ocean', en: 'The Indian Ocean', hi: 'हिंद महासागर', qids: ['Q1239'], keywords: ['Indian Ocean', 'monsoon winds', 'trade route', 'Chagos'] },
    { slug: 'antarctica', en: 'Antarctica', hi: 'अंटार्कटिका', qids: ['Q51'], keywords: ['Antarctica', 'ice sheet', 'Antarctic treaty', 'Maitri station'] },
    { slug: 'the-arctic-and-north-pole', en: 'The Arctic and the North Pole', hi: 'आर्कटिक और उत्तरी ध्रुव', qids: ['Q25322'], keywords: ['Arctic', 'North Pole', 'sea ice', 'Northwest Passage'] },
    { slug: 'volcanoes-and-the-ring-of-fire', en: 'Volcanoes and the Ring of Fire', hi: 'ज्वालामुखी और रिंग ऑफ़ फ़ायर', qids: ['Q8072'], keywords: ['volcano', 'Ring of Fire', 'Krakatoa', 'lava'] },
    { slug: 'earthquakes-and-fault-lines', en: 'Earthquakes and fault lines', hi: 'भूकंप और फ़ॉल्ट लाइनें', qids: ['Q7944'], keywords: ['earthquake', 'San Andreas fault', 'Richter scale', 'seismic zone'] },
    { slug: 'plate-tectonics', en: 'Plate tectonics and drifting continents', hi: 'प्लेट टेक्टोनिक्स और खिसकते महाद्वीप', qids: ['Q7950'], keywords: ['plate tectonics', 'Pangaea', 'continental drift', 'subduction'] },
    { slug: 'the-alps', en: 'The Alps', hi: 'आल्प्स पर्वत', qids: ['Q1286'], keywords: ['Alps', 'Matterhorn', 'Mont Blanc', 'alpine passes'] },
    { slug: 'the-andes', en: 'The Andes', hi: 'एंडीज़ पर्वत', qids: ['Q10411246'], keywords: ['Andes', 'Aconcagua', 'Altiplano', 'Atacama'] },
    { slug: 'the-great-rift-valley', en: 'The Great Rift Valley', hi: 'ग्रेट रिफ़्ट वैली', qids: ['Q81591'], keywords: ['Great Rift Valley', 'East African rift', 'Lake Victoria', 'Afar'] },
    { slug: 'the-mariana-trench', en: 'The Mariana Trench', hi: 'मारियाना ट्रेंच', qids: ['Q510'], keywords: ['Mariana Trench', 'Challenger Deep', 'ocean depth', 'submersible'] },
    { slug: 'the-grand-canyon', en: 'The Grand Canyon', hi: 'ग्रैंड कैन्यन', qids: ['Q52238603'], keywords: ['Grand Canyon', 'Colorado river', 'rock strata', 'erosion'] },
    { slug: 'the-great-barrier-reef', en: 'The Great Barrier Reef', hi: 'ग्रेट बैरियर रीफ़', qids: ['Q7343'], keywords: ['Great Barrier Reef', 'coral bleaching', 'Queensland', 'reef islands'] },
    { slug: 'the-deepest-lakes', en: 'Lake Baikal and the deepest lakes', hi: 'बैकाल झील और सबसे गहरी झीलें', qids: ['Q5513'], keywords: ['Lake Baikal', 'Tanganyika', 'freshwater volume', 'Caspian Sea'] },
    { slug: 'lowest-points-on-land', en: 'The Dead Sea and the lowest places on land', hi: 'मृत सागर और ज़मीन की सबसे नीची जगहें', qids: ['Q23883'], keywords: ['Dead Sea', 'below sea level', 'Danakil depression', 'salinity'] },
    { slug: 'tallest-waterfalls', en: 'The tallest waterfalls', hi: 'दुनिया के सबसे ऊँचे झरने', qids: ['Q139741947'], keywords: ['Angel Falls', 'Victoria Falls', 'Jog Falls', 'Niagara'] },
    { slug: 'planned-capital-cities', en: 'Capitals built from scratch', hi: 'बनाई गई राजधानियाँ', qids: ['Q2844'], keywords: ['Brasilia', 'Canberra', 'Chandigarh', 'Naypyidaw'] },
    { slug: 'borders-enclaves-and-exclaves', en: 'Odd borders, enclaves and exclaves', hi: 'अजीब सरहदें, एन्क्लेव और एक्सक्लेव', qids: ['Q1340068'], keywords: ['enclave', 'exclave', 'Cooch Behar enclaves', 'Baarle-Hertog'] },
    { slug: 'time-zones-and-the-date-line', en: 'Time zones and the date line', hi: 'टाइम ज़ोन और डेट लाइन', qids: ['Q187116'], keywords: ['time zone', 'International Date Line', 'IST', 'UTC offset'] },
    { slug: 'map-projections', en: 'Maps and why they lie', hi: 'नक्शे और उनका झूठ', qids: ['Q309372'], keywords: ['Mercator projection', 'map projection', 'Peters projection', 'cartography'] },
  ],
};
