import type { CategoryDef } from '../taxonomy-types.js';

export const worldHistory: CategoryDef = {
  id: 11,
  slug: 'world-history',
  en: 'World History',
  hi: 'विश्व इतिहास',
  emoji: '🏺',
  kidsSafe: false,
  subtopics: [
    { slug: 'mesopotamia-and-cuneiform', en: 'Mesopotamia and cuneiform', hi: 'मेसोपोटामिया और कीलाक्षर लिपि', qids: ['Q521482'], keywords: ['Sumer', 'cuneiform', 'Ur', 'Hammurabi'] },
    { slug: 'ancient-egypt-and-the-pyramids', en: 'Ancient Egypt and the pyramids', hi: 'प्राचीन मिस्र और पिरामिड', qids: ['Q11768'], keywords: ['Egypt', 'pyramids', 'hieroglyphs', 'Nile'] },
    { slug: 'greek-city-states', en: 'The Greek city-states', hi: 'यूनान के नगर-राज्य', qids: ['Q11772'], keywords: ['Athens', 'Sparta', 'democracy', 'Olympics'] },
    { slug: 'the-roman-republic-and-empire', en: 'The Roman republic and empire', hi: 'रोमन गणराज्य और साम्राज्य', qids: ['Q2277'], keywords: ['Rome', 'Senate', 'aqueduct', 'Caesar'] },
    { slug: 'han-dynasty-china', en: 'Han dynasty China', hi: 'चीन का हान वंश', qids: ['Q7209'], keywords: ['Han dynasty', 'paper', 'civil service exam', 'Chang’an'] },
    { slug: 'the-silk-road', en: 'The Silk Road', hi: 'सिल्क रोड', qids: ['Q36288'], keywords: ['Silk Road', 'caravan', 'Samarkand', 'trade routes'] },
    { slug: 'the-byzantine-empire', en: 'The Byzantine empire', hi: 'बीज़ान्टिन साम्राज्य', qids: ['Q12544'], keywords: ['Byzantium', 'Constantinople', 'Hagia Sophia', 'Justinian'] },
    { slug: 'baghdad-and-the-islamic-golden-age', en: 'Baghdad and the Islamic golden age', hi: 'बग़दाद और इस्लामी स्वर्ण युग', qids: ['Q33018'], keywords: ['House of Wisdom', 'Abbasid', 'al-Khwarizmi', 'astronomy'] },
    { slug: 'mali-empire-and-mansa-musa', en: 'The Mali empire and Mansa Musa', hi: 'माली साम्राज्य और मनसा मूसा', qids: ['Q184536'], keywords: ['Mali empire', 'Mansa Musa', 'Timbuktu', 'gold trade'] },
    { slug: 'great-zimbabwe-and-swahili-coast', en: 'Great Zimbabwe and the Swahili coast', hi: 'ग्रेट ज़िम्बाब्वे और स्वाहिली तट', qids: ['Q209217'], keywords: ['Great Zimbabwe', 'Kilwa', 'Swahili coast', 'Indian Ocean trade'] },
    { slug: 'the-mongol-empire', en: 'The Mongol empire', hi: 'मंगोल साम्राज्य', qids: ['Q12557'], keywords: ['Genghis Khan', 'Mongol empire', 'Yam postal system', 'Karakorum'] },
    { slug: 'medieval-europe-and-feudalism', en: 'Medieval Europe and feudalism', hi: 'मध्यकालीन यूरोप और सामंतवाद', qids: ['Q37739'], keywords: ['feudalism', 'manor', 'cathedral', 'guilds'] },
    { slug: 'tang-and-song-china', en: 'Tang and Song China', hi: 'तांग और सोंग चीन की खोजें', qids: ['Q9683'], keywords: ['Tang dynasty', 'Song dynasty', 'gunpowder', 'printing'] },
    { slug: 'the-maya-and-mesoamerica', en: 'The Maya and Mesoamerica', hi: 'माया सभ्यता और मेसोअमेरिका', qids: ['Q172613'], keywords: ['Maya', 'Tikal', 'Long Count calendar', 'Teotihuacan'] },
    { slug: 'the-inca-and-the-andes', en: 'The Inca and the Andes', hi: 'इंका साम्राज्य और एंडीज़', qids: ['Q676203'], keywords: ['Inca', 'Machu Picchu', 'quipu', 'road network'] },
    { slug: 'angkor-and-the-khmer-empire', en: 'Angkor and the Khmer empire', hi: 'अंकोर और ख़मेर साम्राज्य', qids: ['Q43473'], keywords: ['Angkor Wat', 'Khmer empire', 'baray', 'Jayavarman'] },
    { slug: 'srivijaya-and-majapahit', en: 'Srivijaya and Majapahit', hi: 'श्रीविजय और माजापहित', qids: ['Q234197'], keywords: ['Srivijaya', 'Majapahit', 'Java', 'maritime empire'] },
    { slug: 'the-ottoman-empire', en: 'The Ottoman empire', hi: 'ऑटोमन साम्राज्य', qids: ['Q12560'], keywords: ['Ottoman', 'Istanbul', 'Suleiman', 'janissary'] },
    { slug: 'safavid-persia', en: 'Safavid Persia', hi: 'सफ़ाविद ईरान', qids: ['Q18234383'], keywords: ['Safavid', 'Isfahan', 'Shah Abbas', 'Persian carpets'] },
    { slug: 'the-renaissance', en: 'The Renaissance', hi: 'यूरोप का पुनर्जागरण', qids: ['Q4692'], keywords: ['Renaissance', 'Florence', 'Leonardo', 'patronage'] },
    { slug: 'the-printing-press', en: 'The printing press', hi: 'छापेखाने की ईजाद', qids: ['Q114479012'], keywords: ['printing press', 'Gutenberg', 'movable type', 'books'] },
    { slug: 'age-of-sail-and-navigation', en: 'The age of sail and navigation', hi: 'समुद्री यात्राओं और नौवहन का दौर', qids: ['Q102066'], keywords: ['navigation', 'sextant', 'longitude', 'caravel'] },
    { slug: 'the-columbian-exchange', en: 'The Columbian exchange', hi: 'कोलंबियन एक्सचेंज: फ़सलों की अदला-बदली', qids: ['Q19902800'], keywords: ['Columbian exchange', 'potato', 'chilli', 'maize'] },
    { slug: 'the-scientific-revolution', en: 'The scientific revolution', hi: 'वैज्ञानिक क्रांति', qids: ['Q138039762'], keywords: ['Copernicus', 'Galileo', 'Newton', 'Royal Society'] },
    { slug: 'the-enlightenment', en: 'The Enlightenment', hi: 'प्रबोधन का दौर', qids: ['Q139684267'], keywords: ['Enlightenment', 'Voltaire', 'encyclopédie', 'reason'] },
    { slug: 'american-independence-1776', en: 'American independence, 1776', hi: 'अमेरिकी आज़ादी, 1776', qids: ['Q1464916'], keywords: ['1776', 'Declaration of Independence', 'thirteen colonies', 'constitution'] },
    { slug: 'the-french-revolution', en: 'The French Revolution', hi: 'फ़्रांसीसी क्रांति', qids: ['Q6534'], keywords: ['1789', 'Bastille', 'Estates-General', 'republic'] },
    { slug: 'the-industrial-revolution', en: 'The Industrial Revolution', hi: 'औद्योगिक क्रांति', qids: ['Q2269'], keywords: ['steam engine', 'factory', 'railways', 'Manchester'] },
    { slug: 'abolition-movements', en: 'The movements to abolish slavery', hi: 'ग़ुलामी ख़त्म करने के आंदोलन', qids: ['Q322732'], keywords: ['abolition', 'Wilberforce', 'Haitian revolution', '1833 Act'] },
    { slug: 'the-meiji-restoration', en: 'The Meiji Restoration', hi: 'जापान की मेइजी बहाली', qids: ['Q139703830'], keywords: ['Meiji', 'Japan modernisation', '1868', 'samurai'] },
    { slug: 'the-first-world-war', en: 'The First World War', hi: 'पहला विश्व युद्ध', qids: ['Q361'], keywords: ['1914', 'trenches', 'armistice', 'Treaty of Versailles'] },
    { slug: 'the-russian-revolution-1917', en: 'The Russian Revolution, 1917', hi: 'रूसी क्रांति, 1917', qids: ['Q83372'], keywords: ['1917', 'Bolshevik', 'Petrograd', 'Soviet Union'] },
    { slug: 'the-second-world-war', en: 'The Second World War', hi: 'दूसरा विश्व युद्ध', qids: ['Q362'], keywords: ['1939', 'Allies', 'Axis', 'D-Day'] },
    { slug: 'decolonisation', en: 'Decolonisation in Asia and Africa', hi: 'एशिया और अफ़्रीका में उपनिवेशवाद का अंत', qids: ['Q230533'], keywords: ['decolonisation', 'Ghana 1957', 'Bandung', 'independence'] },
    { slug: 'founding-of-the-united-nations', en: 'The founding of the United Nations', hi: 'संयुक्त राष्ट्र की स्थापना', qids: ['Q1065'], keywords: ['United Nations', '1945', 'San Francisco', 'Security Council'] },
    { slug: 'the-cold-war', en: 'The Cold War', hi: 'शीत युद्ध', qids: ['Q8683'], keywords: ['Cold War', 'Berlin Wall', 'space race', 'non-alignment'] },
  ],
};
