import type { CategoryDef } from '../taxonomy-types.js';

export const inventions: CategoryDef = {
  id: 25,
  slug: 'inventions-engineering',
  en: 'Inventions & Engineering',
  hi: 'आविष्कार और इंजीनियरिंग',
  emoji: '🔧',
  kidsSafe: true,
  subtopics: [
    { slug: 'gutenberg-printing-press', en: 'Gutenberg and the printing press', hi: 'गुटेनबर्ग और छापाख़ाना', qids: ['Q8958'], keywords: ['Johannes Gutenberg', 'movable type', 'Gutenberg Bible', '1450'] },
    { slug: 'harappan-town-planning', en: 'Harappan drainage and town planning', hi: 'हड़प्पा की नालियाँ और शहर की योजना', qids: ['Q42534'], keywords: ['Indus Valley Civilisation', 'Mohenjo-daro', 'Great Bath', 'covered drains'] },
    { slug: 'iron-pillar-of-delhi', en: 'The rustless iron pillar of Delhi', hi: 'दिल्ली का बिना ज़ंग वाला लौह स्तंभ', qids: ['Q55830125'], keywords: ['Iron Pillar Delhi', 'Qutub complex', 'corrosion resistance', 'misawite'] },
    { slug: 'stepwells-and-baolis', en: 'Stepwells and baolis', hi: 'बावड़ियाँ और सीढ़ीदार कुएँ', qids: ['Q7293002'], keywords: ['Rani ki Vav', 'Chand Baori', 'stepwell', 'water architecture'] },
    { slug: 'watt-steam-engine', en: 'Watt’s steam engine', hi: 'वॉट का भाप इंजन', qids: ['Q9041'], keywords: ['James Watt', 'separate condenser', 'Newcomen engine', 'horsepower'] },
    { slug: 'bessemer-process-steel', en: 'The Bessemer process and cheap steel', hi: 'बेसेमर प्रक्रिया और सस्ता स्टील', qids: ['Q2269'], keywords: ['Bessemer converter', 'steel making', '1856', 'Industrial Revolution'] },
    { slug: 'edison-light-bulb', en: 'Edison, the light bulb and the patent race', hi: 'एडिसन, बल्ब और पेटेंट की दौड़', qids: ['Q8743'], keywords: ['Thomas Edison', 'incandescent lamp', 'Menlo Park', 'Joseph Swan'] },
    { slug: 'war-of-currents', en: 'The war of the currents: AC vs DC', hi: 'करंट की जंग: एसी बनाम डीसी', qids: ['Q9036'], keywords: ['Nikola Tesla', 'George Westinghouse', 'alternating current', 'Niagara Falls power'] },
    { slug: 'telephone-invention', en: 'The invention of the telephone', hi: 'टेलीफ़ोन का आविष्कार', keywords: ['Alexander Graham Bell', 'Elisha Gray', 'Antonio Meucci', 'patent 174465'] },
    { slug: 'radio-and-jc-bose', en: 'Early radio and J.C. Bose’s millimetre waves', hi: 'शुरुआती रेडियो और जे.सी. बोस की मिलीमीटर तरंगें', qids: ['Q314267'], keywords: ['Jagadish Chandra Bose', 'Guglielmo Marconi', 'coherer', 'millimetre wave'] },
    { slug: 'wright-brothers-first-flight', en: 'The Wright brothers’ first flight', hi: 'राइट बंधुओं की पहली उड़ान', qids: ['Q46047837'], keywords: ['Wright brothers', 'Kitty Hawk 1903', 'wing warping', 'wind tunnel'] },
    { slug: 'haber-bosch-process', en: 'The Haber–Bosch process and fertiliser', hi: 'हैबर–बॉश प्रक्रिया और खाद', qids: ['Q213669'], keywords: ['Haber Bosch', 'ammonia synthesis', 'nitrogen fixation', 'fertiliser'] },
    { slug: 'penicillin-to-mass-production', en: 'From Fleming’s dish to mass-produced penicillin', hi: 'फ़्लेमिंग की प्लेट से बड़े पैमाने की पेनिसिलिन तक', qids: ['Q37064'], keywords: ['Alexander Fleming', 'Florey Chain', 'deep tank fermentation', 'antibiotic'] },
    { slug: 'transistor-bell-labs', en: 'The transistor at Bell Labs', hi: 'बेल लैब्स में ट्रांज़िस्टर', qids: ['Q5339'], keywords: ['Bardeen Brattain Shockley', 'Bell Labs 1947', 'point contact transistor', 'semiconductor'] },
    { slug: 'integrated-circuit-moores-law', en: 'The integrated circuit and Moore’s law', hi: 'इंटीग्रेटेड सर्किट और मूर का नियम', qids: ['Q182031'], keywords: ['Jack Kilby', 'Robert Noyce', 'Moore’s law', 'microchip'] },
    { slug: 'photolithography-and-chip-fabs', en: 'How chips are actually printed', hi: 'चिप असल में कैसे छपती है', qids: ['Q622938'], keywords: ['photolithography', 'EUV', 'wafer fab', 'cleanroom'] },
    { slug: 'arpanet-and-the-internet', en: 'ARPANET and the internet’s first packets', hi: 'अर्पानेट और इंटरनेट के पहले पैकेट', qids: ['Q75'], keywords: ['ARPANET', 'packet switching', 'TCP/IP', 'first message 1969'] },
    { slug: 'world-wide-web', en: 'The World Wide Web at CERN', hi: 'सर्न में वर्ल्ड वाइड वेब', qids: ['Q466', 'Q80'], keywords: ['Tim Berners-Lee', 'CERN', 'HTTP', 'first website'] },
    { slug: 'gps-satellites', en: 'How GPS works', hi: 'जीपीएस कैसे काम करता है', qids: ['Q227467'], keywords: ['GPS', 'atomic clock', 'relativity correction', 'NavIC'] },
    { slug: 'lasers', en: 'The laser', hi: 'लेज़र', qids: ['Q38867'], keywords: ['Theodore Maiman', 'ruby laser 1960', 'stimulated emission', 'solution looking for a problem'] },
    { slug: 'lithium-ion-battery', en: 'The lithium-ion battery', hi: 'लिथियम-आयन बैटरी', qids: ['Q2822895'], keywords: ['Goodenough Whittingham Yoshino', 'Nobel 2019', 'cathode', 'rechargeable battery'] },
    { slug: 'shipping-container', en: 'The shipping container that changed trade', hi: 'वो शिपिंग कंटेनर जिसने व्यापार बदल दिया', qids: ['Q113513778'], keywords: ['Malcom McLean', 'intermodal container', 'TEU', 'containerisation 1956'] },
    { slug: 'accidental-inventions', en: 'Inventions that happened by accident', hi: 'ग़लती से हुए आविष्कार', keywords: ['microwave oven Percy Spencer', 'Post-it note', 'Velcro', 'vulcanised rubber'] },
    { slug: 'zip-and-everyday-objects', en: 'The zip, the safety pin and other everyday engineering', hi: 'ज़िप, सेफ़्टी पिन और रोज़ की इंजीनियरिंग', qids: ['Q7132576'], keywords: ['zipper Gideon Sundback', 'safety pin Walter Hunt', 'ballpoint pen Biro', 'paperclip'] },
    { slug: 'eiffel-tower', en: 'The Eiffel Tower', hi: 'एफ़िल टावर', qids: ['Q243'], keywords: ['Gustave Eiffel', '1889 Exposition', 'wrought iron', 'wind loading'] },
    { slug: 'taj-mahal-construction', en: 'How the Taj Mahal was built', hi: 'ताजमहल कैसे बना', qids: ['Q9141'], keywords: ['Taj Mahal', 'Ustad Ahmad Lahauri', 'pietra dura', 'foundation wells'] },
    { slug: 'burj-khalifa', en: 'The Burj Khalifa and supertall towers', hi: 'बुर्ज ख़लीफ़ा और आसमान छूती इमारतें', qids: ['Q12495'], keywords: ['Burj Khalifa', 'buttressed core', 'tuned mass damper', 'concrete pumping record'] },
    { slug: 'suez-and-panama-canals', en: 'The Suez and Panama canals', hi: 'स्वेज़ और पनामा नहरें', qids: ['Q2388548'], keywords: ['Suez Canal 1869', 'Panama Canal locks', 'Ferdinand de Lesseps', 'Culebra Cut'] },
    { slug: 'indian-railways-engineering', en: 'The engineering of Indian Railways', hi: 'भारतीय रेल की इंजीनियरिंग', qids: ['Q819425'], keywords: ['Indian Railways', 'Nilgiri Mountain Railway', 'Pamban bridge', 'broad gauge'] },
    { slug: 'konkan-railway', en: 'The Konkan Railway', hi: 'कोंकण रेलवे', qids: ['Q1706472'], keywords: ['Konkan Railway', 'E. Sreedharan', 'tunnels and viaducts', '1998'] },
    { slug: 'chenab-rail-bridge', en: 'The Chenab rail bridge', hi: 'चिनाब रेल पुल', qids: ['Q4855911'], keywords: ['Chenab bridge', 'highest railway arch bridge', 'Jammu Kashmir', 'steel arch'] },
    { slug: 'delhi-metro', en: 'The Delhi Metro', hi: 'दिल्ली मेट्रो', qids: ['Q271195'], keywords: ['Delhi Metro', 'E. Sreedharan', 'tunnel boring machine', '2002 first line'] },
    { slug: 'bhakra-nangal-dam', en: 'Bhakra Nangal and India’s big dams', hi: 'भाखड़ा नंगल और भारत के बड़े बाँध', qids: ['Q83436'], keywords: ['Bhakra dam', 'gravity dam', 'Nangal', 'irrigation canal'] },
    { slug: 'isro-launch-vehicles', en: 'ISRO’s launch vehicles', hi: 'इसरो के रॉकेट', qids: ['Q1360911'], keywords: ['PSLV', 'GSLV Mk III', 'cryogenic engine', 'SLV-3'] },
    { slug: 'chandrayaan-and-mangalyaan', en: 'Chandrayaan and Mangalyaan', hi: 'चंद्रयान और मंगलयान', qids: ['Q2156739'], keywords: ['Chandrayaan-1 water on Moon', 'Mars Orbiter Mission', 'Chandrayaan-3 landing', 'low cost mission'] },
    { slug: 'suspension-bridges', en: 'How suspension bridges hold up', hi: 'सस्पेंशन पुल टिकते कैसे हैं', qids: ['Q44440'], keywords: ['Golden Gate Bridge', 'Akashi Kaikyo', 'Tacoma Narrows collapse', 'main cable'] },
  ],
};
