import type { CategoryDef } from '../taxonomy-types.js';

export const humanBody: CategoryDef = {
  id: 8,
  slug: 'human-body-health',
  en: 'Human Body & Health',
  hi: 'मानव शरीर और स्वास्थ्य',
  emoji: '🫀',
  kidsSafe: true,
  subtopics: [
    { slug: 'the-heart-and-circulation', en: 'The heart and circulation', hi: 'दिल और ख़ून का बहाव', qids: ['Q1072'], keywords: ['heart', 'circulation', 'arteries', 'heartbeat'] },
    { slug: 'blood-and-blood-groups', en: 'Blood and blood groups', hi: 'ख़ून और ब्लड ग्रुप', qids: ['Q7873'], keywords: ['blood', 'ABO', 'Rh factor', 'plasma'] },
    { slug: 'the-human-brain', en: 'The human brain', hi: 'इंसानी दिमाग़', qids: ['Q1073'], keywords: ['brain', 'cortex', 'neurons', 'hemispheres'] },
    { slug: 'the-nervous-system', en: 'The nervous system', hi: 'नर्वस सिस्टम और नसें', qids: ['Q87346972'], keywords: ['nervous system', 'spinal cord', 'reflex', 'nerve'] },
    { slug: 'lungs-and-breathing', en: 'The lungs and breathing', hi: 'फेफड़े और साँस लेना', qids: ['Q7886'], keywords: ['lungs', 'breathing', 'alveoli', 'oxygen'] },
    { slug: 'the-digestive-system', en: 'The digestive system', hi: 'पाचन तंत्र', qids: ['Q123373465'], keywords: ['digestion', 'stomach', 'intestine', 'enzymes'] },
    { slug: 'the-liver', en: 'The liver', hi: 'लिवर यानी जिगर', qids: ['Q54037726'], keywords: ['liver', 'bile', 'detoxification', 'regeneration'] },
    { slug: 'kidneys-and-filtration', en: 'The kidneys and filtration', hi: 'गुर्दे और ख़ून की सफ़ाई', qids: ['Q9377'], keywords: ['kidney', 'nephron', 'urine', 'dialysis'] },
    { slug: 'bones-and-the-skeleton', en: 'Bones and the skeleton', hi: 'हड्डियाँ और कंकाल', qids: ['Q186190'], keywords: ['skeleton', 'bone', 'marrow', 'joints'] },
    { slug: 'muscles-and-movement', en: 'Muscles and movement', hi: 'मांसपेशियाँ और हरकत', qids: ['Q7365'], keywords: ['muscle', 'tendon', 'movement', 'contraction'] },
    { slug: 'the-skin-and-hair', en: 'Skin, hair and nails', hi: 'त्वचा, बाल और नाख़ून', qids: ['Q187526'], keywords: ['skin', 'melanin', 'hair', 'keratin'] },
    { slug: 'the-eye-and-vision', en: 'The eye and vision', hi: 'आँख और नज़र', qids: ['Q58953360'], keywords: ['eye', 'retina', 'colour vision', 'lens'] },
    { slug: 'the-ear-and-hearing', en: 'The ear and hearing', hi: 'कान और सुनने की ताक़त', qids: ['Q13575058'], keywords: ['ear', 'cochlea', 'hearing', 'balance'] },
    { slug: 'smell-and-taste', en: 'Smell and taste', hi: 'सूँघना और स्वाद', qids: ['Q76582768'], keywords: ['smell', 'taste buds', 'olfactory', 'umami'] },
    { slug: 'sleep-and-dreams', en: 'Sleep and dreams', hi: 'नींद और सपने', qids: ['Q35831'], keywords: ['sleep', 'REM', 'circadian rhythm', 'dreams'] },
    { slug: 'the-immune-system', en: 'The immune system', hi: 'इम्यून सिस्टम यानी रोग प्रतिरोधक तंत्र', qids: ['Q134466452'], keywords: ['immune system', 'antibody', 'white blood cells', 'lymph'] },
    { slug: 'how-vaccines-work', en: 'How vaccines work', hi: 'वैक्सीन कैसे काम करती है', qids: ['Q7907941'], keywords: ['vaccine', 'immunity', 'Edward Jenner', 'antigen'] },
    { slug: 'polio-eradication-in-india', en: 'Polio eradication in India', hi: 'भारत में पोलियो का ख़ात्मा', qids: ['Q12195'], keywords: ['polio', 'Pulse Polio', 'oral vaccine', 'eradication'] },
    { slug: 'smallpox-eradication', en: 'The eradication of smallpox', hi: 'चेचक का दुनिया से सफ़ाया', qids: ['Q12214'], keywords: ['smallpox', 'WHO', 'variolation', 'eradication'] },
    { slug: 'tuberculosis-and-bcg', en: 'Tuberculosis and the BCG vaccine', hi: 'टीबी और बीसीजी का टीका', qids: ['Q12204'], keywords: ['tuberculosis', 'BCG', 'Koch', 'sanatorium'] },
    { slug: 'malaria-and-mosquitoes', en: 'Malaria and mosquitoes', hi: 'मलेरिया और मच्छर', qids: ['Q12156'], keywords: ['malaria', 'mosquito', 'Ronald Ross', 'quinine'] },
    { slug: 'ors-and-rehydration', en: 'ORS and oral rehydration therapy', hi: 'ओआरएस और पानी की कमी', qids: ['Q1381652'], keywords: ['ORS', 'oral rehydration', 'cholera', 'Dilip Mahalanabis'] },
    { slug: 'immunisation-programmes', en: 'India’s immunisation programmes', hi: 'देश के टीकाकरण कार्यक्रम', qids: ['Q83412024'], keywords: ['Universal Immunisation Programme', 'Mission Indradhanush', 'cold chain'] },
    { slug: 'nutrition-and-malnutrition', en: 'Nutrition and malnutrition', hi: 'पोषण और कुपोषण', qids: ['Q57771813'], keywords: ['nutrition', 'malnutrition', 'protein', 'ICDS'] },
    { slug: 'vitamins-and-deficiencies', en: 'Vitamins and deficiency diseases', hi: 'विटामिन और उनकी कमी से होने वाले रोग', qids: ['Q94290692'], keywords: ['vitamin', 'scurvy', 'rickets', 'iodine deficiency'] },
    { slug: 'hormones-and-glands', en: 'Hormones and the endocrine glands', hi: 'हार्मोन और एंडोक्राइन ग्रंथियाँ', qids: ['Q11364'], keywords: ['hormone', 'thyroid', 'adrenaline', 'pituitary'] },
    { slug: 'dna-and-the-double-helix', en: 'DNA and the double helix', hi: 'डीएनए और डबल हेलिक्स', qids: ['Q7430'], keywords: ['DNA', 'double helix', 'Rosalind Franklin', 'base pairs'] },
    { slug: 'genes-and-inheritance', en: 'Genes and inheritance', hi: 'जीन और आनुवंशिकता', qids: ['Q7187'], keywords: ['gene', 'Mendel', 'heredity', 'chromosome'] },
    { slug: 'the-human-genome-project', en: 'The Human Genome Project', hi: 'ह्यूमन जीनोम प्रोजेक्ट', qids: ['Q192446'], keywords: ['Human Genome Project', 'sequencing', 'genome', '2003'] },
    { slug: 'cells-and-cell-division', en: 'Cells and cell division', hi: 'कोशिकाएँ और उनका बँटवारा', qids: ['Q141099159'], keywords: ['cell', 'mitosis', 'stem cell', 'microscope'] },
    { slug: 'blood-donation-and-transfusion', en: 'Blood donation and transfusion', hi: 'रक्तदान और ख़ून चढ़ाना', qids: ['Q53467'], keywords: ['blood donation', 'transfusion', 'blood bank', 'Landsteiner'] },
    { slug: 'organ-transplants', en: 'Organ transplants', hi: 'अंग प्रत्यारोपण', qids: ['Q59040937'], keywords: ['transplant', 'kidney transplant', 'donor', 'Christiaan Barnard'] },
    { slug: 'antibiotics-and-resistance', en: 'Antibiotics and resistance', hi: 'एंटीबायोटिक और उनका बेअसर होना', qids: ['Q42382663'], keywords: ['antibiotic', 'penicillin', 'resistance', 'Fleming'] },
    { slug: 'the-gut-microbiome', en: 'The gut microbiome', hi: 'पेट के बैक्टीरिया', qids: ['Q35192914'], keywords: ['microbiome', 'gut bacteria', 'fermentation', 'probiotic'] },
    { slug: 'the-discovery-of-insulin', en: 'The discovery of insulin', hi: 'इंसुलिन की खोज', qids: ['Q138036755'], keywords: ['insulin', 'Banting', 'Best', 'pancreas'] },
    { slug: 'the-discovery-of-anaesthesia', en: 'The discovery of anaesthesia', hi: 'बेहोशी की दवा की खोज', qids: ['Q58728832'], keywords: ['anaesthesia', 'ether', 'chloroform', 'surgery history'] },
  ],
};
