import type { CategoryDef } from '../taxonomy-types.js';

export const finance: CategoryDef = {
  id: 1,
  slug: 'finance-markets',
  en: 'Finance & Markets',
  hi: 'वित्त और बाज़ार',
  emoji: '📈',
  kidsSafe: true,
  subtopics: [
    { slug: 'indian-stock-exchanges', en: 'Indian stock exchanges', hi: 'भारतीय शेयर बाज़ार', qids: ['Q796994'], keywords: ['BSE', 'NSE', 'Sensex', 'Nifty'] },
    { slug: 'reserve-bank-of-india', en: 'The Reserve Bank of India', hi: 'भारतीय रिज़र्व बैंक', qids: ['Q944085'], keywords: ['RBI', 'monetary policy', 'repo rate'] },
    { slug: 'indian-rupee', en: 'The Indian rupee', hi: 'भारतीय रुपया', qids: ['Q80524'], keywords: ['rupee', 'currency', 'devaluation'] },
    { slug: 'sebi-and-regulation', en: 'SEBI and market regulation', hi: 'सेबी और बाज़ार नियमन', qids: ['Q3771881'], keywords: ['SEBI', 'regulator', 'insider trading'] },
    { slug: 'famous-market-crashes', en: 'Famous market crashes', hi: 'मशहूर बाज़ार गिरावटें', qids: ['Q868261'], keywords: ['1929', '2008', 'Black Monday', 'dot-com'] },
    { slug: 'harshad-mehta-scam', en: 'The Harshad Mehta scam', hi: 'हर्षद मेहता घोटाला', keywords: ['1992', 'securities scam'] },
    { slug: 'central-banks', en: 'Central banks of the world', hi: 'दुनिया के केंद्रीय बैंक', qids: ['Q66344'], keywords: ['Federal Reserve', 'ECB', 'Bank of England'] },
    { slug: 'currencies-of-the-world', en: 'Currencies of the world', hi: 'दुनिया की मुद्राएँ', qids: ['Q8142'], keywords: ['currency', 'exchange rate'] },
    { slug: 'gdp-and-growth', en: 'GDP and economic growth', hi: 'जीडीपी और आर्थिक वृद्धि', qids: ['Q3516239'], keywords: ['GDP', 'growth rate', 'World Bank'] },
    { slug: 'inflation-and-prices', en: 'Inflation and prices', hi: 'महँगाई और कीमतें', qids: ['Q35865'], keywords: ['inflation', 'CPI', 'hyperinflation'] },
    { slug: 'gold-and-commodities', en: 'Gold and commodities', hi: 'सोना और जिंसें', qids: ['Q897'], keywords: ['gold', 'crude oil', 'commodity'] },
    { slug: 'indian-banks', en: 'Indian banks', hi: 'भारतीय बैंक', qids: ['Q739084', 'Q1959536'], keywords: ['SBI', 'HDFC', 'nationalisation'] },
    { slug: 'ipos-and-listings', en: 'IPOs and listings', hi: 'आईपीओ और लिस्टिंग', qids: ['Q478088'], keywords: ['IPO', 'listing', 'oversubscribed'] },
    { slug: 'famous-investors', en: 'Famous investors', hi: 'मशहूर निवेशक', keywords: ['Buffett', 'Rakesh Jhunjhunwala', 'Graham'] },
    { slug: 'cryptocurrency-history', en: 'The history of cryptocurrency', hi: 'क्रिप्टोकरेंसी का इतिहास', qids: ['Q131723'], keywords: ['Bitcoin', 'blockchain', 'Satoshi'] },
    { slug: 'insurance', en: 'Insurance', hi: 'बीमा', qids: ['Q43183'], keywords: ['LIC', 'insurance', 'actuarial'] },
    { slug: 'taxes-and-budgets', en: 'Taxes and government budgets', hi: 'कर और सरकारी बजट', qids: ['Q8161'], keywords: ['GST', 'income tax', 'union budget'] },
    { slug: 'demonetisation', en: 'Demonetisation', hi: 'विमुद्रीकरण', qids: ['Q3044465'], keywords: ['2016', 'notebandi', '500', '1000'] },
    { slug: 'upi-and-digital-payments', en: 'UPI and digital payments', hi: 'यूपीआई और डिजिटल भुगतान', keywords: ['UPI', 'NPCI', 'digital payment'] },
    { slug: 'mutual-funds', en: 'Mutual funds', hi: 'म्यूचुअल फंड', qids: ['Q791974'], keywords: ['SIP', 'AMC', 'index fund'] },
    { slug: 'bonds-and-debt', en: 'Bonds and government debt', hi: 'बॉन्ड और सरकारी कर्ज़', qids: ['Q105891421'], keywords: ['bond', 'yield', 'sovereign debt'] },
    { slug: 'stock-market-terms', en: 'Where market words come from', hi: 'बाज़ार के शब्द कहाँ से आए', qids: ['Q753878'], keywords: ['bull', 'bear', 'blue chip', 'etymology'] },
    { slug: 'worlds-largest-companies', en: 'The world’s largest companies', hi: 'दुनिया की सबसे बड़ी कंपनियाँ', qids: ['Q76615'], keywords: ['market cap', 'Fortune 500'] },
    { slug: 'trade-and-exports', en: 'Trade and exports', hi: 'व्यापार और निर्यात', qids: ['Q601401'], keywords: ['exports', 'trade deficit', 'tariff'] },
    { slug: 'famous-frauds', en: 'Famous financial frauds', hi: 'मशहूर वित्तीय धोखाधड़ी', qids: ['Q21707975'], keywords: ['Ponzi', 'Enron', 'Madoff', 'Satyam'] },
    { slug: 'money-history', en: 'The history of money', hi: 'पैसे का इतिहास', qids: ['Q1368'], keywords: ['barter', 'coinage', 'paper money'] },
    { slug: 'world-bank-imf', en: 'The World Bank and the IMF', hi: 'विश्व बैंक और आईएमएफ', qids: ['Q7164', 'Q7804'], keywords: ['World Bank', 'IMF', 'SDR'] },
    { slug: 'indian-economic-reforms', en: 'India’s 1991 reforms', hi: 'भारत के 1991 के सुधार', keywords: ['1991', 'liberalisation', 'Manmohan Singh'] },
    { slug: 'sovereign-wealth-funds', en: 'Sovereign wealth funds', hi: 'संप्रभु धन कोष', qids: ['Q1061648'], keywords: ['SWF', 'Norway', 'Temasek'] },
    { slug: 'unicorn-valuations', en: 'Unicorns and valuations', hi: 'यूनिकॉर्न और मूल्यांकन', qids: ['Q3549947'], keywords: ['unicorn', 'valuation', 'startup funding'] },
  ],
};
