import type { CategoryDef } from '../taxonomy-types.js';

export const otherSports: CategoryDef = {
  id: 27,
  slug: 'other-sports',
  en: 'Other Sports',
  hi: 'अन्य खेल',
  emoji: '🏅',
  kidsSafe: true,
  subtopics: [
    { slug: 'india-hockey-olympic-golds', en: 'India’s eight Olympic hockey golds', hi: 'भारत के आठ ओलंपिक हॉकी स्वर्ण', qids: ['Q931527', 'Q900171'], keywords: ['India field hockey team', '1928 Amsterdam', 'six in a row', 'Olympic gold'] },
    { slug: 'dhyan-chand', en: 'Dhyan Chand', hi: 'ध्यानचंद', qids: ['Q381138'], keywords: ['Dhyan Chand', 'The Wizard', '1936 Berlin final', 'National Sports Day'] },
    { slug: 'hockey-world-cup-1975', en: 'The 1975 Hockey World Cup', hi: '1975 का हॉकी विश्व कप', qids: ['Q1255965'], keywords: ['1975 Hockey World Cup', 'Kuala Lumpur', 'Ashok Kumar goal', 'India Pakistan final'] },
    { slug: 'field-hockey-rules-and-astroturf', en: 'Hockey rules and the astroturf shift', hi: 'हॉकी के नियम और एस्ट्रोटर्फ़ वाला बदलाव', qids: ['Q1455'], keywords: ['field hockey', 'astroturf', 'penalty corner', 'offside abolished'] },
    { slug: 'kabaddi', en: 'Kabaddi', hi: 'कबड्डी', qids: ['Q148636'], keywords: ['kabaddi', 'raider', 'cant', 'Asian Games kabaddi'] },
    { slug: 'pro-kabaddi-league', en: 'The Pro Kabaddi League', hi: 'प्रो कबड्डी लीग', qids: ['Q17069491'], keywords: ['Pro Kabaddi League', '2014', 'franchise league', 'Pardeep Narwal'] },
    { slug: 'chaturanga-and-chess-origins', en: 'Chaturanga and the origin of chess', hi: 'चतुरंग और शतरंज की शुरुआत', qids: ['Q206230', 'Q718'], keywords: ['chaturanga', 'chess origin India', 'shatranj', 'wheat and chessboard'] },
    { slug: 'viswanathan-anand', en: 'Viswanathan Anand', hi: 'विश्वनाथन आनंद', qids: ['Q45747'], keywords: ['Viswanathan Anand', 'first Indian grandmaster', 'world champion 2007', 'rapid chess'] },
    { slug: 'world-chess-championship', en: 'The World Chess Championship', hi: 'विश्व शतरंज चैंपियनशिप', qids: ['Q190042'], keywords: ['World Chess Championship', 'Fischer Spassky', 'Kasparov Karpov', 'FIDE'] },
    { slug: 'indian-chess-boom', en: 'India’s new grandmasters', hi: 'भारत के नए शतरंज ग्रैंडमास्टर', keywords: ['Gukesh Dommaraju', 'Praggnanandhaa', 'youngest world champion', 'Chess Olympiad'] },
    { slug: 'prakash-padukone-all-england', en: 'Prakash Padukone and the All England', hi: 'प्रकाश पादुकोण और ऑल इंग्लैंड', qids: ['Q1391342', 'Q1396170'], keywords: ['Prakash Padukone', 'All England Open 1980', 'badminton', 'Pullela Gopichand'] },
    { slug: 'indian-olympic-badminton-medals', en: 'India’s Olympic badminton medals', hi: 'बैडमिंटन में भारत के ओलंपिक पदक', keywords: ['P. V. Sindhu', 'Saina Nehwal', 'badminton Olympics', 'silver medal'] },
    { slug: 'thomas-cup', en: 'The Thomas Cup', hi: 'थॉमस कप', qids: ['Q1194788'], keywords: ['Thomas Cup', 'India 2022 win', 'men team badminton', 'Bangkok'] },
    { slug: 'kushti-and-akharas', en: 'Kushti and the akhara', hi: 'कुश्ती और अखाड़े', qids: ['Q2404776'], keywords: ['pehlwani', 'akhara', 'mud wrestling', 'Gama Pehlwan', 'dangal'] },
    { slug: 'khashaba-jadhav', en: 'K. D. Jadhav, India’s first individual medal', hi: 'खाशाबा जाधव — भारत का पहला व्यक्तिगत पदक', qids: ['Q3177430'], keywords: ['K. D. Jadhav', '1952 Helsinki bronze', 'wrestling', 'Goleshwar'] },
    { slug: 'olympic-wrestling', en: 'Wrestling at the Olympics', hi: 'ओलंपिक कुश्ती', qids: ['Q748627'], keywords: ['Olympic wrestling', 'freestyle', 'Greco-Roman', 'weight classes'] },
    { slug: 'neeraj-chopra', en: 'Neeraj Chopra and the javelin', hi: 'नीरज चोपड़ा और भाला फेंक', qids: ['Q24955843'], keywords: ['Neeraj Chopra', 'javelin throw', 'Tokyo 2020 gold', 'first athletics gold'] },
    { slug: 'milkha-singh', en: 'Milkha Singh', hi: 'मिल्खा सिंह', qids: ['Q269014'], keywords: ['Milkha Singh', '1960 Rome 400m', 'Flying Sikh', 'photo finish'] },
    { slug: 'pt-usha', en: 'P. T. Usha', hi: 'पी. टी. उषा', qids: ['Q3284484'], keywords: ['P. T. Usha', '1984 Los Angeles', 'fourth by 1/100th second', '400m hurdles'] },
    { slug: 'marathon-history', en: 'Where the marathon came from', hi: 'मैराथन कहाँ से आई', qids: ['Q40244'], keywords: ['marathon', 'Pheidippides', '42.195 km', '1908 London'] },
    { slug: 'sprinting-records', en: 'The 100 metres and speed records', hi: '100 मीटर और रफ़्तार के रिकॉर्ड', qids: ['Q164761'], keywords: ['100 metres', 'world record progression', 'Usain Bolt', 'reaction time'] },
    { slug: 'abhinav-bindra-and-shooting', en: 'Abhinav Bindra and Olympic shooting', hi: 'अभिनव बिंद्रा और ओलंपिक निशानेबाज़ी', qids: ['Q320610', 'Q206989'], keywords: ['Abhinav Bindra', '10m air rifle', 'Beijing 2008 gold', 'shooting sports'] },
    { slug: 'olympic-archery', en: 'Archery at the Olympics', hi: 'ओलंपिक तीरंदाज़ी', qids: ['Q654150'], keywords: ['Olympic archery', 'recurve bow', 'Deepika Kumari', '70 metres'] },
    { slug: 'indian-boxing-and-mary-kom', en: 'Mary Kom and Indian boxing', hi: 'मैरी कॉम और भारतीय मुक्केबाज़ी', qids: ['Q328951', 'Q578715'], keywords: ['Mary Kom', 'six world titles', 'Olympic boxing', 'Vijender Singh'] },
    { slug: 'modern-olympic-games', en: 'The modern Olympic Games', hi: 'आधुनिक ओलंपिक खेल', qids: ['Q159821'], keywords: ['Summer Olympics', 'Coubertin', '1896 Athens', 'Olympic rings'] },
    { slug: 'ancient-olympic-games', en: 'The ancient Olympic Games', hi: 'प्राचीन ओलंपिक खेल', qids: ['Q188468'], keywords: ['Ancient Olympic Games', 'Olympia', 'stadion race', 'olive wreath'] },
    { slug: 'paralympic-games', en: 'The Paralympic Games', hi: 'पैरालंपिक खेल', qids: ['Q73633'], keywords: ['Paralympic Games', 'Stoke Mandeville', 'classification', 'Murlikant Petkar'] },
    { slug: 'asian-games', en: 'The Asian Games', hi: 'एशियाई खेल', qids: ['Q483463'], keywords: ['Asian Games', '1951 New Delhi', 'Guru Dutt Sondhi', 'medal tally'] },
    { slug: 'commonwealth-games', en: 'The Commonwealth Games', hi: 'राष्ट्रमंडल खेल', qids: ['Q178340'], keywords: ['Commonwealth Games', '2010 Delhi', 'Friendly Games', 'lawn bowls'] },
    { slug: 'formula-one', en: 'Formula One', hi: 'फ़ॉर्मूला वन', qids: ['Q1968'], keywords: ['Formula One', 'constructors championship', 'pit stop', 'Monaco Grand Prix'] },
    { slug: 'indian-grand-prix', en: 'The Indian Grand Prix', hi: 'भारतीय ग्रां प्री', qids: ['Q8025'], keywords: ['Indian Grand Prix', 'Buddh International Circuit', '2011', 'Force India'] },
    { slug: 'tennis-grand-slams', en: 'The tennis Grand Slams', hi: 'टेनिस के ग्रैंड स्लैम', qids: ['Q102113'], keywords: ['Grand Slam tennis', 'Wimbledon', 'clay court', 'calendar slam'] },
    { slug: 'paes-and-bhupathi', en: 'Leander Paes and Mahesh Bhupathi', hi: 'लिएंडर पेस और महेश भूपति', qids: ['Q296282', 'Q312554'], keywords: ['Leander Paes', 'Mahesh Bhupathi', 'doubles Grand Slam', 'Atlanta 1996 bronze'] },
    { slug: 'table-tennis', en: 'Table tennis', hi: 'टेबल टेनिस', qids: ['Q3930'], keywords: ['table tennis', 'ping pong diplomacy', 'ITTF ball size', 'Sharath Kamal'] },
    { slug: 'nba-and-basketball', en: 'Basketball and the NBA', hi: 'बास्केटबॉल और एनबीए', qids: ['Q155223'], keywords: ['NBA', 'James Naismith', 'peach basket', 'three-point line'] },
    { slug: 'sumo', en: 'Sumo wrestling', hi: 'सूमो कुश्ती', qids: ['Q40561'], keywords: ['sumo', 'yokozuna', 'dohyo', 'basho tournament'] },
  ],
};
