import type { CategoryDef } from '../taxonomy-types.js';

export const cricket: CategoryDef = {
  id: 9,
  slug: 'cricket',
  en: 'Cricket',
  hi: 'क्रिकेट',
  emoji: '🏏',
  kidsSafe: true,
  subtopics: [
    { slug: 'indias-first-test-1932', en: 'India’s first Test, 1932', hi: 'भारत का पहला टेस्ट, 1932', qids: ['Q23393'], keywords: ['1932', 'Lord’s', 'CK Nayudu', 'first Test'] },
    { slug: 'bodyline-series-1932-33', en: 'The Bodyline series, 1932-33', hi: 'बॉडीलाइन सीरीज़, 1932-33', qids: ['Q111015489'], keywords: ['Bodyline', 'Jardine', 'leg theory', 'Larwood'] },
    { slug: 'the-ashes', en: 'The Ashes', hi: 'द ऐशेज़', qids: ['Q725151'], keywords: ['Ashes', 'England Australia', 'urn', '1882'] },
    { slug: 'world-cup-1983', en: 'The 1983 World Cup win', hi: '1983 का वर्ल्ड कप', qids: ['Q558189'], keywords: ['1983', 'Kapil Dev', 'Lord’s final', 'West Indies'] },
    { slug: 'world-cup-2011', en: 'The 2011 World Cup win', hi: '2011 का वर्ल्ड कप', keywords: ['2011', 'Wankhede', 'Dhoni six', 'Sri Lanka final'] },
    { slug: 't20-world-cup-2007', en: 'The 2007 T20 World Cup', hi: '2007 का टी20 वर्ल्ड कप', qids: ['Q979298'], keywords: ['2007', 'T20 World Cup', 'bowl-out', 'Johannesburg'] },
    { slug: 'ipl-origins-2008', en: 'The IPL and its 2008 origins', hi: 'आईपीएल की शुरुआत, 2008', keywords: ['IPL', '2008', 'franchise auction', 'Twenty20'] },
    { slug: 'ranji-trophy', en: 'The Ranji Trophy', hi: 'रणजी ट्रॉफ़ी', qids: ['Q3051958'], keywords: ['Ranji Trophy', 'domestic cricket', 'Bombay', 'first-class'] },
    { slug: 'duleep-and-irani-trophies', en: 'The Duleep and Irani trophies', hi: 'दलीप और ईरानी ट्रॉफ़ी', qids: ['Q3345067'], keywords: ['Duleep Trophy', 'Irani Cup', 'zonal cricket', 'Rest of India'] },
    { slug: 'the-gavaskar-era', en: 'The Gavaskar era', hi: 'गावस्कर का दौर', qids: ['Q558182'], keywords: ['Sunil Gavaskar', '10000 runs', 'opening batsman', '1970s'] },
    { slug: 'kapil-dev-and-allrounders', en: 'Kapil Dev and the all-rounder age', hi: 'कपिल देव और ऑलराउंडर का दौर', qids: ['Q558189'], keywords: ['Kapil Dev', 'all-rounder', 'Botham', 'Imran Khan'] },
    { slug: 'tendulkar-career', en: 'Sachin Tendulkar’s career', hi: 'सचिन तेंदुलकर का करियर', qids: ['Q9488'], keywords: ['Sachin Tendulkar', '100 centuries', 'debut 1989', 'records'] },
    { slug: 'dhoni-captaincy-era', en: 'The Dhoni captaincy years', hi: 'धोनी की कप्तानी का दौर', qids: ['Q470774'], keywords: ['MS Dhoni', 'captain', 'finisher', 'ICC trophies'] },
    { slug: 'the-kohli-era', en: 'The Kohli era', hi: 'विराट कोहली का दौर', qids: ['Q213854'], keywords: ['Virat Kohli', 'chase master', 'fitness', 'Test captaincy'] },
    { slug: 'indian-womens-cricket', en: 'Indian women’s cricket', hi: 'भारतीय महिला क्रिकेट', qids: ['Q3520476'], keywords: ['women’s cricket India', 'Mithali Raj', 'Jhulan Goswami', 'WPL'] },
    { slug: 'womens-world-cup-cricket', en: 'The Women’s Cricket World Cup', hi: 'महिला क्रिकेट वर्ल्ड कप', qids: ['Q1580299'], keywords: ['Women’s World Cup', '1973', '2017 final', 'Australia'] },
    { slug: 'world-series-cricket-1977', en: 'World Series Cricket, 1977', hi: 'वर्ल्ड सीरीज़ क्रिकेट, 1977', qids: ['Q1412816'], keywords: ['Kerry Packer', 'World Series Cricket', 'coloured clothing', 'floodlights'] },
    { slug: 'laws-of-cricket-and-mcc', en: 'The Laws of Cricket and the MCC', hi: 'क्रिकेट के नियम और एमसीसी', qids: ['Q2737036'], keywords: ['Laws of Cricket', 'MCC', '1788', 'spirit of cricket'] },
    { slug: 'bat-and-ball-making', en: 'How bats and balls are made', hi: 'बैट और गेंद कैसे बनते हैं', qids: ['Q104092599'], keywords: ['willow', 'Kashmir willow', 'cricket ball', 'seam'] },
    { slug: 'spin-bowling', en: 'The craft of spin bowling', hi: 'स्पिन गेंदबाज़ी की कला', qids: ['Q1684170'], keywords: ['spin bowling', 'doosra', 'googly', 'Bishan Bedi'] },
    { slug: 'fast-bowling-and-swing', en: 'Fast bowling and reverse swing', hi: 'तेज़ गेंदबाज़ी और रिवर्स स्विंग', qids: ['Q45085'], keywords: ['fast bowling', 'reverse swing', 'yorker', 'bouncer'] },
    { slug: 'wicketkeeping', en: 'Wicketkeeping', hi: 'विकेटकीपिंग', qids: ['Q50675789'], keywords: ['wicketkeeper', 'stumping', 'gloves', 'dismissals'] },
    { slug: 'lbw-and-umpiring', en: 'LBW and umpiring', hi: 'एलबीडब्ल्यू और अंपायरिंग', keywords: ['LBW', 'umpire', 'signals', 'no-ball'] },
    { slug: 'drs-and-cricket-technology', en: 'DRS and cricket technology', hi: 'डीआरएस और क्रिकेट की तकनीक', qids: ['Q1136821'], keywords: ['DRS', 'Hawk-Eye', 'Snicko', 'third umpire'] },
    { slug: 'indian-cricket-grounds', en: 'The great grounds of India', hi: 'भारत के मशहूर क्रिकेट मैदान', qids: ['Q2035004'], keywords: ['Eden Gardens', 'Wankhede', 'Chepauk', 'Narendra Modi Stadium'] },
    { slug: 'lords-and-english-grounds', en: 'Lord’s and the English grounds', hi: 'लॉर्ड्स और इंग्लैंड के मैदान', qids: ['Q23393'], keywords: ['Lord’s', 'Oval', 'Headingley', 'pavilion'] },
    { slug: 'bradman-and-the-average', en: 'Bradman and the 99.94 average', hi: 'ब्रैडमैन और 99.94 का औसत', keywords: ['Don Bradman', '99.94', 'batting average', 'Invincibles'] },
    { slug: 'west-indies-golden-era', en: 'The West Indies golden era', hi: 'वेस्ट इंडीज़ का सुनहरा दौर', qids: ['Q669037'], keywords: ['West Indies', 'Clive Lloyd', 'pace quartet', 'Viv Richards'] },
    { slug: 'australia-dominance-1999-2007', en: 'Australia’s dominance, 1999-2007', hi: 'ऑस्ट्रेलिया का दबदबा, 1999-2007', qids: ['Q408'], keywords: ['Australia', 'Steve Waugh', 'Ponting', 'three World Cups'] },
    { slug: 'pakistan-cricket-history', en: 'Pakistan cricket history', hi: 'पाकिस्तान क्रिकेट का इतिहास', qids: ['Q5185025'], keywords: ['Pakistan cricket', 'Imran Khan', '1992 World Cup', 'reverse swing'] },
    { slug: 'sri-lanka-1996', en: 'Sri Lanka and the 1996 World Cup', hi: 'श्रीलंका और 1996 का वर्ल्ड कप', qids: ['Q854'], keywords: ['Sri Lanka', '1996', 'Jayasuriya', 'pinch hitting'] },
    { slug: 'day-night-pink-ball-tests', en: 'Day-night Tests and the pink ball', hi: 'डे-नाइट टेस्ट और गुलाबी गेंद', qids: ['Q79999311'], keywords: ['pink ball', 'day-night Test', 'Adelaide', '2015'] },
    { slug: 'cricket-records-and-stats', en: 'Cricket records and statistics', hi: 'क्रिकेट के रिकॉर्ड और आँकड़े', qids: ['Q1091565'], keywords: ['records', 'Wisden', 'statistics', 'highest score'] },
    { slug: 'famous-finishes', en: 'Tied matches and famous finishes', hi: 'टाई मैच और यादगार फ़िनिश', qids: ['Q7800971'], keywords: ['tied Test', 'super over', '2019 final', 'last ball'] },
    { slug: 'cricket-commentary', en: 'Cricket commentary and broadcasting', hi: 'क्रिकेट कमेंट्री और प्रसारण', qids: ['Q1749541'], keywords: ['commentary', 'radio', 'Test Match Special', 'broadcast rights'] },
    { slug: 'cricket-at-the-olympics', en: 'Cricket at the Olympics', hi: 'ओलंपिक में क्रिकेट', qids: ['Q39052122'], keywords: ['Olympics 1900', 'Los Angeles 2028', 'Commonwealth Games'] },
  ],
};
