import type { CategoryDef } from '../taxonomy-types.js';

export const psychology: CategoryDef = {
  id: 23,
  slug: 'psychology-brain',
  en: 'Psychology & The Brain',
  hi: 'मनोविज्ञान और दिमाग़',
  emoji: '🧠',
  kidsSafe: true,
  subtopics: [
    { slug: 'pavlov-classical-conditioning', en: 'Pavlov’s dogs and classical conditioning', hi: 'पावलोव के कुत्ते और क्लासिकल कंडिशनिंग', qids: ['Q667920'], keywords: ['Pavlov', 'classical conditioning', 'salivation', 'conditioned reflex'] },
    { slug: 'skinner-operant-conditioning', en: 'Skinner’s box and operant conditioning', hi: 'स्किनर का बॉक्स और ऑपरेंट कंडिशनिंग', qids: ['Q213195'], keywords: ['B.F. Skinner', 'operant conditioning', 'reinforcement schedule', 'Skinner box'] },
    { slug: 'milgram-obedience-experiment', en: 'The Milgram obedience experiment', hi: 'मिलग्राम का आज्ञापालन प्रयोग', qids: ['Q208236'], keywords: ['Stanley Milgram', 'obedience to authority', 'Yale', '1961'] },
    { slug: 'asch-conformity-experiments', en: 'The Asch conformity experiments', hi: 'ऐश के कन्फ़ॉर्मिटी प्रयोग', qids: ['Q778684'], keywords: ['Solomon Asch', 'conformity', 'line judgement', 'group pressure'] },
    { slug: 'stanford-prison-experiment', en: 'The Stanford prison experiment and its critics', hi: 'स्टैनफ़ोर्ड जेल प्रयोग और उस पर उठे सवाल', qids: ['Q296042'], keywords: ['Philip Zimbardo', '1971', 'Stanford prison experiment', 'replication criticism'] },
    { slug: 'bystander-effect', en: 'The bystander effect', hi: 'बाईस्टैंडर इफ़ेक्ट: भीड़ में कोई मदद क्यों नहीं करता', qids: ['Q35174047'], keywords: ['bystander effect', 'diffusion of responsibility', 'Darley Latane'] },
    { slug: 'cognitive-dissonance', en: 'Cognitive dissonance', hi: 'कॉग्निटिव डिसोनेंस यानी सोच का टकराव', qids: ['Q110555571'], keywords: ['Leon Festinger', 'cognitive dissonance', 'When Prophecy Fails'] },
    { slug: 'dunning-kruger-effect', en: 'The Dunning–Kruger effect', hi: 'डनिंग–क्रूगर इफ़ेक्ट', qids: ['Q61248615'], keywords: ['Dunning Kruger', 'overconfidence', 'metacognition', '1999 study'] },
    { slug: 'confirmation-bias', en: 'Confirmation bias', hi: 'कन्फ़र्मेशन बायस: वही दिखता है जो हम मानते हैं', qids: ['Q431498'], keywords: ['confirmation bias', 'Wason selection task', 'motivated reasoning'] },
    { slug: 'anchoring-effect', en: 'The anchoring effect', hi: 'ऐंकरिंग इफ़ेक्ट: पहला नंबर दिमाग़ में अटक जाता है', qids: ['Q557151'], keywords: ['anchoring', 'Tversky Kahneman', 'numerical estimate', 'negotiation'] },
    { slug: 'prospect-theory-loss-aversion', en: 'Prospect theory and loss aversion', hi: 'प्रॉस्पेक्ट थ्योरी और नुक़सान से डर', qids: ['Q233950'], keywords: ['Daniel Kahneman', 'Amos Tversky', 'prospect theory', 'loss aversion', 'Nobel 2002'] },
    { slug: 'availability-heuristic', en: 'The availability heuristic', hi: 'अवेलेबिलिटी ह्यूरिस्टिक', qids: ['Q1462985'], keywords: ['availability heuristic', 'risk perception', 'plane crash vs car crash'] },
    { slug: 'framing-effect', en: 'The framing effect', hi: 'फ़्रेमिंग इफ़ेक्ट: बात कहने का तरीक़ा', qids: ['Q1440683'], keywords: ['framing effect', 'Asian disease problem', 'decision making'] },
    { slug: 'placebo-and-nocebo', en: 'The placebo and nocebo effects', hi: 'प्लेसीबो और नोसीबो असर', qids: ['Q89548369'], keywords: ['placebo effect', 'nocebo', 'sham treatment', 'clinical trial history'] },
    { slug: 'stroop-effect', en: 'The Stroop effect', hi: 'स्ट्रूप इफ़ेक्ट', qids: ['Q384176'], keywords: ['Stroop test', 'colour word interference', '1935', 'reaction time'] },
    { slug: 'mcgurk-effect', en: 'The McGurk effect', hi: 'मैकगर्क इफ़ेक्ट: कान वही सुनते हैं जो आँख देखती है', qids: ['Q34424758'], keywords: ['McGurk effect', 'audiovisual illusion', 'speech perception'] },
    { slug: 'cocktail-party-effect', en: 'The cocktail party effect', hi: 'कॉकटेल पार्टी इफ़ेक्ट: शोर में अपना नाम सुन लेना', qids: ['Q50641906'], keywords: ['cocktail party effect', 'selective attention', 'Colin Cherry', 'dichotic listening'] },
    { slug: 'inattentional-blindness', en: 'Inattentional blindness and the invisible gorilla', hi: 'ध्यान की अंधता और वो अदृश्य गोरिल्ला', qids: ['Q287827'], keywords: ['invisible gorilla', 'Simons Chabris', 'inattentional blindness', 'change blindness'] },
    { slug: 'ebbinghaus-forgetting-curve', en: 'Ebbinghaus and the forgetting curve', hi: 'एबिंगहॉस और भूलने का कर्व', qids: ['Q57332'], keywords: ['Hermann Ebbinghaus', 'forgetting curve', 'spacing effect', 'nonsense syllables'] },
    { slug: 'loftus-false-memory', en: 'Elizabeth Loftus and false memories', hi: 'एलिज़ाबेथ लॉफ़्टस और झूठी यादें', qids: ['Q262154'], keywords: ['Elizabeth Loftus', 'misinformation effect', 'eyewitness testimony', 'lost in the mall'] },
    { slug: 'flashbulb-memories', en: 'Flashbulb memories', hi: 'फ़्लैशबल्ब यादें: बड़ी घटना का पल याद रह जाना', qids: ['Q55894042'], keywords: ['flashbulb memory', 'Brown Kulik', 'Challenger study', 'memory accuracy'] },
    { slug: 'patient-hm-and-hippocampus', en: 'Patient H.M. and the hippocampus', hi: 'मरीज़ एच.एम. और हिप्पोकैम्पस', qids: ['Q18627'], keywords: ['Henry Molaison', 'anterograde amnesia', 'Brenda Milner', 'hippocampus'] },
    { slug: 'phineas-gage', en: 'The case of Phineas Gage', hi: 'फ़िनियस गेज का मशहूर हादसा', qids: ['Q316742'], keywords: ['Phineas Gage', '1848', 'frontal lobe', 'tamping iron'] },
    { slug: 'split-brain-experiments', en: 'Sperry’s split-brain experiments', hi: 'स्पेरी के स्प्लिट-ब्रेन प्रयोग', qids: ['Q232305'], keywords: ['Roger Sperry', 'corpus callosum', 'split brain', 'Nobel 1981'] },
    { slug: 'phantom-limbs-ramachandran', en: 'Phantom limbs and V.S. Ramachandran’s mirror box', hi: 'फैंटम लिम्ब और वी.एस. रामचंद्रन का मिरर बॉक्स', qids: ['Q48616781'], keywords: ['V.S. Ramachandran', 'phantom limb', 'mirror box', 'body map'] },
    { slug: 'london-taxi-drivers-brains', en: 'London taxi drivers and brain plasticity', hi: 'लंदन के टैक्सी ड्राइवर और दिमाग़ की लचक', qids: ['Q1073'], keywords: ['taxi driver hippocampus', 'Eleanor Maguire', 'neuroplasticity', 'The Knowledge'] },
    { slug: 'mirror-neurons', en: 'Mirror neurons', hi: 'मिरर न्यूरॉन', qids: ['Q22337343'], keywords: ['mirror neurons', 'Rizzolatti', 'macaque premotor cortex', 'imitation'] },
    { slug: 'rem-sleep-and-dreaming', en: 'REM sleep and dreaming', hi: 'REM नींद और सपने', qids: ['Q211402'], keywords: ['REM sleep', 'Aserinsky Kleitman', 'sleep cycle', 'dream research'] },
    { slug: 'circadian-rhythm-discovery', en: 'How the body clock was discovered', hi: 'शरीर की घड़ी कैसे खोजी गई', qids: ['Q208353'], keywords: ['circadian rhythm', 'Michel Siffre cave', 'suprachiasmatic nucleus', 'Nobel 2017'] },
    { slug: 'freud-and-psychoanalysis', en: 'Freud and the birth of psychoanalysis', hi: 'फ़्रॉयड और मनोविश्लेषण की शुरुआत', qids: ['Q9215'], keywords: ['Sigmund Freud', 'psychoanalysis', 'The Interpretation of Dreams', 'unconscious'] },
    { slug: 'jung-and-archetypes', en: 'Jung, archetypes and the word association test', hi: 'युंग, आर्किटाइप और शब्द-संगति परीक्षण', qids: ['Q41532'], keywords: ['Carl Jung', 'archetype', 'collective unconscious', 'word association'] },
    { slug: 'piaget-stages-of-development', en: 'Piaget’s stages of child development', hi: 'पियाजे के बाल-विकास के चरण', qids: ['Q123190'], keywords: ['Jean Piaget', 'object permanence', 'conservation task', 'cognitive development'] },
    { slug: 'maslow-hierarchy-of-needs', en: 'Maslow’s hierarchy of needs', hi: 'मैस्लो का ज़रूरतों का पिरामिड', qids: ['Q179515'], keywords: ['Abraham Maslow', 'hierarchy of needs', 'self-actualisation', '1943 paper'] },
    { slug: 'big-five-personality-traits', en: 'The Big Five personality traits', hi: 'व्यक्तित्व के पाँच बड़े लक्षण', qids: ['Q378132'], keywords: ['Big Five', 'OCEAN model', 'personality psychology', 'lexical hypothesis'] },
    { slug: 'marshmallow-test', en: 'The marshmallow test and delayed gratification', hi: 'मार्शमैलो टेस्ट और सब्र की परीक्षा', qids: ['Q215978'], keywords: ['Walter Mischel', 'marshmallow test', 'delayed gratification', 'replication'] },
    { slug: 'wundt-first-psychology-lab', en: 'Wundt’s Leipzig lab and the birth of psychology', hi: 'वुंट की लाइपज़िग लैब और मनोविज्ञान की शुरुआत', qids: ['Q9418'], keywords: ['Wilhelm Wundt', '1879 Leipzig', 'introspection', 'experimental psychology'] },
    { slug: 'pareidolia', en: 'Pareidolia: seeing faces in things', hi: 'पैरिडोलिया: चीज़ों में चेहरे दिखना', qids: ['Q135022808'], keywords: ['pareidolia', 'face perception', 'fusiform face area', 'Face on Mars'] },
    { slug: 'optical-illusions', en: 'Classic optical illusions and why they work', hi: 'मशहूर ऑप्टिकल इल्यूज़न और उनके पीछे की वजह', qids: ['Q926299'], keywords: ['Müller-Lyer illusion', 'Ponzo illusion', 'checker shadow', 'visual perception'] },
  ],
};
