import type { CategoryDef } from '../taxonomy-types.js';

export const food: CategoryDef = {
  id: 19,
  slug: 'food-cooking',
  en: 'Food & Cooking',
  hi: 'खाना और पकवान',
  emoji: '🍲',
  kidsSafe: true,
  subtopics: [
    { slug: 'biryani-and-its-versions', en: 'Biryani and its regional versions', hi: 'बिरयानी और उसके अलग-अलग अंदाज़', qids: ['Q271555'], keywords: ['biryani', 'Hyderabadi dum biryani', 'Lucknawi', 'Thalassery'] },
    { slug: 'the-story-of-samosa', en: 'Where the samosa came from', hi: 'समोसा कहाँ से आया', qids: ['Q491517'], keywords: ['samosa', 'sambusak', 'Persian origin', 'fried pastry'] },
    { slug: 'chai-and-indian-tea-gardens', en: 'Chai and India’s tea gardens', hi: 'चाय और भारत के चाय बाग़ान', qids: ['Q6097'], keywords: ['tea', 'Assam tea', 'Darjeeling', 'cutting chai'] },
    { slug: 'filter-coffee-and-indian-coffee', en: 'Filter coffee and Indian coffee', hi: 'फ़िल्टर कॉफ़ी और भारतीय कॉफ़ी', qids: ['Q8486'], keywords: ['coffee', 'filter coffee', 'Coorg plantation', 'Baba Budan'] },
    { slug: 'dosa-idli-and-fermented-batter', en: 'Dosa, idli and fermented batter', hi: 'डोसा, इडली और खमीर वाला घोल', keywords: ['dosa', 'idli', 'fermented batter', 'urad dal'] },
    { slug: 'mumbai-street-food', en: 'The street food of Mumbai', hi: 'मुंबई का स्ट्रीट फ़ूड', qids: ['Q7623006'], keywords: ['vada pav', 'pav bhaji', 'bhel puri', 'Mumbai street food'] },
    { slug: 'chaat-of-north-india', en: 'The chaat of north India', hi: 'उत्तर भारत की चाट', keywords: ['chaat', 'golgappa', 'aloo tikki', 'dahi puri'] },
    { slug: 'bengali-sweets', en: 'Rosogolla, sandesh and Bengali sweets', hi: 'रसगुल्ला, संदेश और बंगाली मिठाइयाँ', qids: ['Q3349224'], keywords: ['rosogolla', 'sandesh', 'chhena', 'Nabin Chandra Das'] },
    { slug: 'festival-mithai', en: 'Mithai and festival sweets', hi: 'मिठाइयाँ और त्योहारी पकवान', qids: ['Q3272159'], keywords: ['mithai', 'laddu', 'jalebi', 'barfi'] },
    { slug: 'rajasthani-food', en: 'Rajasthani food and dal baati', hi: 'राजस्थानी खाना और दाल बाटी', keywords: ['dal baati churma', 'laal maas', 'ker sangri', 'Rajasthani cuisine'] },
    { slug: 'kashmiri-wazwan', en: 'The Kashmiri wazwan', hi: 'कश्मीरी वाज़वान', qids: ['Q4102393'], keywords: ['wazwan', 'rogan josh', 'gushtaba', 'waza cooks'] },
    { slug: 'goan-food-and-portuguese-influence', en: 'Goan food and the Portuguese influence', hi: 'गोवा का खाना और पुर्तगाली असर', qids: ['Q1339633'], keywords: ['vindaloo', 'Goan cuisine', 'kokum', 'bebinca'] },
    { slug: 'awadhi-and-hyderabadi-dum', en: 'Awadhi and Hyderabadi dum cooking', hi: 'अवधी और हैदराबादी दम पुख़्त', qids: ['Q5313587'], keywords: ['dum pukht', 'Awadhi cuisine', 'Hyderabadi haleem', 'nihari'] },
    { slug: 'northeast-indian-food', en: 'The food of northeast India', hi: 'पूर्वोत्तर भारत का खाना', qids: ['Q2157176'], keywords: ['bamboo shoot', 'axone', 'Naga king chilli', 'smoked pork'] },
    { slug: 'kerala-coconut-and-seafood', en: 'Kerala coconut and seafood cooking', hi: 'केरल का नारियल और समुद्री खाना', qids: ['Q841779'], keywords: ['Kerala cuisine', 'coconut milk', 'meen curry', 'appam'] },
    { slug: 'gujarati-thali', en: 'The Gujarati thali', hi: 'गुजराती थाली', qids: ['Q24906353'], keywords: ['Gujarati thali', 'dhokla', 'undhiyu', 'farsan'] },
    { slug: 'indian-spices-and-the-spice-trade', en: 'Indian spices and the spice trade', hi: 'भारतीय मसाले और मसालों का व्यापार', qids: ['Q135453380'], keywords: ['spice trade', 'garam masala', 'cardamom', 'Malabar coast'] },
    { slug: 'turmeric', en: 'Turmeric', hi: 'हल्दी', qids: ['Q20730193'], keywords: ['turmeric', 'curcumin', 'Erode', 'haldi'] },
    { slug: 'chillies-came-to-india', en: 'How chillies reached India', hi: 'मिर्च भारत कैसे पहुँची', qids: ['Q135428003'], keywords: ['chilli pepper', 'capsaicin', 'Guntur', 'Scoville scale'] },
    { slug: 'black-pepper-of-malabar', en: 'The black pepper of Malabar', hi: 'मालाबार की काली मिर्च', qids: ['Q43084'], keywords: ['black pepper', 'Malabar', 'piperine', 'pepper trade'] },
    { slug: 'rice-varieties-and-basmati', en: 'Rice varieties and basmati', hi: 'चावल की किस्में और बासमती', qids: ['Q5090'], keywords: ['rice', 'basmati', 'paddy cultivation', 'GI tag'] },
    { slug: 'rotis-and-flatbreads', en: 'Roti, naan and Indian flatbreads', hi: 'रोटी, नान और भारतीय रोटियाँ', qids: ['Q59707'], keywords: ['roti', 'naan', 'paratha', 'wheat flour'] },
    { slug: 'lentils-and-dal', en: 'Lentils and dal', hi: 'दालें', qids: ['Q15622268'], keywords: ['dal', 'toor dal', 'pulses', 'protein'] },
    { slug: 'ghee-and-indian-dairy', en: 'Ghee, butter and Indian dairy', hi: 'घी, मक्खन और भारतीय डेयरी', qids: ['Q106928594'], keywords: ['ghee', 'butter', 'Amul', 'white revolution'] },
    { slug: 'paneer-and-cheeses', en: 'Paneer and the cheeses of the world', hi: 'पनीर और दुनिया की चीज़', qids: ['Q1139546'], keywords: ['paneer', 'cheese making', 'rennet', 'Parmesan'] },
    { slug: 'pickles-and-preserving', en: 'Pickles and preserving food', hi: 'अचार और खाना सहेजने के तरीक़े', qids: ['Q1503967'], keywords: ['achar', 'pickling', 'brine', 'preservation'] },
    { slug: 'fermentation-in-food', en: 'Fermentation in food', hi: 'खाने में फ़र्मेंटेशन', qids: ['Q41760'], keywords: ['fermentation', 'curd', 'kimchi', 'lactic acid bacteria'] },
    { slug: 'mangoes-of-india', en: 'The mangoes of India', hi: 'भारत के आम', qids: ['Q169'], keywords: ['mango', 'Alphonso', 'Langra', 'Dussehri'] },
    { slug: 'pizza-and-italian-food', en: 'Pizza and Italian food', hi: 'पिज़्ज़ा और इतालवी खाना', qids: ['Q177'], keywords: ['pizza', 'Margherita', 'pasta', 'Naples'] },
    { slug: 'chocolate-bean-to-bar', en: 'Chocolate, from bean to bar', hi: 'चॉकलेट: बीन से बार तक', qids: ['Q195'], keywords: ['chocolate', 'cacao bean', 'conching', 'Idukki cocoa'] },
    { slug: 'sushi-and-japanese-food', en: 'Sushi and Japanese food', hi: 'सुशी और जापानी खाना', qids: ['Q12378304'], keywords: ['sushi', 'wasabi', 'umami', 'dashi'] },
    { slug: 'bread-baking-and-sourdough', en: 'Bread baking and sourdough', hi: 'ब्रेड बेकिंग और सॉरडो', qids: ['Q96694045'], keywords: ['bread', 'sourdough starter', 'yeast', 'gluten'] },
    { slug: 'noodles-and-their-history', en: 'Noodles and where they began', hi: 'नूडल्स कहाँ से शुरू हुए', qids: ['Q113012299'], keywords: ['noodles', 'ramen', 'Lajia noodles', 'instant noodles'] },
    { slug: 'indian-chinese-food', en: 'Indian Chinese food', hi: 'भारत का चाइनीज़ खाना', qids: ['Q8963561'], keywords: ['Indian Chinese', 'gobi manchurian', 'Tangra Kolkata', 'hakka noodles'] },
    { slug: 'kebabs-and-their-history', en: 'Kebabs and their history', hi: 'कबाब और उनका इतिहास', qids: ['Q55632802'], keywords: ['kebab', 'galouti kebab', 'seekh kebab', 'Lucknow'] },
    { slug: 'tandoor-cooking', en: 'Cooking in a tandoor', hi: 'तंदूर में पकता खाना', qids: ['Q379831'], keywords: ['tandoor', 'clay oven', 'tandoori chicken', 'Moti Mahal'] },
  ],
};
