import type { CategoryDef } from '../taxonomy-types.js';

export const language: CategoryDef = {
  id: 22,
  slug: 'language-words',
  en: 'Language & Words',
  hi: 'भाषा और शब्द',
  emoji: '🔤',
  kidsSafe: true,
  subtopics: [
    { slug: 'devanagari-script', en: 'The Devanagari script', hi: 'देवनागरी लिपि', qids: ['Q38592'], keywords: ['Devanagari', 'shirorekha', 'abugida', 'matra'] },
    { slug: 'tamil-language-and-script', en: 'Tamil, language and script', hi: 'तमिल भाषा और लिपि', qids: ['Q5885', 'Q26803'], keywords: ['Tamil language', 'Tamil script', 'Sangam literature', 'classical language'] },
    { slug: 'bengali-assamese-script', en: 'The Bengali-Assamese script', hi: 'बांग्ला-असमिया लिपि', qids: ['Q12438487'], keywords: ['Bengali script', 'Assamese', 'Eastern Nagari', 'conjunct letters'] },
    { slug: 'urdu-and-nastaliq', en: 'Urdu and the nastaliq hand', hi: 'उर्दू और नस्तालीक़', qids: ['Q1617', 'Q1133121'], keywords: ['Urdu', 'Nastaliq', 'calligraphy', 'Perso-Arabic script'] },
    { slug: 'sanskrit-and-panini', en: 'Sanskrit and Panini’s grammar', hi: 'संस्कृत और पाणिनि का व्याकरण', qids: ['Q11059', 'Q189725'], keywords: ['Sanskrit', 'Panini', 'Ashtadhyayi', 'sutra grammar'] },
    { slug: 'hindi-urdu-hindustani', en: 'Hindi, Urdu and Hindustani', hi: 'हिंदी, उर्दू और हिंदुस्तानी', qids: ['Q11051'], keywords: ['Hindustani language', 'register', 'Khari Boli', 'Hindi Urdu controversy'] },
    { slug: 'eighth-schedule-languages', en: 'The Eighth Schedule languages', hi: 'आठवीं अनुसूची की भाषाएँ', qids: ['Q12414903'], keywords: ['Eighth Schedule', 'scheduled languages', 'Constitution of India', '22 languages'] },
    { slug: 'english-words-from-india', en: 'English words that came from India', hi: 'अंग्रेज़ी में गए भारतीय शब्द', qids: ['Q191086'], keywords: ['loot', 'jungle', 'shampoo', 'Hobson-Jobson', 'bungalow'] },
    { slug: 'brahmi-script', en: 'The Brahmi script', hi: 'ब्राह्मी लिपि', qids: ['Q185083'], keywords: ['Brahmi script', 'James Prinsep', 'decipherment', 'ancestor of Indic scripts'] },
    { slug: 'ashokan-edicts-and-prakrit', en: 'Ashoka’s edicts and Prakrit', hi: 'अशोक के शिलालेख और प्राकृत', qids: ['Q779933', 'Q192170'], keywords: ['Edicts of Ashoka', 'Prakrit', 'Kharosthi', 'rock inscriptions'] },
    { slug: 'indus-script', en: 'The undeciphered Indus script', hi: 'सिंधु घाटी की न पढ़ी जा सकी लिपि', qids: ['Q601388'], keywords: ['Indus script', 'Harappa seals', 'undeciphered', 'sign count'] },
    { slug: 'ol-chiki-and-santali', en: 'Ol Chiki and the Santali language', hi: 'ओल चिकी लिपि और संताली', qids: ['Q201688', 'Q33965'], keywords: ['Ol Chiki', 'Santali language', 'Raghunath Murmu', 'tribal script'] },
    { slug: 'gurmukhi-script', en: 'The Gurmukhi script', hi: 'गुरमुखी लिपि', qids: ['Q689894'], keywords: ['Gurmukhi', 'Guru Angad', 'Punjabi', 'Guru Granth Sahib'] },
    { slug: 'malayalam-language', en: 'Malayalam', hi: 'मलयालम भाषा', qids: ['Q36236'], keywords: ['Malayalam', 'palindrome name', 'Kerala', 'Dravidian language'] },
    { slug: 'dravidian-languages', en: 'The Dravidian language family', hi: 'द्रविड़ भाषा परिवार', qids: ['Q33311'], keywords: ['Dravidian languages', 'Brahui', 'Telugu', 'Kannada', 'language family'] },
    { slug: 'indo-aryan-languages', en: 'The Indo-Aryan languages', hi: 'इंडो-आर्यन भाषाएँ', qids: ['Q33577'], keywords: ['Indo-Aryan languages', 'Marathi', 'Odia', 'Sinhala', 'language tree'] },
    { slug: 'classical-languages-of-india', en: 'India’s classical languages', hi: 'भारत की शास्त्रीय भाषाएँ', qids: ['Q116275530'], keywords: ['classical language status', 'Tamil 2004', 'Sanskrit', 'Odia', 'Marathi'] },
    { slug: 'indian-sign-language', en: 'Indian Sign Language', hi: 'भारतीय सांकेतिक भाषा', qids: ['Q3306265'], keywords: ['Indian Sign Language', 'Indo-Pakistani Sign Language', 'ISLRTC', 'deaf community'] },
    { slug: 'three-language-formula', en: 'The three-language formula', hi: 'त्रिभाषा फ़ॉर्मूला', qids: ['Q7797263'], keywords: ['three-language formula', 'Official Languages Act 1963', 'language policy India'] },
    { slug: 'bombay-hindi-slang', en: 'Bambaiya Hindi and film slang', hi: 'बंबइया हिंदी और फ़िल्मी बोली', qids: ['Q3543151'], keywords: ['Bombay Hindi', 'bindaas', 'Bambaiya slang', 'tapori'] },
    { slug: 'proto-indo-european', en: 'Proto-Indo-European, the reconstructed ancestor', hi: 'प्रोटो-इंडो-यूरोपियन — जोड़कर बनाई गई पुरखा भाषा', qids: ['Q37178'], keywords: ['Proto-Indo-European', 'comparative method', 'William Jones', 'cognates'] },
    { slug: 'types-of-writing-systems', en: 'Alphabets, abjads and abugidas', hi: 'वर्णमाला, अब्जद और अबुगिदा', qids: ['Q8192'], keywords: ['writing system', 'abjad', 'abugida', 'logogram', 'syllabary'] },
    { slug: 'egyptian-hieroglyphs', en: 'Hieroglyphs and the Rosetta Stone', hi: 'मिस्री चित्रलिपि और रोज़ेटा स्टोन', qids: ['Q132659', 'Q48584'], keywords: ['Egyptian hieroglyphs', 'Rosetta Stone', 'Champollion', 'cartouche'] },
    { slug: 'cuneiform', en: 'Cuneiform, the oldest writing', hi: 'कीलाक्षर — सबसे पुरानी लिखाई', qids: ['Q401'], keywords: ['cuneiform', 'Sumerian', 'clay tablet', 'Uruk'] },
    { slug: 'chinese-characters', en: 'Chinese characters', hi: 'चीनी लिपि के अक्षर', qids: ['Q8201'], keywords: ['Chinese characters', 'hanzi', 'radicals', 'simplified characters'] },
    { slug: 'japanese-writing-systems', en: 'Japan’s three writing systems', hi: 'जापान की तीन लेखन प्रणालियाँ', qids: ['Q190502'], keywords: ['Japanese writing system', 'hiragana', 'katakana', 'kanji'] },
    { slug: 'arabic-script', en: 'The Arabic script', hi: 'अरबी लिपि', qids: ['Q1828555'], keywords: ['Arabic script', 'right to left', 'letter forms', 'diacritics'] },
    { slug: 'latin-alphabet', en: 'The Latin alphabet', hi: 'रोमन वर्णमाला', qids: ['Q41670'], keywords: ['Latin alphabet', 'letter J and W', 'Etruscan', 'romanisation'] },
    { slug: 'greek-alphabet', en: 'The Greek alphabet', hi: 'यूनानी वर्णमाला', qids: ['Q8216'], keywords: ['Greek alphabet', 'first vowels', 'alpha beta', 'Phoenician origin'] },
    { slug: 'endangered-languages', en: 'Languages going extinct', hi: 'लुप्त होती भाषाएँ', qids: ['Q335214'], keywords: ['endangered language', 'last speaker', 'UNESCO atlas', 'language death'] },
    { slug: 'esperanto', en: 'Esperanto', hi: 'एस्पेरांतो', qids: ['Q143'], keywords: ['Esperanto', 'Zamenhof', 'planned language', 'native speakers'] },
    { slug: 'constructed-languages', en: 'Invented languages', hi: 'गढ़ी हुई भाषाएँ', qids: ['Q33215', 'Q1067836'], keywords: ['constructed language', 'Klingon', 'Elvish languages', 'Tolkien', 'Dothraki'] },
    { slug: 'american-sign-language', en: 'American Sign Language', hi: 'अमेरिकन साइन लैंग्वेज', qids: ['Q14759'], keywords: ['American Sign Language', 'fingerspelling', 'Gallaudet', 'sign grammar'] },
    { slug: 'braille', en: 'Braille', hi: 'ब्रेल लिपि', qids: ['Q79894'], keywords: ['Braille', 'Louis Braille', 'six dots', 'Bharati Braille'] },
    { slug: 'unicode-and-emoji', en: 'Unicode and emoji', hi: 'यूनिकोड और इमोजी', qids: ['Q8819', 'Q1049294'], keywords: ['Unicode', 'emoji', 'code point', 'Indic scripts encoding'] },
    { slug: 'loanwords-and-false-friends', en: 'Loanwords and false friends', hi: 'उधार के शब्द और धोखा देने वाले शब्द', qids: ['Q103808'], keywords: ['loanword', 'false friend', 'calque', 'borrowing'] },
  ],
};
