import type { CategoryDef } from '../taxonomy-types.js';

export const indianCulture: CategoryDef = {
  id: 18,
  slug: 'indian-culture-festivals-mythology',
  en: 'Indian Culture, Festivals & Mythology',
  hi: 'भारतीय संस्कृति, त्योहार और पुराण',
  emoji: '🪔',
  kidsSafe: true,
  subtopics: [
    { slug: 'diwali-and-its-five-days', en: 'Diwali and its five days', hi: 'दिवाली और उसके पाँच दिन', qids: ['Q10244'], keywords: ['Diwali', 'Dhanteras', 'Govardhan puja', 'Bhai Dooj'] },
    { slug: 'holi-and-holika-dahan', en: 'Holi and Holika Dahan', hi: 'होली और होलिका दहन', qids: ['Q16191443'], keywords: ['Holi', 'Holika Dahan', 'Lathmar Holi', 'Braj'] },
    { slug: 'durga-puja-in-bengal', en: 'Durga Puja in Bengal', hi: 'बंगाल की दुर्गा पूजा', qids: ['Q1145922'], keywords: ['Durga Puja', 'pandal', 'Kumartuli idols', 'Sindoor Khela'] },
    { slug: 'ganesh-chaturthi', en: 'Ganesh Chaturthi in Maharashtra', hi: 'महाराष्ट्र में गणेश चतुर्थी', qids: ['Q929250'], keywords: ['Ganesh Chaturthi', 'Lalbaugcha Raja', 'visarjan', 'Tilak'] },
    { slug: 'onam-in-kerala', en: 'Onam in Kerala', hi: 'केरल का ओणम', qids: ['Q59178'], keywords: ['Onam', 'Mahabali', 'pookalam', 'Vallam Kali boat race'] },
    { slug: 'pongal-and-tamil-harvest', en: 'Pongal and the Tamil harvest', hi: 'पोंगल और तमिल फ़सल का त्योहार', qids: ['Q29271'], keywords: ['Pongal', 'Jallikattu', 'Thai month', 'harvest festival'] },
    { slug: 'bihu-of-assam', en: 'Bihu in Assam', hi: 'असम का बिहू', qids: ['Q2461213'], keywords: ['Bihu', 'Rongali Bihu', 'Assam dance', 'dhol'] },
    { slug: 'baisakhi-and-punjabi-new-year', en: 'Baisakhi and the Punjabi new year', hi: 'बैसाखी और पंजाबी नया साल', qids: ['Q2461213'], keywords: ['Baisakhi', 'Khalsa', 'bhangra', 'harvest'] },
    { slug: 'navratri-and-garba', en: 'Navratri and garba', hi: 'नवरात्रि और गरबा', qids: ['Q10269'], keywords: ['Navratri', 'garba', 'dandiya raas', 'nine nights'] },
    { slug: 'chhath-puja', en: 'Chhath Puja', hi: 'छठ पूजा', qids: ['Q2671645'], keywords: ['Chhath Puja', 'Bihar', 'Surya worship', 'ghat'] },
    { slug: 'regional-new-years', en: 'Ugadi, Gudi Padwa and regional new years', hi: 'उगादी, गुड़ी पड़वा और अलग-अलग नए साल', qids: ['Q615384'], keywords: ['Ugadi', 'Gudi Padwa', 'Puthandu', 'Vishu'] },
    { slug: 'eid-in-india', en: 'Eid in India', hi: 'भारत में ईद', qids: ['Q464458'], keywords: ['Eid ul-Fitr', 'sewaiyan', 'Ramzan', 'Jama Masjid'] },
    { slug: 'hornbill-festival-nagaland', en: 'The Hornbill Festival of Nagaland', hi: 'नागालैंड का हॉर्नबिल फ़ेस्टिवल', qids: ['Q17055323'], keywords: ['Hornbill Festival', 'Naga tribes', 'Kisama', 'Kohima'] },
    { slug: 'rath-yatra-of-puri', en: 'The Rath Yatra of Puri', hi: 'पुरी की रथ यात्रा', qids: ['Q2826519'], keywords: ['Rath Yatra', 'Jagannath', 'Puri chariot', 'Odisha'] },
    { slug: 'kumbh-mela', en: 'The Kumbh Mela', hi: 'कुंभ मेला', qids: ['Q10283'], keywords: ['Kumbh Mela', 'Prayagraj', 'Naga sadhu', 'shahi snan'] },
    { slug: 'the-ramayana', en: 'The Ramayana', hi: 'रामायण', qids: ['Q7759379'], keywords: ['Ramayana', 'Valmiki', 'Ramcharitmanas', 'Tulsidas'] },
    { slug: 'the-mahabharata', en: 'The Mahabharata', hi: 'महाभारत', qids: ['Q7749606'], keywords: ['Mahabharata', 'Kurukshetra', 'Vyasa', 'Pandavas'] },
    { slug: 'the-bhagavad-gita', en: 'The Bhagavad Gita', hi: 'भगवद्गीता', qids: ['Q63196913'], keywords: ['Bhagavad Gita', 'Krishna Arjuna', 'chapters', 'commentaries'] },
    { slug: 'puranas-and-their-stories', en: 'The Puranas and their stories', hi: 'पुराण और उनकी कहानियाँ', qids: ['Q7260824'], keywords: ['Purana', 'Bhagavata Purana', 'samudra manthan', 'avatars'] },
    { slug: 'panchatantra-and-jataka', en: 'The Panchatantra and Jataka tales', hi: 'पंचतंत्र और जातक कथाएँ', qids: ['Q233780'], keywords: ['Panchatantra', 'Jataka tales', 'Hitopadesha', 'fables'] },
    { slug: 'nagara-temple-architecture', en: 'Nagara style temple architecture', hi: 'नागर शैली के मंदिर', qids: ['Q123458533'], keywords: ['Nagara style', 'shikhara', 'Khajuraho', 'Konark'] },
    { slug: 'dravidian-temple-architecture', en: 'Dravidian style temple architecture', hi: 'द्रविड़ शैली के मंदिर', qids: ['Q171309'], keywords: ['Dravidian architecture', 'gopuram', 'Brihadeeswarar temple', 'Meenakshi temple'] },
    { slug: 'mughal-architecture-and-taj-mahal', en: 'Mughal architecture and the Taj Mahal', hi: 'मुग़ल वास्तुकला और ताजमहल', qids: ['Q9141'], keywords: ['Taj Mahal', 'Mughal architecture', 'pietra dura', 'charbagh'] },
    { slug: 'ajanta-and-ellora-caves', en: 'The Ajanta and Ellora caves', hi: 'अजंता और एलोरा की गुफाएँ', qids: ['Q184427'], keywords: ['Ajanta caves', 'Ellora', 'Kailasa temple', 'rock-cut'] },
    { slug: 'bharatanatyam', en: 'Bharatanatyam', hi: 'भरतनाट्यम', qids: ['Q334156'], keywords: ['Bharatanatyam', 'Natya Shastra', 'mudra', 'Tanjore'] },
    { slug: 'kathak', en: 'Kathak', hi: 'कथक', qids: ['Q949256'], keywords: ['Kathak', 'Lucknow gharana', 'tatkar footwork', 'ghungroo'] },
    { slug: 'kathakali-and-mohiniyattam', en: 'Kathakali and Mohiniyattam', hi: 'कथकली और मोहिनीअट्टम', qids: ['Q839500'], keywords: ['Kathakali', 'Mohiniyattam', 'Kerala dance', 'face makeup'] },
    { slug: 'odissi-and-manipuri', en: 'Odissi and Manipuri', hi: 'ओडिसी और मणिपुरी', qids: ['Q2014687'], keywords: ['Odissi', 'Manipuri dance', 'tribhangi', 'raas leela'] },
    { slug: 'hindustani-and-carnatic-music', en: 'Hindustani and Carnatic music', hi: 'हिंदुस्तानी और कर्नाटक संगीत', qids: ['Q1770695'], keywords: ['Hindustani music', 'Carnatic music', 'raga', 'tala'] },
    { slug: 'folk-theatre-traditions', en: 'Ramlila, Yakshagana and folk theatre', hi: 'रामलीला, यक्षगान और लोक नाटक', qids: ['Q167067'], keywords: ['Ramlila', 'Yakshagana', 'Nautanki', 'Therukoothu'] },
    { slug: 'indian-silks-and-weaves', en: 'Banarasi, Kanjeevaram and Indian silks', hi: 'बनारसी, कांजीवरम और भारतीय रेशम', qids: ['Q2723230'], keywords: ['Banarasi saree', 'Kanjeevaram silk', 'Patola', 'handloom'] },
    { slug: 'block-printing-and-bandhani', en: 'Block printing and bandhani', hi: 'ब्लॉक प्रिंटिंग और बांधनी', qids: ['Q1261053'], keywords: ['block printing', 'bandhani tie-dye', 'Ajrakh', 'Sanganeri'] },
    { slug: 'folk-painting-traditions', en: 'Madhubani, Warli and folk painting', hi: 'मधुबनी, वारली और लोक चित्रकला', qids: ['Q2547125'], keywords: ['Madhubani painting', 'Warli art', 'Pattachitra', 'Gond art'] },
    { slug: 'indian-wedding-customs', en: 'Indian wedding customs', hi: 'भारतीय शादी की रस्में', qids: ['Q7395718'], keywords: ['saat phere', 'mehndi', 'baraat', 'mangalsutra'] },
    { slug: 'bhakti-movement-saints', en: 'Saints of the Bhakti movement', hi: 'भक्ति आंदोलन के संत', qids: ['Q2914617'], keywords: ['Bhakti movement', 'Kabir', 'Meerabai', 'Tukaram'] },
    { slug: 'sufi-dargahs-and-qawwali', en: 'Sufi dargahs and qawwali', hi: 'सूफ़ी दरगाहें और क़व्वाली', qids: ['Q5222593'], keywords: ['Sufi', 'Ajmer Sharif', 'qawwali', 'Amir Khusrau'] },
  ],
};
