import type { CategoryDef } from '../taxonomy-types.js';

export const startups: CategoryDef = {
  id: 7,
  slug: 'startups-business',
  en: 'Startups & Business',
  hi: 'स्टार्टअप और व्यापार',
  emoji: '🚀',
  kidsSafe: true,
  subtopics: [
    { slug: 'infosys-and-indian-it', en: 'Infosys and the Indian IT boom', hi: 'इंफ़ोसिस और भारत का आईटी बूम', keywords: ['Infosys', 'Narayana Murthy', 'IT services', 'offshoring'] },
    { slug: 'tcs-and-the-tata-group', en: 'TCS and the Tata group', hi: 'टीसीएस और टाटा ग्रुप', qids: ['Q2377884'], keywords: ['TCS', 'Tata Sons', 'JRD Tata', 'conglomerate'] },
    { slug: 'wipro-and-azim-premji', en: 'Wipro and Azim Premji', hi: 'विप्रो और अज़ीम प्रेमजी', qids: ['Q380152'], keywords: ['Wipro', 'Azim Premji', 'vanaspati', 'philanthropy'] },
    { slug: 'flipkart-story', en: 'The Flipkart story', hi: 'फ़्लिपकार्ट की कहानी', qids: ['Q1381966'], keywords: ['Flipkart', 'Bansal', 'Walmart acquisition', 'e-commerce India'] },
    { slug: 'food-delivery-apps', en: 'Zomato, Swiggy and food delivery', hi: 'ज़ोमैटो, स्विगी और फ़ूड डिलीवरी', qids: ['Q8073715'], keywords: ['Zomato', 'Swiggy', 'food delivery', 'dark kitchen'] },
    { slug: 'upi-era-fintech', en: 'UPI-era fintech companies', hi: 'यूपीआई दौर का फ़िनटेक', qids: ['Q30324297'], keywords: ['Paytm', 'PhonePe', 'Razorpay', 'fintech India'] },
    { slug: 'ride-hailing-in-india', en: 'Ola, Uber and ride hailing', hi: 'ओला, उबर और कैब का धंधा', keywords: ['Ola', 'Uber', 'ride hailing', 'aggregator'] },
    { slug: 'bengaluru-startup-hub', en: 'Bengaluru as a startup capital', hi: 'बेंगलुरु: स्टार्टअप की राजधानी', qids: ['Q1355'], keywords: ['Bengaluru', 'Koramangala', 'startup hub', 'Electronic City'] },
    { slug: 'indian-unicorns', en: 'India’s unicorn companies', hi: 'भारत के यूनिकॉर्न स्टार्टअप', qids: ['Q3549947'], keywords: ['unicorn', 'valuation', 'Indian startups'] },
    { slug: 'edtech-boom', en: 'The edtech boom and bust', hi: 'एडटेक का उछाल और गिरावट', qids: ['Q48999036'], keywords: ['BYJU’S', 'Unacademy', 'edtech', 'online learning'] },
    { slug: 'jio-and-the-telecom-war', en: 'Jio and the telecom price war', hi: 'जियो और टेलीकॉम की क़ीमत जंग', qids: ['Q18643672'], keywords: ['Reliance Jio', 'telecom', 'data prices', 'spectrum'] },
    { slug: 'maruti-and-indias-car-market', en: 'Maruti and India’s car market', hi: 'मारुति और भारत का कार बाज़ार', qids: ['Q63997117'], keywords: ['Maruti', 'Suzuki', 'Ambassador', 'automobile India'] },
    { slug: 'amul-and-the-dairy-cooperative', en: 'Amul and the dairy cooperative', hi: 'अमूल और दूध की सहकारी क्रांति', qids: ['Q180385'], keywords: ['Amul', 'Verghese Kurien', 'Operation Flood', 'cooperative'] },
    { slug: 'dhirubhai-ambani-and-reliance', en: 'Dhirubhai Ambani and Reliance', hi: 'धीरूभाई अंबानी और रिलायंस', qids: ['Q468364'], keywords: ['Dhirubhai Ambani', 'Reliance', 'polyester', 'retail investors'] },
    { slug: 'licence-raj-to-liberalisation', en: 'From Licence Raj to liberalisation', hi: 'लाइसेंस राज से उदारीकरण तक', qids: ['Q1461789'], keywords: ['Licence Raj', 'MRTP', 'liberalisation', 'permit'] },
    { slug: 'bombay-cotton-mills', en: 'The Bombay cotton mills', hi: 'बंबई की कपड़ा मिलें', qids: ['Q123130829'], keywords: ['textile mills', 'Bombay', 'cotton', 'industrialisation'] },
    { slug: 'indian-business-houses', en: 'India’s old business houses', hi: 'भारत के पुराने कारोबारी घराने', qids: ['Q56312'], keywords: ['Birla', 'Godrej', 'Bajaj', 'Marwari'] },
    { slug: 'silicon-valley-origins', en: 'How Silicon Valley began', hi: 'सिलिकॉन वैली की शुरुआत', qids: ['Q163820'], keywords: ['Silicon Valley', 'Fairchild', 'Stanford', 'transistor'] },
    { slug: 'accelerators-and-incubators', en: 'Accelerators and incubators', hi: 'एक्सेलरेटर और इनक्यूबेटर', keywords: ['Y Combinator', 'accelerator', 'demo day', 'incubator'] },
    { slug: 'venture-capital-explained', en: 'How venture capital works', hi: 'वेंचर कैपिटल कैसे काम करता है', qids: ['Q77202602'], keywords: ['venture capital', 'limited partner', 'term sheet'] },
    { slug: 'startup-funding-rounds', en: 'Seed, Series A and funding rounds', hi: 'सीड, सीरीज़ ए और फंडिंग राउंड', qids: ['Q110286097'], keywords: ['seed round', 'Series A', 'cap table', 'dilution'] },
    { slug: 'apple-founding-years', en: 'Apple’s founding years', hi: 'ऐपल के शुरुआती साल', qids: ['Q312'], keywords: ['Apple', 'Steve Jobs', 'Wozniak', 'Macintosh'] },
    { slug: 'rise-of-microsoft', en: 'The rise of Microsoft', hi: 'माइक्रोसॉफ़्ट का उदय', qids: ['Q2283'], keywords: ['Microsoft', 'Bill Gates', 'MS-DOS', 'Windows'] },
    { slug: 'google-and-search-advertising', en: 'Google and search advertising', hi: 'गूगल और सर्च विज्ञापन', qids: ['Q95'], keywords: ['Google', 'PageRank', 'AdWords', 'Alphabet'] },
    { slug: 'amazon-and-e-commerce', en: 'Amazon and e-commerce', hi: 'ऐमज़ॉन और ई-कॉमर्स', qids: ['Q3884'], keywords: ['Amazon', 'Jeff Bezos', 'AWS', 'warehouse'] },
    { slug: 'spacex-and-private-spaceflight', en: 'SpaceX and private spaceflight', hi: 'स्पेसएक्स और निजी अंतरिक्ष उड़ान', qids: ['Q193701'], keywords: ['SpaceX', 'Falcon 9', 'reusable rocket'] },
    { slug: 'electric-car-companies', en: 'Electric car companies', hi: 'इलेक्ट्रिक कार कंपनियाँ', qids: ['Q13629441'], keywords: ['Tesla', 'BYD', 'electric vehicle', 'battery'] },
    { slug: 'the-dot-com-bubble', en: 'The dot-com bubble', hi: 'डॉट-कॉम बुलबुला', qids: ['Q79721'], keywords: ['dot-com', 'Nasdaq', '2000 crash', 'Pets.com'] },
    { slug: 'semiconductors-and-chipmakers', en: 'Semiconductors and chipmakers', hi: 'सेमीकंडक्टर और चिप कंपनियाँ', qids: ['Q13883136'], keywords: ['TSMC', 'Intel', 'foundry', 'Moore’s law'] },
    { slug: 'east-india-company-as-a-business', en: 'The East India Company as a business', hi: 'ईस्ट इंडिया कंपनी: एक कारोबार', qids: ['Q83164'], keywords: ['East India Company', 'joint stock', 'monopoly', 'shareholders'] },
    { slug: 'assembly-line-and-mass-production', en: 'The assembly line and mass production', hi: 'असेंबली लाइन और बड़े पैमाने का उत्पादन', qids: ['Q8768'], keywords: ['Henry Ford', 'assembly line', 'Model T', 'mass production'] },
    { slug: 'franchising-and-fast-food', en: 'Franchising and fast food', hi: 'फ़्रैंचाइज़ी और फ़ास्ट फ़ूड', qids: ['Q38076'], keywords: ['McDonald’s', 'franchise', 'KFC', 'chain restaurant'] },
    { slug: 'famous-corporate-failures', en: 'Famous corporate failures', hi: 'नामी कंपनियाँ जो डूब गईं', qids: ['Q65068095'], keywords: ['Nokia', 'Kodak', 'Blockbuster', 'disruption'] },
    { slug: 'brand-names-and-logos', en: 'Where brand names and logos come from', hi: 'ब्रांड के नाम और लोगो कहाँ से आए', qids: ['Q2519914'], keywords: ['brand name', 'logo', 'trademark', 'origin'] },
    { slug: 'gig-economy-and-platform-work', en: 'The gig economy and platform work', hi: 'गिग इकॉनमी और प्लेटफ़ॉर्म पर काम', qids: ['Q51711208'], keywords: ['gig economy', 'delivery workers', 'platform work'] },
    { slug: 'acquisitions-and-exits', en: 'Acquisitions and startup exits', hi: 'अधिग्रहण और स्टार्टअप एग्ज़िट', qids: ['Q22340494'], keywords: ['acquisition', 'exit', 'merger', 'acqui-hire'] },
  ],
};
