import type { CategoryDef } from '../taxonomy-types.js';

export const television: CategoryDef = {
  id: 21,
  slug: 'television-streaming',
  en: 'Television & Streaming',
  hi: 'टीवी और स्ट्रीमिंग',
  emoji: '📺',
  kidsSafe: true,
  subtopics: [
    { slug: 'doordarshan-history', en: 'The story of Doordarshan', hi: 'दूरदर्शन की कहानी', qids: ['Q1763315'], keywords: ['Doordarshan', '1959 Delhi', 'DD National', 'Indian television'] },
    { slug: 'krishi-darshan', en: 'Krishi Darshan, India’s longest-running show', hi: 'कृषि दर्शन — भारत का सबसे पुराना चलता कार्यक्रम', qids: ['Q1008701'], keywords: ['Krishi Darshan', '1967', 'farmers programme', 'Doordarshan'] },
    { slug: 'hum-log', en: 'Hum Log, India’s first soap', hi: 'हम लोग — भारत का पहला सोप', qids: ['Q5936556'], keywords: ['Hum Log', '1984', 'Ashok Kumar', 'Manohar Shyam Joshi'] },
    { slug: 'buniyaad', en: 'Buniyaad and the Partition drama', hi: 'बुनियाद और बँटवारे की कहानी', qids: ['Q4997708'], keywords: ['Buniyaad', 'Ramesh Sippy', '1986', 'Partition serial'] },
    { slug: 'ramayan-1987', en: 'Ramayan (1987)', hi: 'रामायण (1987)', qids: ['Q3345634'], keywords: ['Ramayan 1987', 'Ramanand Sagar', 'Arun Govil', 'viewership record'] },
    { slug: 'mahabharat-1988', en: 'Mahabharat (1988)', hi: 'महाभारत (1988)', qids: ['Q3312543'], keywords: ['Mahabharat 1988', 'B. R. Chopra', 'Main Samay Hoon', 'Nitish Bharadwaj'] },
    { slug: 'malgudi-days', en: 'Malgudi Days on screen', hi: 'मालगुडी डेज़', qids: ['Q3312708'], keywords: ['Malgudi Days', 'R. K. Narayan', 'Shankar Nag', 'Agumbe'] },
    { slug: 'chitrahaar-and-film-song-shows', en: 'Chitrahaar and film-song shows', hi: 'चित्रहार और फ़िल्मी गानों के कार्यक्रम', qids: ['Q5102311'], keywords: ['Chitrahaar', 'Rangoli', 'film songs', 'Doordarshan'] },
    { slug: 'byomkesh-bakshi-serial', en: 'Byomkesh Bakshi on Doordarshan', hi: 'दूरदर्शन का ब्योमकेश बक्शी', qids: ['Q19891099'], keywords: ['Byomkesh Bakshi', 'Rajit Kapur', 'Saradindu Bandyopadhyay', 'detective serial'] },
    { slug: 'shaktimaan', en: 'Shaktimaan', hi: 'शक्तिमान', qids: ['Q3345441'], keywords: ['Shaktimaan', 'Mukesh Khanna', '1997', 'Indian superhero'] },
    { slug: 'colour-tv-and-1982-asian-games', en: 'Colour TV and the 1982 Asian Games', hi: 'रंगीन टीवी और 1982 के एशियाई खेल', qids: ['Q729509'], keywords: ['colour television India', '1982 Asian Games', 'INSAT-1A', 'Delhi'] },
    { slug: 'cable-and-satellite-boom', en: 'The cable and satellite boom of the 1990s', hi: 'नब्बे के दशक का केबल और सैटेलाइट धमाका', qids: ['Q2044826'], keywords: ['Zee TV', 'STAR TV', 'cable television India', '1991 Gulf War CNN'] },
    { slug: 'saas-bahu-era', en: 'The saas-bahu serial era', hi: 'सास-बहू सीरियलों का दौर', qids: ['Q6452765'], keywords: ['Kyunki Saas Bhi Kabhi Bahu Thi', 'Ekta Kapoor', 'Balaji Telefilms', 'Kahaani Ghar Ghar Ki'] },
    { slug: 'kaun-banega-crorepati', en: 'Kaun Banega Crorepati', hi: 'कौन बनेगा करोड़पति', qids: ['Q2122128'], keywords: ['Kaun Banega Crorepati', 'Who Wants to Be a Millionaire', 'Amitabh Bachchan', 'hot seat'] },
    { slug: 'cid-serial', en: 'CID, the marathon crime show', hi: 'सी.आई.डी. — सबसे लंबा चलने वाला क्राइम शो', qids: ['Q252118'], keywords: ['CID Indian TV', 'ACP Pradyuman', 'Sony Entertainment', 'longest running'] },
    { slug: 'sarabhai-vs-sarabhai', en: 'Sarabhai vs Sarabhai', hi: 'सारा भाई वर्सेज़ सारा भाई', qids: ['Q7421927'], keywords: ['Sarabhai vs Sarabhai', 'Ratna Pathak Shah', 'sitcom India', 'Star One'] },
    { slug: 'taarak-mehta-ka-ooltah-chashmah', en: 'Taarak Mehta Ka Ooltah Chashmah', hi: 'तारक मेहता का उल्टा चश्मा', qids: ['Q2719817'], keywords: ['Taarak Mehta Ka Ooltah Chashmah', 'Gokuldham', 'SAB TV', 'Jethalal'] },
    { slug: 'indian-singing-reality-shows', en: 'Indian singing reality shows', hi: 'भारतीय सिंगिंग रियलिटी शो', qids: ['Q4115199'], keywords: ['Indian Idol', 'Sa Re Ga Ma Pa', 'reality show', 'SMS voting'] },
    { slug: 'bigg-boss-india', en: 'Bigg Boss', hi: 'बिग बॉस', qids: ['Q284261'], keywords: ['Bigg Boss', 'Big Brother format', 'Salman Khan', 'reality show'] },
    { slug: 'indian-news-channels', en: 'Indian news television', hi: 'भारतीय न्यूज़ चैनल', qids: ['Q2985356', 'Q3396358'], keywords: ['NDTV', 'Aaj Tak', 'TRP ratings', 'news channel India'] },
    { slug: 'indian-streaming-platforms', en: 'Indian streaming platforms', hi: 'भारतीय स्ट्रीमिंग प्लेटफ़ॉर्म', qids: ['Q19758675', 'Q51328854', 'Q17021043'], keywords: ['JioHotstar', 'ZEE5', 'SonyLIV', 'OTT India'] },
    { slug: 'indian-streaming-originals', en: 'Indian streaming originals', hi: 'भारतीय स्ट्रीमिंग ओरिजिनल सीरीज़', qids: ['Q48727094'], keywords: ['Sacred Games', 'Paatal Lok', 'Netflix India', 'web series'] },
    { slug: 'john-logie-baird', en: 'John Logie Baird and the first television', hi: 'जॉन लोगी बेयर्ड और पहला टेलीविज़न', qids: ['Q133544'], keywords: ['John Logie Baird', 'mechanical television', '1926 demonstration', 'Nipkow disk'] },
    { slug: 'bbc-television', en: 'BBC Television', hi: 'बीबीसी टेलीविज़न', qids: ['Q261492'], keywords: ['BBC Television', '1936 Alexandra Palace', 'licence fee', 'test card'] },
    { slug: 'i-love-lucy', en: 'I Love Lucy and the invention of the rerun', hi: 'आई लव लूसी और रीरन का जन्म', qids: ['Q181943'], keywords: ['I Love Lucy', 'Lucille Ball', 'three-camera setup', 'rerun'] },
    { slug: 'soap-opera-origins', en: 'Why they are called soap operas', hi: 'सोप ओपेरा नाम कहाँ से आया', qids: ['Q23739'], keywords: ['soap opera', 'radio serial', 'Procter and Gamble', 'sponsorship'] },
    { slug: 'sesame-street', en: 'Sesame Street', hi: 'सेसमी स्ट्रीट', qids: ['Q155629'], keywords: ['Sesame Street', 'Jim Henson', 'Galli Galli Sim Sim', 'children television'] },
    { slug: 'star-trek', en: 'Star Trek', hi: 'स्टार ट्रेक', qids: ['Q1077'], keywords: ['Star Trek', 'Gene Roddenberry', 'USS Enterprise', 'fan campaign'] },
    { slug: 'the-simpsons', en: 'The Simpsons', hi: 'द सिम्पसन्स', qids: ['Q886'], keywords: ['The Simpsons', 'Matt Groening', 'Springfield', 'longest running sitcom'] },
    { slug: 'friends-and-the-90s-sitcom', en: 'Friends and the 90s sitcom', hi: 'फ़्रेंड्स और नब्बे के सिटकॉम', qids: ['Q961460'], keywords: ['Friends', 'sitcom', 'laugh track', 'Central Perk'] },
    { slug: 'game-of-thrones', en: 'Game of Thrones', hi: 'गेम ऑफ़ थ्रोन्स', qids: ['Q23572'], keywords: ['Game of Thrones', 'HBO', 'piracy record', 'Emmy wins'] },
    { slug: 'netflix-history', en: 'How Netflix went from DVDs to streaming', hi: 'नेटफ़्लिक्स — डीवीडी से स्ट्रीमिंग तक', qids: ['Q907311', 'Q841645'], keywords: ['Netflix', 'DVD by mail', 'binge watching', 'streaming television'] },
    { slug: 'korean-drama', en: 'Korean drama and the Hallyu wave', hi: 'कोरियन ड्रामा और हल्यू लहर', qids: ['Q482612'], keywords: ['Korean drama', 'Hallyu', 'Squid Game', 'K-drama'] },
    { slug: 'telenovela', en: 'The telenovela', hi: 'टेलीनोवेला', qids: ['Q23745'], keywords: ['telenovela', 'Latin America', 'Brazil TV Globo', 'limited run serial'] },
    { slug: 'emmy-awards', en: 'The Emmy Awards', hi: 'एमी अवॉर्ड', qids: ['Q1044427'], keywords: ['Primetime Emmy Award', 'television award', 'record wins'] },
    { slug: 'apollo-11-broadcast', en: 'The Moon landing on live TV', hi: 'चाँद पर उतरने का सीधा प्रसारण', qids: ['Q43653'], keywords: ['Apollo 11 broadcast', 'live television', '1969 audience', 'Parkes Observatory'] },
  ],
};
