import type { CategoryDef } from '../taxonomy-types.js';

export const indianHistory: CategoryDef = {
  id: 12,
  slug: 'indian-history',
  en: 'Indian History',
  hi: 'भारतीय इतिहास',
  emoji: '🇮🇳',
  kidsSafe: false,
  subtopics: [
    { slug: 'indus-valley-cities', en: 'The cities of the Indus valley', hi: 'सिंधु घाटी के शहर', qids: ['Q185562'], keywords: ['Harappa', 'Mohenjo-daro', 'Dholavira', 'drainage'] },
    { slug: 'the-vedic-period', en: 'The Vedic period', hi: 'वैदिक काल', qids: ['Q215262'], keywords: ['Vedas', 'Rigveda', 'iron age', 'Sarasvati'] },
    { slug: 'mahajanapadas', en: 'The mahajanapadas and early republics', hi: 'महाजनपद और शुरुआती गणराज्य', qids: ['Q846025'], keywords: ['mahajanapada', 'Magadha', 'Vaishali', 'gana-sangha'] },
    { slug: 'the-mauryan-empire', en: 'The Mauryan empire', hi: 'मौर्य साम्राज्य', qids: ['Q62943'], keywords: ['Chandragupta Maurya', 'Ashoka', 'Arthashastra', 'Pataliputra'] },
    { slug: 'ashokan-edicts-and-pillars', en: 'The Ashokan edicts and pillars', hi: 'अशोक के शिलालेख और स्तंभ', qids: ['Q4805809'], keywords: ['Ashokan edicts', 'Sarnath pillar', 'Brahmi', 'Prakrit'] },
    { slug: 'the-sangam-age', en: 'The Sangam age of Tamilakam', hi: 'संगम युग और तमिलकम', qids: ['Q3219940'], keywords: ['Sangam literature', 'Chera', 'Pandya', 'Tamilakam'] },
    { slug: 'satavahanas-and-the-deccan', en: 'The Satavahanas and the Deccan', hi: 'सातवाहन और दक्कन', qids: ['Q103965487'], keywords: ['Satavahana', 'Amaravati', 'Deccan trade', 'Pratishthana'] },
    { slug: 'kushans-and-gandhara-art', en: 'The Kushans and Gandhara art', hi: 'कुषाण और गांधार कला', qids: ['Q713055'], keywords: ['Kushan', 'Kanishka', 'Gandhara', 'Greco-Buddhist'] },
    { slug: 'the-gupta-period', en: 'The Gupta period', hi: 'गुप्त काल', qids: ['Q11774'], keywords: ['Gupta empire', 'Aryabhata', 'Iron Pillar', 'Ajanta'] },
    { slug: 'nalanda-and-ancient-universities', en: 'Nalanda and the ancient universities', hi: 'नालंदा और पुराने विश्वविद्यालय', qids: ['Q6960799'], keywords: ['Nalanda', 'Takshashila', 'Vikramshila', 'Xuanzang'] },
    { slug: 'the-chola-empire', en: 'The Chola empire', hi: 'चोल साम्राज्य', qids: ['Q6806806'], keywords: ['Chola', 'Rajaraja', 'Brihadeeswarar', 'naval expeditions'] },
    { slug: 'pallavas-and-mahabalipuram', en: 'The Pallavas and Mahabalipuram', hi: 'पल्लव और महाबलीपुरम', qids: ['Q15104320'], keywords: ['Pallava', 'Mahabalipuram', 'rock-cut temples', 'Kanchipuram'] },
    { slug: 'rashtrakutas-and-ellora', en: 'The Rashtrakutas and the Kailasa temple', hi: 'राष्ट्रकूट और कैलाश मंदिर', qids: ['Q103963211'], keywords: ['Rashtrakuta', 'Ellora', 'Kailasa temple', 'Manyakheta'] },
    { slug: 'the-vijayanagara-empire', en: 'The Vijayanagara empire', hi: 'विजयनगर साम्राज्य', qids: ['Q167639'], keywords: ['Vijayanagara', 'Hampi', 'Krishnadevaraya', 'Tungabhadra'] },
    { slug: 'the-delhi-sultanate', en: 'The Delhi Sultanate', hi: 'दिल्ली सल्तनत', qids: ['Q229411'], keywords: ['Delhi Sultanate', 'Qutub Minar', 'Tughlaq', 'Khalji'] },
    { slug: 'the-deccan-sultanates', en: 'The Deccan sultanates', hi: 'दक्कन की सल्तनतें', qids: ['Q1183649'], keywords: ['Bahmani', 'Golconda', 'Bijapur', 'Gol Gumbaz'] },
    { slug: 'bhakti-and-sufi-movements', en: 'The Bhakti and Sufi movements', hi: 'भक्ति और सूफ़ी आंदोलन', qids: ['Q113809924'], keywords: ['Kabir', 'Mirabai', 'Sufi', 'Basava'] },
    { slug: 'the-mughal-empire', en: 'The Mughal empire', hi: 'मुग़ल साम्राज्य', qids: ['Q139685340'], keywords: ['Babur', 'Akbar', 'mansabdari', 'Aurangzeb'] },
    { slug: 'mughal-architecture-and-the-taj', en: 'Mughal architecture and the Taj Mahal', hi: 'मुग़ल वास्तुकला और ताजमहल', qids: ['Q9141'], keywords: ['Taj Mahal', 'Shah Jahan', 'Fatehpur Sikri', 'charbagh'] },
    { slug: 'sikh-gurus-and-the-khalsa', en: 'The Sikh gurus and the Khalsa', hi: 'सिख गुरु और ख़ालसा', qids: ['Q83322'], keywords: ['Guru Nanak', 'Guru Gobind Singh', 'Khalsa', 'Amritsar'] },
    { slug: 'the-maratha-empire', en: 'The Maratha empire', hi: 'मराठा साम्राज्य', qids: ['Q83618'], keywords: ['Shivaji', 'Peshwa', 'forts', 'Panipat 1761'] },
    { slug: 'the-ahom-kingdom', en: 'The Ahom kingdom of Assam', hi: 'असम का अहोम राज', qids: ['Q3631757'], keywords: ['Ahom', 'Lachit Borphukan', 'Saraighat', 'Buranji'] },
    { slug: 'kingdoms-of-the-north-east', en: 'Kingdoms of the North-East', hi: 'पूर्वोत्तर के राजवंश', qids: ['Q1193'], keywords: ['Manipur', 'Tripura', 'Kachari', 'Meitei'] },
    { slug: 'the-malabar-spice-trade', en: 'The Malabar spice trade', hi: 'मालाबार का मसाला व्यापार', qids: ['Q13544028'], keywords: ['Malabar', 'pepper', 'Calicut', 'Zamorin'] },
    { slug: 'bengal-nawabs-and-plassey', en: 'The Bengal nawabs and Plassey', hi: 'बंगाल के नवाब और प्लासी', qids: ['Q1998495'], keywords: ['Siraj-ud-Daulah', 'Plassey 1757', 'Murshidabad', 'diwani'] },
    { slug: 'east-india-company-rule', en: 'East India Company rule', hi: 'ईस्ट इंडिया कंपनी का राज', qids: ['Q83164'], keywords: ['East India Company', 'Permanent Settlement', 'Regulating Act', 'Company Raj'] },
    { slug: 'mysore-under-haidar-and-tipu', en: 'Mysore under Haidar Ali and Tipu Sultan', hi: 'हैदर अली और टीपू सुल्तान का मैसूर', qids: ['Q10088'], keywords: ['Tipu Sultan', 'Haidar Ali', 'Mysore wars', 'rockets'] },
    { slug: 'the-1857-uprising', en: 'The uprising of 1857', hi: '1857 का विद्रोह', qids: ['Q181878'], keywords: ['1857', 'Rani Lakshmibai', 'Meerut', 'sepoy'] },
    { slug: 'railways-and-the-telegraph', en: 'The railways and the telegraph', hi: 'रेलवे और तार का आना', qids: ['Q41137028'], keywords: ['Indian Railways 1853', 'telegraph', 'GIP Railway', 'gauge'] },
    { slug: 'the-bengal-renaissance', en: 'The Bengal renaissance', hi: 'बंगाल का नवजागरण', keywords: ['Raja Ram Mohan Roy', 'Tagore', 'Brahmo Samaj', 'Vidyasagar'] },
    { slug: 'founding-of-the-congress', en: 'The founding of the Indian National Congress', hi: 'कांग्रेस की स्थापना, 1885', qids: ['Q10225'], keywords: ['Indian National Congress', '1885', 'A O Hume', 'Bombay session'] },
    { slug: 'the-swadeshi-movement', en: 'The Swadeshi movement, 1905', hi: 'स्वदेशी आंदोलन, 1905', qids: ['Q179366'], keywords: ['Swadeshi', 'Bengal partition 1905', 'boycott', 'Tilak'] },
    { slug: 'gandhi-and-satyagraha', en: 'Gandhi and satyagraha', hi: 'गांधी और सत्याग्रह', qids: ['Q1001'], keywords: ['Gandhi', 'satyagraha', 'Champaran', 'non-cooperation'] },
    { slug: 'the-salt-march-1930', en: 'The Salt March, 1930', hi: 'नमक सत्याग्रह, 1930', qids: ['Q239344'], keywords: ['Dandi march', 'salt tax', '1930', 'civil disobedience'] },
    { slug: 'quit-india-and-the-ina', en: 'Quit India and the INA', hi: 'भारत छोड़ो और आज़ाद हिंद फ़ौज', qids: ['Q2153'], keywords: ['Quit India 1942', 'Subhas Chandra Bose', 'INA', 'Red Fort trials'] },
    { slug: 'independence-and-1947', en: 'Independence and the making of 1947', hi: 'आज़ादी और 1947 का बँटवारा', qids: ['Q1419358'], keywords: ['1947', 'Radcliffe Line', 'Mountbatten', 'integration of states'] },
  ],
};
