import type { CategoryDef } from '../taxonomy-types.js';

export const music: CategoryDef = {
  id: 20,
  slug: 'music',
  en: 'Music',
  hi: 'संगीत',
  emoji: '🎵',
  kidsSafe: true,
  subtopics: [
    { slug: 'hindustani-classical-music', en: 'Hindustani classical music', hi: 'हिंदुस्तानी शास्त्रीय संगीत', qids: ['Q1770695'], keywords: ['Hindustani classical', 'North Indian classical music', 'gharana'] },
    { slug: 'carnatic-music', en: 'Carnatic music', hi: 'कर्नाटक संगीत', qids: ['Q956883'], keywords: ['Carnatic music', 'kriti', 'Madras Music Season'] },
    { slug: 'ragas-and-time-of-day', en: 'Ragas and the time of day', hi: 'राग और उनके पहर', qids: ['Q216926'], keywords: ['raga', 'Bhairav', 'Malkauns', 'thaat', 'melakarta'] },
    { slug: 'tala-and-rhythm-cycles', en: 'Tala and rhythm cycles', hi: 'ताल और लय के चक्र', qids: ['Q1896571'], keywords: ['tala', 'teentaal', 'adi tala', 'matra', 'sam'] },
    { slug: 'dhrupad', en: 'Dhrupad, the oldest surviving style', hi: 'ध्रुपद — सबसे पुरानी बची हुई गायकी', qids: ['Q59158'], keywords: ['dhrupad', 'Dagar', 'alap', 'pakhawaj'] },
    { slug: 'khayal', en: 'Khayal singing', hi: 'ख़याल गायकी', qids: ['Q62128'], keywords: ['khayal', 'bandish', 'bada khayal', 'taan'] },
    { slug: 'thumri-and-dadra', en: 'Thumri and dadra', hi: 'ठुमरी और दादरा', qids: ['Q69596'], keywords: ['thumri', 'dadra', 'Banaras', 'Girija Devi'] },
    { slug: 'gwalior-gharana', en: 'The Gwalior gharana', hi: 'ग्वालियर घराना', qids: ['Q5623275'], keywords: ['Gwalior gharana', 'Haddu Hassu Khan', 'khayal'] },
    { slug: 'kirana-gharana', en: 'The Kirana gharana', hi: 'किराना घराना', qids: ['Q3595117'], keywords: ['Kirana gharana', 'Abdul Karim Khan', 'Bhimsen Joshi', 'Gangubai Hangal'] },
    { slug: 'jaipur-atrauli-gharana', en: 'The Jaipur-Atrauli gharana', hi: 'जयपुर-अतरौली घराना', qids: ['Q6124116'], keywords: ['Jaipur-Atrauli gharana', 'Alladiya Khan', 'Kesarbai Kerkar'] },
    { slug: 'tansen-and-mughal-court-music', en: 'Tansen and music at the Mughal court', hi: 'तानसेन और मुग़ल दरबार का संगीत', qids: ['Q469894'], keywords: ['Tansen', 'Akbar', 'Miyan ki Malhar', 'Gwalior'] },
    { slug: 'the-sitar', en: 'The sitar', hi: 'सितार', qids: ['Q229205'], keywords: ['sitar', 'sympathetic strings', 'jawari', 'Ravi Shankar'] },
    { slug: 'the-tabla', en: 'The tabla', hi: 'तबला', qids: ['Q213100'], keywords: ['tabla', 'bol', 'syahi', 'Zakir Hussain'] },
    { slug: 'saraswati-veena', en: 'The Saraswati veena', hi: 'सरस्वती वीणा', qids: ['Q16155191'], keywords: ['Saraswati veena', 'Thanjavur', 'Carnatic instrument'] },
    { slug: 'shehnai-and-bismillah-khan', en: 'The shehnai and Bismillah Khan', hi: 'शहनाई और बिस्मिल्लाह ख़ाँ', qids: ['Q847911', 'Q379707'], keywords: ['shehnai', 'Bismillah Khan', 'Bharat Ratna', 'Kashi Vishwanath'] },
    { slug: 'mridangam', en: 'The mridangam', hi: 'मृदंगम', qids: ['Q744831'], keywords: ['mridangam', 'Carnatic percussion', 'thani avarthanam'] },
    { slug: 'carnatic-trinity', en: 'The Carnatic trinity', hi: 'कर्नाटक संगीत की त्रिमूर्ति', qids: ['Q7843018'], keywords: ['Tyagaraja', 'Muthuswami Dikshitar', 'Syama Sastri', 'Thiruvaiyaru'] },
    { slug: 'm-s-subbulakshmi', en: 'M. S. Subbulakshmi', hi: 'एम. एस. सुब्बुलक्ष्मी', qids: ['Q465067'], keywords: ['M. S. Subbulakshmi', 'United Nations 1966', 'Suprabhatam', 'Bharat Ratna'] },
    { slug: 'ravi-shankar', en: 'Ravi Shankar', hi: 'पंडित रवि शंकर', qids: ['Q103774'], keywords: ['Ravi Shankar', 'Concert for Bangladesh', 'Woodstock', 'sitar'] },
    { slug: 'lata-mangeshkar', en: 'Lata Mangeshkar', hi: 'लता मंगेशकर', qids: ['Q156347'], keywords: ['Lata Mangeshkar', 'playback singer', 'Ae Mere Watan Ke Logon'] },
    { slug: 'rafi-and-kishore-kumar', en: 'Mohammed Rafi and Kishore Kumar', hi: 'मोहम्मद रफ़ी और किशोर कुमार', qids: ['Q156815', 'Q471542'], keywords: ['Mohammed Rafi', 'Kishore Kumar', 'playback singing', 'yodelling'] },
    { slug: 'golden-age-film-composers', en: 'Composers of the golden age of film music', hi: 'फ़िल्म संगीत के सुनहरे दौर के संगीतकार', qids: ['Q674337', 'Q2723913'], keywords: ['Naushad', 'S. D. Burman', 'Shankar-Jaikishan', 'Madan Mohan'] },
    { slug: 'r-d-burman', en: 'R. D. Burman', hi: 'आर. डी. बर्मन', qids: ['Q3351160'], keywords: ['R. D. Burman', 'Pancham', 'Sholay', 'Teesri Manzil'] },
    { slug: 'a-r-rahman', en: 'A. R. Rahman', hi: 'ए. आर. रहमान', qids: ['Q108560'], keywords: ['A. R. Rahman', 'Roja', 'Slumdog Millionaire', 'Academy Award'] },
    { slug: 'ilaiyaraaja', en: 'Ilaiyaraaja', hi: 'इलैयाराजा', qids: ['Q2720141'], keywords: ['Ilaiyaraaja', 'Tamil film music', 'How to Name It', 'symphony'] },
    { slug: 'qawwali-and-amir-khusrau', en: 'Qawwali and Amir Khusrau', hi: 'क़व्वाली और अमीर ख़ुसरो', qids: ['Q512410', 'Q207817'], keywords: ['qawwali', 'Amir Khusrau', 'Nizamuddin Auliya', 'Sufi music'] },
    { slug: 'nusrat-fateh-ali-khan', en: 'Nusrat Fateh Ali Khan', hi: 'नुसरत फ़तेह अली ख़ान', qids: ['Q299073'], keywords: ['Nusrat Fateh Ali Khan', 'qawwali', 'Real World Records', 'sargam'] },
    { slug: 'ghazal-singing', en: 'Ghazal singing', hi: 'ग़ज़ल गायकी', qids: ['Q281111', 'Q107067'], keywords: ['ghazal', 'Jagjit Singh', 'Mehdi Hassan', 'Begum Akhtar', 'radif'] },
    { slug: 'rabindra-sangeet', en: 'Rabindra Sangeet', hi: 'रबींद्र संगीत', qids: ['Q3345491'], keywords: ['Rabindra Sangeet', 'Tagore', 'Jana Gana Mana', 'Amar Shonar Bangla'] },
    { slug: 'bhangra-and-punjabi-folk', en: 'Bhangra and Punjabi folk music', hi: 'भांगड़ा और पंजाबी लोक संगीत', qids: ['Q854844'], keywords: ['bhangra', 'dhol', 'tumbi', 'Punjabi folk'] },
    { slug: 'bauls-of-bengal', en: 'The Bauls of Bengal', hi: 'बंगाल के बाउल', qids: ['Q811449'], keywords: ['Baul', 'Lalon', 'ektara', 'UNESCO intangible heritage'] },
    { slug: 'western-classical-eras', en: 'The eras of Western classical music', hi: 'पश्चिमी शास्त्रीय संगीत के दौर', qids: ['Q9730'], keywords: ['Baroque', 'Classical period', 'Romantic music', 'Bach', 'Mozart'] },
    { slug: 'birth-of-jazz', en: 'The birth of jazz', hi: 'जैज़ का जन्म', qids: ['Q8341'], keywords: ['jazz', 'New Orleans', 'Louis Armstrong', 'improvisation', 'bebop'] },
    { slug: 'rock-and-roll-and-the-beatles', en: 'Rock and roll and the Beatles', hi: 'रॉक एंड रोल और बीटल्स', qids: ['Q7749', 'Q1299'], keywords: ['rock and roll', 'The Beatles', 'Elvis Presley', 'Abbey Road'] },
    { slug: 'staff-notation', en: 'Staff notation and how music is written', hi: 'स्टाफ़ नोटेशन — संगीत लिखा कैसे जाता है', qids: ['Q192193'], keywords: ['staff notation', 'clef', 'Guido of Arezzo', 'solfege'] },
    { slug: 'sound-recording-technology', en: 'From the phonograph to streaming', hi: 'फ़ोनोग्राफ़ से स्ट्रीमिंग तक', qids: ['Q116434'], keywords: ['phonograph', 'vinyl record', 'magnetic tape', 'MP3', 'streaming'] },
  ],
};
