import type { CategoryDef } from '../taxonomy-types.js';

export const ai: CategoryDef = {
  id: 5,
  slug: 'artificial-intelligence',
  en: 'Artificial Intelligence',
  hi: 'कृत्रिम बुद्धिमत्ता',
  emoji: '🤖',
  kidsSafe: true,
  subtopics: [
    { slug: 'alan-turing-and-the-imitation-game', en: 'Alan Turing and the imitation game', hi: 'ऐलन ट्यूरिंग और इमिटेशन गेम', qids: ['Q7251'], keywords: ['Alan Turing', 'Turing test', 'Computing Machinery and Intelligence', 'imitation game'] },
    { slug: 'dartmouth-workshop-1956', en: 'The 1956 Dartmouth workshop', hi: '1956 की डार्टमथ वर्कशॉप', qids: ['Q2453355'], keywords: ['Dartmouth workshop', 'John McCarthy', 'Marvin Minsky', 'birth of AI'] },
    { slug: 'perceptron-and-early-neural-nets', en: 'The perceptron and the first neural nets', hi: 'परसेप्ट्रॉन और शुरुआती न्यूरल नेट', qids: ['Q690207'], keywords: ['perceptron', 'Frank Rosenblatt', 'Minsky Papert', 'neural network history'] },
    { slug: 'eliza-chatbot', en: 'ELIZA, the first chatbot', hi: 'एलिज़ा, पहला चैटबॉट', qids: ['Q75778'], keywords: ['ELIZA', 'Joseph Weizenbaum', 'ELIZA effect', 'early chatbot'] },
    { slug: 'expert-systems-and-ai-winter', en: 'Expert systems and the AI winters', hi: 'एक्सपर्ट सिस्टम और एआई विंटर', qids: ['Q184609'], keywords: ['expert system', 'AI winter', 'MYCIN', 'Lighthill report'] },
    { slug: 'deep-blue-vs-kasparov', en: 'Deep Blue versus Garry Kasparov', hi: 'डीप ब्लू बनाम गैरी कास्पारोव', qids: ['Q3235334'], keywords: ['Deep Blue', 'Garry Kasparov', '1997 chess match', 'IBM'] },
    { slug: 'ibm-watson-jeopardy', en: 'IBM Watson on Jeopardy!', hi: 'आईबीएम वॉटसन और जेपर्डी', qids: ['Q107386392'], keywords: ['IBM Watson', 'Jeopardy 2011', 'question answering', 'DeepQA'] },
    { slug: 'alphago-lee-sedol', en: 'AlphaGo and move 37', hi: 'अल्फ़ागो और मूव 37', qids: ['Q40415503'], keywords: ['AlphaGo', 'Lee Sedol', 'move 37', 'DeepMind Go'] },
    { slug: 'backpropagation', en: 'Backpropagation', hi: 'बैकप्रॉपगेशन', qids: ['Q798503'], keywords: ['backpropagation', 'gradient descent', 'Rumelhart Hinton', 'training neural network'] },
    { slug: 'imagenet-and-alexnet', en: 'ImageNet and the AlexNet moment', hi: 'इमेजनेट और अलेक्सनेट वाला पल', qids: ['Q24901201'], keywords: ['ImageNet', 'AlexNet', 'Fei-Fei Li', 'ILSVRC 2012'] },
    { slug: 'deep-learning', en: 'Deep learning', hi: 'डीप लर्निंग', qids: ['Q197536'], keywords: ['deep learning', 'Geoffrey Hinton', 'Yann LeCun', 'Yoshua Bengio'] },
    { slug: 'machine-learning-basics', en: 'How machine learning actually learns', hi: 'मशीन लर्निंग असल में सीखती कैसे है', qids: ['Q2539'], keywords: ['machine learning', 'training data', 'supervised learning', 'overfitting'] },
    { slug: 'reinforcement-learning', en: 'Reinforcement learning and reward', hi: 'रीइन्फ़ोर्समेंट लर्निंग और इनाम', qids: ['Q830687'], keywords: ['reinforcement learning', 'reward function', 'Q-learning', 'RLHF'] },
    { slug: 'transformers-and-attention', en: 'Transformers and the attention paper', hi: 'ट्रांसफ़ॉर्मर और अटेंशन वाला पेपर', qids: ['Q85810444'], keywords: ['Transformer model', 'Attention Is All You Need', 'self-attention', '2017 paper'] },
    { slug: 'large-language-models', en: 'Large language models and how they predict', hi: 'बड़े लैंग्वेज मॉडल और उनकी भविष्यवाणी', qids: ['Q115305900'], keywords: ['large language model', 'GPT', 'tokens', 'next token prediction'] },
    { slug: 'chatgpt-launch', en: 'The launch of ChatGPT', hi: 'चैटजीपीटी की लॉन्चिंग', qids: ['Q115564437'], keywords: ['ChatGPT', 'November 2022', 'fastest growing app', 'OpenAI'] },
    { slug: 'openai-history', en: 'OpenAI: from nonprofit to product company', hi: 'ओपनएआई: नॉन-प्रॉफ़िट से प्रोडक्ट कंपनी तक', qids: ['Q21708200'], keywords: ['OpenAI', 'founding 2015', 'capped profit', 'GPT models'] },
    { slug: 'deepmind-and-alphafold', en: 'DeepMind and AlphaFold’s protein structures', hi: 'डीपमाइंड और अल्फ़ाफ़ोल्ड की प्रोटीन संरचनाएँ', qids: ['Q60827595'], keywords: ['DeepMind', 'AlphaFold', 'protein folding', 'CASP'] },
    { slug: 'computer-vision', en: 'Computer vision and face recognition', hi: 'कंप्यूटर विज़न और चेहरा पहचानना', qids: ['Q844240'], keywords: ['computer vision', 'face recognition', 'object detection', 'convolutional network'] },
    { slug: 'speech-recognition', en: 'Speech recognition and voice assistants', hi: 'स्पीच रिकग्निशन और वॉइस असिस्टेंट', qids: ['Q189436'], keywords: ['speech recognition', 'Siri', 'Alexa', 'text to speech'] },
    { slug: 'machine-translation', en: 'Machine translation', hi: 'मशीन ट्रांसलेशन', qids: ['Q79798'], keywords: ['machine translation', 'Google Translate', 'neural MT', 'Georgetown experiment'] },
    { slug: 'ai-for-indian-languages', en: 'AI for Indian languages', hi: 'भारतीय भाषाओं के लिए एआई', qids: ['Q130553376'], keywords: ['Bhashini', 'Indic NLP', 'AI4Bharat', 'low-resource languages'] },
    { slug: 'generative-image-models', en: 'Text-to-image models', hi: 'टेक्स्ट से तस्वीर बनाने वाले मॉडल', qids: ['Q113940039'], keywords: ['text-to-image', 'diffusion model', 'Stable Diffusion', 'DALL-E'] },
    { slug: 'deepfakes', en: 'Deepfakes and synthetic media', hi: 'डीपफ़ेक और नक़ली मीडिया', qids: ['Q49473179'], keywords: ['deepfake', 'face swap', 'synthetic media', 'detection'] },
    { slug: 'self-driving-cars', en: 'Self-driving cars and the DARPA Grand Challenge', hi: 'सेल्फ़-ड्राइविंग कार और डार्पा ग्रैंड चैलेंज', qids: ['Q741490'], keywords: ['self-driving car', 'DARPA Grand Challenge', 'Waymo', 'autonomy levels'] },
    { slug: 'robotics', en: 'Robots, from factory arms to humanoids', hi: 'रोबोट: फ़ैक्ट्री के हाथ से ह्यूमनॉइड तक', qids: ['Q11012'], keywords: ['robot', 'Unimate', 'Boston Dynamics', 'humanoid robot'] },
    { slug: 'ai-chips-and-gpus', en: 'GPUs, TPUs and the chips behind AI', hi: 'जीपीयू, टीपीयू और एआई के पीछे की चिप', qids: ['Q182477'], keywords: ['GPU', 'Nvidia', 'TPU', 'AI accelerator'] },
    { slug: 'recommendation-algorithms', en: 'Recommendation algorithms and feeds', hi: 'रेकमेंडेशन एल्गोरिदम और फ़ीड', qids: ['Q554950'], keywords: ['recommender system', 'collaborative filtering', 'Netflix Prize', 'ranking feed'] },
    { slug: 'ai-in-healthcare', en: 'AI in diagnosis and medical imaging', hi: 'बीमारी पहचानने और मेडिकल इमेजिंग में एआई', qids: ['Q74266336'], keywords: ['AI diagnosis', 'medical imaging AI', 'diabetic retinopathy screening', 'radiology AI'] },
    { slug: 'ai-in-weather-forecasting', en: 'AI weather forecasting', hi: 'एआई से मौसम की भविष्यवाणी', keywords: ['AI weather model', 'GraphCast', 'numerical weather prediction', 'monsoon forecast'] },
    { slug: 'ai-in-agriculture-india', en: 'AI in Indian agriculture', hi: 'भारतीय खेती में एआई', qids: ['Q1283783'], keywords: ['AI agriculture India', 'crop yield prediction', 'satellite crop monitoring', 'pest detection'] },
    { slug: 'hallucination-and-benchmarks', en: 'Hallucination and how AI is benchmarked', hi: 'हैलुसिनेशन और एआई की परख कैसे होती है', qids: ['Q1161707'], keywords: ['hallucination LLM', 'benchmark', 'evaluation', 'MMLU'] },
    { slug: 'ai-and-jobs', en: 'AI, automation and jobs', hi: 'एआई, ऑटोमेशन और नौकरियाँ', qids: ['Q105468213'], keywords: ['automation jobs', 'AI displacement', 'BPO India', 'future of work'] },
    { slug: 'ai-regulation', en: 'AI regulation around the world', hi: 'दुनिया भर में एआई के नियम', qids: ['Q108456694'], keywords: ['EU AI Act', 'AI regulation', 'AI safety policy', 'India AI advisory'] },
    { slug: 'ai-in-fiction', en: 'Asimov’s laws and AI in fiction', hi: 'असिमोव के नियम और कहानियों में एआई', qids: ['Q23758'], keywords: ['Three Laws of Robotics', 'Isaac Asimov', 'HAL 9000', 'AI in film'] },
    { slug: 'artificial-intelligence-overview', en: 'What counts as artificial intelligence', hi: 'आख़िर एआई कहते किसे हैं', qids: ['Q11660'], keywords: ['artificial intelligence', 'symbolic AI', 'AI effect', 'narrow vs general AI'] },
  ],
};
