import type { CategoryDef } from '../taxonomy-types.js';

export const law: CategoryDef = {
  id: 26,
  slug: 'law-constitution-government',
  en: 'Law, Constitution & Government',
  hi: 'क़ानून, संविधान और सरकार',
  emoji: '⚖️',
  kidsSafe: true,
  subtopics: [
    { slug: 'constituent-assembly-of-india', en: 'The Constituent Assembly of India', hi: 'भारत की संविधान सभा', qids: ['Q2340149'], keywords: ['Constituent Assembly', '1946 to 1949', 'Rajendra Prasad', 'objectives resolution'] },
    { slug: 'ambedkar-drafting-committee', en: 'Ambedkar and the drafting committee', hi: 'आंबेडकर और प्रारूप समिति', qids: ['Q231690'], keywords: ['B.R. Ambedkar', 'drafting committee', 'B.N. Rau', 'Constitution of India'] },
    { slug: 'making-of-the-constitution', en: 'How the Constitution was written and calligraphed', hi: 'संविधान कैसे लिखा और सुलेखित हुआ', qids: ['Q62023627'], keywords: ['Prem Behari Narain Raizada', 'Nandalal Bose illustrations', '26 January 1950', 'handwritten constitution'] },
    { slug: 'preamble-of-the-constitution', en: 'The Preamble', hi: 'संविधान की प्रस्तावना', qids: ['Q6498282'], keywords: ['Preamble', 'sovereign socialist secular democratic republic', '42nd amendment', 'We the People'] },
    { slug: 'fundamental-rights', en: 'Fundamental Rights, Part III', hi: 'मौलिक अधिकार, भाग तीन', qids: ['Q3237872'], keywords: ['Fundamental Rights', 'Part III', 'right to equality', 'right to freedom'] },
    { slug: 'article-14-equality', en: 'Article 14 and equality before law', hi: 'अनुच्छेद 14: क़ानून के सामने बराबरी', qids: ['Q4800865'], keywords: ['Article 14', 'equality before law', 'reasonable classification', 'arbitrariness'] },
    { slug: 'article-19-free-speech', en: 'Article 19 and free speech', hi: 'अनुच्छेद 19 और बोलने की आज़ादी', qids: ['Q2533114'], keywords: ['Article 19', 'freedom of speech', 'reasonable restrictions', 'first amendment 1951'] },
    { slug: 'article-21-life-and-liberty', en: 'Article 21: life and personal liberty', hi: 'अनुच्छेद 21: जीवन और निजी आज़ादी', qids: ['Q122363696'], keywords: ['Article 21', 'procedure established by law', 'right to life', 'due process'] },
    { slug: 'article-32-writs', en: 'Article 32 and the five writs', hi: 'अनुच्छेद 32 और पाँच रिट', qids: ['Q52668215'], keywords: ['Article 32', 'habeas corpus', 'mandamus', 'heart and soul of the Constitution'] },
    { slug: 'directive-principles', en: 'The Directive Principles of State Policy', hi: 'राज्य के नीति निदेशक तत्व', qids: ['Q134497312'], keywords: ['Directive Principles', 'Part IV', 'Irish Constitution influence', 'non-justiciable'] },
    { slug: 'fundamental-duties', en: 'Fundamental Duties and the 42nd Amendment', hi: 'मौलिक कर्तव्य और 42वाँ संशोधन', qids: ['Q136901127'], keywords: ['Fundamental Duties', 'Article 51A', 'Swaran Singh Committee', '42nd amendment 1976'] },
    { slug: 'kesavananda-basic-structure', en: 'Kesavananda Bharati and the basic structure doctrine', hi: 'केशवानंद भारती और बुनियादी ढाँचे का सिद्धांत', qids: ['Q4867055'], keywords: ['Kesavananda Bharati 1973', 'basic structure doctrine', '13 judge bench', 'amendment power'] },
    { slug: 'golaknath-case', en: 'The Golaknath case, 1967', hi: 'गोलकनाथ मामला, 1967', qids: ['Q190752'], keywords: ['Golaknath 1967', 'amendment of fundamental rights', 'prospective overruling', 'Supreme Court'] },
    { slug: 'maneka-gandhi-case', en: 'Maneka Gandhi v. Union of India, 1978', hi: 'मेनका गांधी बनाम भारत संघ, 1978', qids: ['Q60751451'], keywords: ['Maneka Gandhi 1978', 'passport impounded', 'due process', 'Article 21 expansion'] },
    { slug: 'emergency-and-adm-jabalpur', en: 'The Emergency and the ADM Jabalpur judgment', hi: 'आपातकाल और एडीएम जबलपुर का फ़ैसला', keywords: ['Emergency 1975', 'ADM Jabalpur 1976', 'habeas corpus case', 'Justice H.R. Khanna dissent'] },
    { slug: 'vishaka-guidelines', en: 'The Vishaka guidelines, 1997', hi: 'विशाखा दिशानिर्देश, 1997', qids: ['Q190752'], keywords: ['Vishaka 1997', 'workplace guidelines', 'judicial lawmaking', 'Supreme Court'] },
    { slug: 'public-interest-litigation', en: 'Public interest litigation in India', hi: 'भारत में जनहित याचिका', qids: ['Q3610538'], keywords: ['PIL', 'locus standi relaxation', 'Justice P.N. Bhagwati', 'epistolary jurisdiction'] },
    { slug: 'supreme-court-of-india', en: 'The Supreme Court of India', hi: 'भारत का सर्वोच्च न्यायालय', qids: ['Q54008035'], keywords: ['Supreme Court of India', '1950 Federal Court', 'Chief Justice of India', 'constitution bench'] },
    { slug: 'high-courts-of-india', en: 'The High Courts', hi: 'भारत के उच्च न्यायालय', qids: ['Q13211826'], keywords: ['High Court', 'Calcutta High Court 1862', 'Article 226', 'jurisdiction'] },
    { slug: 'collegium-system', en: 'How judges are appointed: the collegium', hi: 'जज कैसे नियुक्त होते हैं: कॉलेजियम', qids: ['Q7797551'], keywords: ['collegium system', 'Three Judges Cases', 'judicial appointments', 'Article 124'] },
    { slug: 'jury-trials-and-nanavati', en: 'How India abolished jury trials', hi: 'भारत ने ज्यूरी ट्रायल कैसे ख़त्म किया', qids: ['Q695852'], keywords: ['K.M. Nanavati 1959', 'jury trial abolished', 'Bombay High Court', 'criminal procedure'] },
    { slug: 'indian-penal-code-history', en: 'Macaulay and the Indian Penal Code', hi: 'मैकॉले और भारतीय दंड संहिता', qids: ['Q19519573'], keywords: ['Thomas Babington Macaulay', 'Indian Penal Code 1860', 'first law commission', 'codification'] },
    { slug: 'how-a-bill-becomes-law', en: 'How a bill becomes law in India', hi: 'भारत में बिल क़ानून कैसे बनता है', keywords: ['bill', 'three readings', 'standing committee', 'presidential assent'] },
    { slug: 'lok-sabha-and-rajya-sabha', en: 'Lok Sabha and Rajya Sabha', hi: 'लोकसभा और राज्यसभा', qids: ['Q230003'], keywords: ['Lok Sabha', 'Rajya Sabha', 'joint sitting', 'Speaker'] },
    { slug: 'money-bills-and-budget', en: 'Money bills and the Union Budget', hi: 'धन विधेयक और आम बजट', qids: ['Q1591172'], keywords: ['money bill Article 110', 'appropriation bill', 'union budget', 'consolidated fund'] },
    { slug: 'anti-defection-law', en: 'The anti-defection law', hi: 'दल-बदल विरोधी क़ानून', qids: ['Q96372207'], keywords: ['Tenth Schedule', '52nd amendment 1985', 'defection', 'Speaker disqualification'] },
    { slug: 'president-and-governors', en: 'The President and the Governors', hi: 'राष्ट्रपति और राज्यपाल', qids: ['Q313383'], keywords: ['President of India', 'electoral college', 'Governor', 'Article 356'] },
    { slug: 'seventh-schedule-lists', en: 'The Seventh Schedule: who makes which law', hi: 'सातवीं अनुसूची: कौन सा क़ानून कौन बनाए', qids: ['Q7885821'], keywords: ['Union List', 'State List', 'Concurrent List', 'federalism'] },
    { slug: 'constitutional-amendments', en: 'How the Constitution gets amended', hi: 'संविधान में संशोधन कैसे होता है', keywords: ['Article 368', 'special majority', 'ratification by states', 'most amended constitution'] },
    { slug: 'election-commission-of-india', en: 'The Election Commission of India', hi: 'भारत का चुनाव आयोग', qids: ['Q2724317'], keywords: ['Election Commission', 'T.N. Seshan', 'model code of conduct', 'EVM'] },
    { slug: 'first-general-election', en: 'India’s first general election, 1951–52', hi: 'भारत का पहला आम चुनाव, 1951–52', qids: ['Q7635916'], keywords: ['first general election 1951', 'Sukumar Sen', 'universal adult franchise', 'ballot box symbols'] },
    { slug: 'panchayati-raj-amendments', en: 'Panchayati Raj and the 73rd and 74th Amendments', hi: 'पंचायती राज और 73वाँ–74वाँ संशोधन', keywords: ['73rd amendment 1992', 'gram sabha', 'urban local bodies', 'reservation for women'] },
    { slug: 'right-to-information-act', en: 'The Right to Information Act, 2005', hi: 'सूचना का अधिकार क़ानून, 2005', qids: ['Q2725604'], keywords: ['RTI Act 2005', 'public information officer', 'MKSS Rajasthan', 'central information commission'] },
    { slug: 'cag-of-india', en: 'The Comptroller and Auditor General', hi: 'नियंत्रक एवं महालेखापरीक्षक', qids: ['Q48319259'], keywords: ['CAG', 'Article 148', 'audit report', 'public accounts committee'] },
    { slug: 'magna-carta', en: 'Magna Carta', hi: 'मैग्ना कार्टा', qids: ['Q12519'], keywords: ['Magna Carta 1215', 'King John', 'Runnymede', 'rule of law'] },
    { slug: 'code-of-hammurabi', en: 'The Code of Hammurabi', hi: 'हम्मूराबी की क़ानून संहिता', qids: ['Q93304'], keywords: ['Hammurabi', 'Babylon', 'stele', 'oldest written law code'] },
    { slug: 'common-law-vs-civil-law', en: 'Common law and civil law systems', hi: 'कॉमन लॉ और सिविल लॉ की व्यवस्थाएँ', qids: ['Q30216'], keywords: ['common law', 'civil law', 'Napoleonic Code', 'precedent'] },
    { slug: 'un-and-international-court', en: 'The UN and the International Court of Justice', hi: 'संयुक्त राष्ट्र और अंतरराष्ट्रीय न्यायालय', qids: ['Q1065'], keywords: ['United Nations', 'International Court of Justice', 'The Hague', 'UN Charter 1945'] },
    { slug: 'nuremberg-trials', en: 'The Nuremberg trials', hi: 'नूरेम्बर्ग मुक़दमे', qids: ['Q580233'], keywords: ['Nuremberg trials 1945', 'crimes against humanity', 'international criminal law', 'Robert Jackson'] },
    { slug: 'udhr-1948', en: 'The Universal Declaration of Human Rights', hi: 'मानवाधिकारों की सार्वभौम घोषणा', qids: ['Q140187082'], keywords: ['UDHR 1948', 'Eleanor Roosevelt', 'Hansa Mehta', 'thirty articles'] },
  ],
};
