import type { CategoryDef } from '../taxonomy-types.js';

export const environment: CategoryDef = {
  id: 24,
  slug: 'environment-climate',
  en: 'Environment & Climate',
  hi: 'पर्यावरण और जलवायु',
  emoji: '🌏',
  kidsSafe: true,
  subtopics: [
    { slug: 'greenhouse-effect-discovery', en: 'How the greenhouse effect was discovered', hi: 'ग्रीनहाउस असर कैसे पता चला', keywords: ['Eunice Foote', 'John Tyndall', 'Svante Arrhenius', 'greenhouse effect'] },
    { slug: 'keeling-curve', en: 'The Keeling Curve', hi: 'कीलिंग कर्व: हवा में CO2 का हिसाब', qids: ['Q224858'], keywords: ['Charles David Keeling', 'Mauna Loa', 'carbon dioxide concentration', 'ppm'] },
    { slug: 'ice-cores-and-past-climate', en: 'Ice cores and the climate of the past', hi: 'बर्फ़ के कोर और पुराने ज़माने की जलवायु', qids: ['Q258914'], keywords: ['ice core', 'Vostok', 'EPICA Dome C', 'paleoclimate'] },
    { slug: 'ipcc-assessment-reports', en: 'The IPCC and its assessment reports', hi: 'आईपीसीसी और उसकी रिपोर्टें', qids: ['Q97611940'], keywords: ['IPCC', 'assessment report', 'Nobel Peace Prize 2007', 'R.K. Pachauri'] },
    { slug: 'kyoto-protocol', en: 'The Kyoto Protocol', hi: 'क्योटो प्रोटोकॉल', qids: ['Q47359'], keywords: ['Kyoto Protocol', '1997', 'emission targets', 'UNFCCC'] },
    { slug: 'paris-agreement', en: 'The Paris Agreement', hi: 'पेरिस समझौता', qids: ['Q21707860'], keywords: ['Paris Agreement', 'COP21', '1.5 degrees', 'nationally determined contributions'] },
    { slug: 'montreal-protocol-ozone', en: 'The Montreal Protocol and the ozone hole', hi: 'मॉन्ट्रियल प्रोटोकॉल और ओज़ोन का छेद', qids: ['Q219438'], keywords: ['Montreal Protocol', 'ozone hole', 'CFC', 'Antarctic ozone'] },
    { slug: 'silent-spring-and-ddt', en: 'Silent Spring and the DDT ban', hi: 'साइलेंट स्प्रिंग और डीडीटी पर रोक', qids: ['Q100948'], keywords: ['Rachel Carson', 'Silent Spring', 'DDT', 'pesticide'] },
    { slug: 'chipko-movement', en: 'The Chipko movement', hi: 'चिपको आंदोलन', qids: ['Q1074585'], keywords: ['Chipko', 'Sunderlal Bahuguna', 'Gaura Devi', 'Reni village 1974'] },
    { slug: 'narmada-bachao-andolan', en: 'The Narmada dam debate', hi: 'नर्मदा बाँध की बहस', qids: ['Q2762203'], keywords: ['Narmada Bachao Andolan', 'Sardar Sarovar', 'Medha Patkar', 'displacement'] },
    { slug: 'bhopal-gas-tragedy', en: 'The Bhopal gas tragedy and industrial safety law', hi: 'भोपाल गैस त्रासदी और औद्योगिक सुरक्षा क़ानून', qids: ['Q410431'], keywords: ['Bhopal 1984', 'methyl isocyanate', 'Union Carbide', 'environmental law'] },
    { slug: 'ganga-river-system', en: 'The Ganga river system', hi: 'गंगा नदी तंत्र', qids: ['Q5089'], keywords: ['Ganges', 'Gangotri', 'river basin', 'Namami Gange'] },
    { slug: 'himalayan-glaciers', en: 'Himalayan glaciers', hi: 'हिमालय के ग्लेशियर', qids: ['Q5451'], keywords: ['Gangotri glacier', 'Siachen', 'glacial retreat', 'third pole'] },
    { slug: 'indian-monsoon', en: 'The Indian monsoon', hi: 'भारतीय मानसून', qids: ['Q110652068'], keywords: ['southwest monsoon', 'monsoon onset Kerala', 'IMD', 'rainfall'] },
    { slug: 'el-nino-la-nina', en: 'El Niño and La Niña', hi: 'अल नीन्यो और ला नीन्या', qids: ['Q3720957'], keywords: ['El Nino', 'La Nina', 'ENSO', 'Pacific sea surface temperature'] },
    { slug: 'bay-of-bengal-cyclones', en: 'Cyclones of the Bay of Bengal', hi: 'बंगाल की खाड़ी के चक्रवात', qids: ['Q121742'], keywords: ['Bay of Bengal cyclone', 'Odisha super cyclone 1999', 'cyclone naming', 'storm surge'] },
    { slug: 'sundarbans-mangroves', en: 'The Sundarbans mangroves', hi: 'सुंदरबन के मैंग्रोव', qids: ['Q3285794'], keywords: ['Sundarbans', 'mangrove forest', 'Royal Bengal tiger', 'UNESCO site'] },
    { slug: 'western-ghats-biodiversity', en: 'The Western Ghats biodiversity hotspot', hi: 'पश्चिमी घाट: जैव विविधता का ख़ज़ाना', qids: ['Q4527'], keywords: ['Western Ghats', 'biodiversity hotspot', 'endemic species', 'Gadgil report'] },
    { slug: 'project-tiger', en: 'Project Tiger', hi: 'प्रोजेक्ट टाइगर', qids: ['Q3180609'], keywords: ['Project Tiger', '1973', 'tiger reserve', 'tiger census'] },
    { slug: 'indian-national-parks', en: 'India’s national parks', hi: 'भारत के राष्ट्रीय उद्यान', qids: ['Q949297'], keywords: ['Jim Corbett National Park', 'Kaziranga', 'Gir', 'Ranthambore'] },
    { slug: 'iucn-red-list', en: 'The IUCN Red List', hi: 'आईयूसीएन की रेड लिस्ट', qids: ['Q32059'], keywords: ['IUCN Red List', 'endangered species', 'critically endangered', 'conservation status'] },
    { slug: 'extinct-animals', en: 'Animals that went extinct in recorded history', hi: 'जो जानवर हमारी आँखों के सामने ख़त्म हो गए', qids: ['Q191968'], keywords: ['dodo', 'passenger pigeon', 'thylacine', 'Steller sea cow'] },
    { slug: 'amazon-rainforest', en: 'The Amazon rainforest', hi: 'अमेज़न का वर्षावन', qids: ['Q177567'], keywords: ['Amazon rainforest', 'deforestation', 'carbon sink', 'Brazil'] },
    { slug: 'coral-reefs-and-bleaching', en: 'Coral reefs and bleaching', hi: 'मूँगे की चट्टानें और उनका सफ़ेद पड़ना', qids: ['Q7343'], keywords: ['Great Barrier Reef', 'coral bleaching', 'Lakshadweep reefs', 'zooxanthellae'] },
    { slug: 'sea-level-rise', en: 'Sea level rise', hi: 'समुद्र का बढ़ता जलस्तर', qids: ['Q841083'], keywords: ['sea level rise', 'thermal expansion', 'Maldives', 'coastal erosion'] },
    { slug: 'sahara-and-desertification', en: 'The Sahara and desertification', hi: 'सहारा और रेगिस्तान का फैलाव', qids: ['Q6583'], keywords: ['Sahara', 'desertification', 'Great Green Wall', 'African Humid Period'] },
    { slug: 'plastic-pollution', en: 'Plastic in the oceans', hi: 'समुद्र में प्लास्टिक', qids: ['Q638904'], keywords: ['Great Pacific Garbage Patch', 'microplastics', 'single-use plastic ban', 'ocean gyre'] },
    { slug: 'e-waste', en: 'Electronic waste', hi: 'ई-कचरा', qids: ['Q327400'], keywords: ['e-waste', 'Seelampur', 'Agbogbloshie', 'urban mining'] },
    { slug: 'air-quality-and-smog', en: 'Air quality, smog and the AQI', hi: 'हवा की गुणवत्ता, स्मॉग और एक्यूआई', qids: ['Q2364111'], keywords: ['air quality index', 'PM2.5', 'Great Smog of London 1952', 'stubble burning'] },
    { slug: 'renewable-energy-india', en: 'India’s renewable energy build-out', hi: 'भारत में नवीकरणीय ऊर्जा का विस्तार', keywords: ['solar park', 'Bhadla', 'wind energy Tamil Nadu', 'International Solar Alliance'] },
    { slug: 'nuclear-accidents-and-environment', en: 'Chernobyl, Fukushima and the land around them', hi: 'चेर्नोबिल, फ़ुकुशिमा और उनके आसपास की ज़मीन', qids: ['Q1050926'], keywords: ['Chernobyl exclusion zone', 'Fukushima 2011', 'radiation', 'wildlife return'] },
    { slug: 'ramsar-wetlands', en: 'Ramsar wetlands', hi: 'रामसर आर्द्रभूमि', qids: ['Q170170'], keywords: ['Ramsar Convention', 'wetland', 'Chilika Lake', 'Keoladeo'] },
    { slug: 'groundwater-and-water-crisis', en: 'Groundwater and India’s water crisis', hi: 'भूजल और भारत का पानी संकट', qids: ['Q7113626'], keywords: ['groundwater depletion', 'tubewell', 'Cape Town Day Zero', 'rainwater harvesting'] },
    { slug: 'rewilding-yellowstone-wolves', en: 'Rewilding and the Yellowstone wolves', hi: 'रीवाइल्डिंग और येलोस्टोन के भेड़िये', qids: ['Q2455497'], keywords: ['Yellowstone wolves 1995', 'trophic cascade', 'rewilding', 'elk'] },
    { slug: 'urban-heat-islands', en: 'Urban heat islands', hi: 'शहरों का हीट आइलैंड बनना', qids: ['Q215712'], keywords: ['urban heat island', 'cool roof', 'Ahmedabad heat action plan', 'albedo'] },
    { slug: 'antarctic-treaty', en: 'The Antarctic Treaty', hi: 'अंटार्कटिक संधि', qids: ['Q182814'], keywords: ['Antarctic Treaty 1959', 'no military activity', 'research stations', 'Dakshin Gangotri'] },
  ],
};
