import type { CategoryDef } from '../taxonomy-types.js';

export const hollywood: CategoryDef = {
  id: 3,
  slug: 'hollywood',
  en: 'Hollywood',
  hi: 'हॉलीवुड',
  emoji: '🎞️',
  kidsSafe: true,
  subtopics: [
    { slug: 'how-hollywood-began', en: 'How the film business moved to Hollywood', hi: 'फ़िल्म कारोबार हॉलीवुड कैसे पहुँचा', qids: ['Q34006'], keywords: ['Hollywood', 'Edison patents', 'Nestor Studio', 'Los Angeles 1911'] },
    { slug: 'silent-era-comedians', en: 'Chaplin, Keaton and the silent comedians', hi: 'चैप्लिन, कीटन और साइलेंट कॉमेडी', qids: ['Q882'], keywords: ['Charlie Chaplin', 'Buster Keaton', 'Harold Lloyd', 'silent film'] },
    { slug: 'the-jazz-singer-sound', en: 'The Jazz Singer and the coming of sound', hi: 'द जैज़ सिंगर और आवाज़ का आना', qids: ['Q465087'], keywords: ['The Jazz Singer', '1927', 'Vitaphone', 'talkies transition'] },
    { slug: 'studio-system', en: 'The studio system and the Big Five', hi: 'स्टूडियो सिस्टम और बड़े पाँच स्टूडियो', qids: ['Q11307668'], keywords: ['studio system', 'MGM', 'Paramount', 'contract players'] },
    { slug: 'hays-code', en: 'The Hays Code: what films could not show', hi: 'हेज़ कोड: फ़िल्मों में क्या नहीं दिखा सकते थे', qids: ['Q610292'], keywords: ['Hays Code', 'Motion Picture Production Code', 'pre-Code Hollywood', 'censorship'] },
    { slug: 'technicolor', en: 'Technicolor and the arrival of colour', hi: 'टेक्नीकलर और रंगीन फ़िल्मों की शुरुआत', qids: ['Q674564'], keywords: ['Technicolor', 'three-strip process', 'The Wizard of Oz', 'colour film'] },
    { slug: 'hollywood-1939', en: '1939, Hollywood’s greatest year', hi: '1939, हॉलीवुड का सबसे बड़ा साल', qids: ['Q96359529'], keywords: ['1939 films', 'Gone with the Wind', 'The Wizard of Oz', 'Stagecoach'] },
    { slug: 'citizen-kane-and-welles', en: 'Citizen Kane and Orson Welles', hi: 'सिटिज़न केन और ऑर्सन वेल्स', qids: ['Q24815'], keywords: ['Citizen Kane', 'Orson Welles', 'deep focus', 'Hearst'] },
    { slug: 'film-noir', en: 'Film noir', hi: 'फ़िल्म नोआर', qids: ['Q185867'], keywords: ['film noir', 'Double Indemnity', 'chiaroscuro lighting', 'femme fatale'] },
    { slug: 'westerns-and-john-ford', en: 'Westerns, John Ford and Monument Valley', hi: 'वेस्टर्न, जॉन फ़ोर्ड और मॉन्युमेंट वैली', qids: ['Q172980'], keywords: ['Western film', 'John Ford', 'Monument Valley', 'The Searchers'] },
    { slug: 'hollywood-blacklist', en: 'The Hollywood blacklist and the Hollywood Ten', hi: 'हॉलीवुड ब्लैकलिस्ट और हॉलीवुड टेन', qids: ['Q16864771'], keywords: ['Hollywood blacklist', 'HUAC', 'Hollywood Ten', 'Dalton Trumbo'] },
    { slug: 'method-acting-studio', en: 'The Actors Studio and method acting', hi: 'ऐक्टर्स स्टूडियो और मेथड ऐक्टिंग', qids: ['Q216458'], keywords: ['Actors Studio', 'Lee Strasberg', 'method acting', 'Stanislavski'] },
    { slug: 'paramount-decree', en: 'The Paramount decree that broke the studios', hi: 'पैरामाउंट फ़ैसला जिसने स्टूडियो तोड़े', qids: ['Q3550761'], keywords: ['United States v. Paramount', '1948', 'block booking', 'antitrust'] },
    { slug: 'new-hollywood-1970s', en: 'New Hollywood and the 1970s directors', hi: 'न्यू हॉलीवुड और 1970 के निर्देशक', qids: ['Q377616'], keywords: ['New Hollywood', 'Coppola', 'Scorsese', 'Easy Rider'] },
    { slug: 'the-godfather', en: 'The Godfather and the gangster film', hi: 'द गॉडफ़ादर और गैंगस्टर सिनेमा', qids: ['Q1139696'], keywords: ['The Godfather', 'Francis Ford Coppola', 'gangster film', 'casting Pacino'] },
    { slug: 'jaws-and-the-blockbuster', en: 'Jaws and the invention of the summer blockbuster', hi: 'जॉज़ और समर ब्लॉकबस्टर की शुरुआत', qids: ['Q4019680'], keywords: ['Jaws', '1975', 'wide release', 'summer blockbuster'] },
    { slug: 'star-wars-franchise', en: 'Star Wars and the merchandising deal', hi: 'स्टार वॉर्स और मर्चेंडाइज़िंग की डील', qids: ['Q462'], keywords: ['Star Wars', 'George Lucas', 'merchandising rights', 'Industrial Light and Magic'] },
    { slug: 'spielberg-films', en: 'Steven Spielberg’s filmography', hi: 'स्टीवन स्पीलबर्ग की फ़िल्में', qids: ['Q8877'], keywords: ['Steven Spielberg', 'E.T.', 'Schindler’s List', 'Amblin'] },
    { slug: 'academy-awards', en: 'The Academy Awards', hi: 'अकैडमी अवॉर्ड्स', qids: ['Q19020'], keywords: ['Oscars', 'Academy Award', 'Best Picture', 'Academy of Motion Picture Arts and Sciences'] },
    { slug: 'oscar-upsets-and-scandals', en: 'Oscar upsets, refusals and envelope mix-ups', hi: 'ऑस्कर के उलटफेर, इनकार और लिफ़ाफ़े की ग़लती', keywords: ['Oscar snub', 'Brando refusal', 'La La Land Moonlight', 'Academy controversy'] },
    { slug: 'mpaa-ratings', en: 'The MPAA rating system', hi: 'एमपीएए रेटिंग सिस्टम', qids: ['Q23660208'], keywords: ['MPAA rating', 'PG-13', 'NC-17', 'film certification US'] },
    { slug: 'ilm-and-visual-effects', en: 'ILM and the visual effects revolution', hi: 'आईएलएम और वीएफ़एक्स की क्रांति', qids: ['Q746676'], keywords: ['Industrial Light and Magic', 'visual effects', 'motion control', 'Jurassic Park CGI'] },
    { slug: 'pixar-and-cg-animation', en: 'Pixar and computer animation', hi: 'पिक्सर और कंप्यूटर ऐनिमेशन', qids: ['Q2316015'], keywords: ['Pixar', 'Toy Story', 'RenderMan', 'computer animation'] },
    { slug: 'disney-renaissance', en: 'The Disney Renaissance', hi: 'डिज़्नी रेनेसाँ', qids: ['Q906232'], keywords: ['Disney Renaissance', 'The Lion King', 'Howard Ashman', 'animated musical'] },
    { slug: 'marvel-cinematic-universe', en: 'The Marvel Cinematic Universe', hi: 'मार्वल सिनेमैटिक यूनिवर्स', qids: ['Q642878'], keywords: ['Marvel Cinematic Universe', 'Iron Man 2008', 'Avengers Endgame', 'Kevin Feige'] },
    { slug: 'james-bond-series', en: 'The James Bond series and its six actors', hi: 'जेम्स बॉन्ड सीरीज़ और उसके छह ऐक्टर', qids: ['Q844'], keywords: ['James Bond', 'Eon Productions', 'Dr. No', 'Bond actors'] },
    { slug: 'titanic-and-cameron', en: 'Titanic, Avatar and James Cameron’s budgets', hi: 'टाइटैनिक, अवतार और जेम्स कैमरन का बजट', qids: ['Q44578'], keywords: ['Titanic 1997', 'James Cameron', 'Avatar', 'production budget'] },
    { slug: 'billion-dollar-films', en: 'The billion-dollar box office club', hi: 'एक अरब डॉलर वाला बॉक्स ऑफ़िस क्लब', keywords: ['highest-grossing films', 'worldwide box office', 'billion dollar film', 'opening weekend record'] },
    { slug: 'film-scores', en: 'Film scores: Williams, Morricone, Zimmer', hi: 'फ़िल्म संगीत: विलियम्स, मोरिकोने, ज़िमर', qids: ['Q131285'], keywords: ['John Williams', 'Ennio Morricone', 'Hans Zimmer', 'film score'] },
    { slug: 'stunts-and-practical-effects', en: 'Stunt work and practical effects', hi: 'स्टंट और असली इफ़ेक्ट्स', qids: ['Q465501'], keywords: ['stunt performer', 'practical effects', 'Mission Impossible stunts', 'safety on set'] },
    { slug: 'sundance-and-indie-film', en: 'Sundance and American independent film', hi: 'सनडांस और अमेरिकी इंडी सिनेमा', qids: ['Q189887'], keywords: ['Sundance Film Festival', 'independent film', 'Miramax', 'Reservoir Dogs'] },
    { slug: 'cannes-and-festival-circuit', en: 'Cannes, Venice, Berlin and the festival circuit', hi: 'कान, वेनिस, बर्लिन और फ़ेस्टिवल सर्किट', qids: ['Q42369'], keywords: ['Cannes Film Festival', 'Palme d’Or', 'Venice Film Festival', 'Berlinale'] },
    { slug: 'streaming-and-theatrical-window', en: 'Streaming and the collapse of the theatrical window', hi: 'स्ट्रीमिंग और थिएटर विंडो का ख़त्म होना', qids: ['Q907311'], keywords: ['Netflix', 'theatrical window', 'day-and-date release', 'streaming wars'] },
    { slug: 'hollywood-strikes', en: 'The writers’ and actors’ strikes', hi: 'लेखकों और कलाकारों की हड़तालें', qids: ['Q120674816'], keywords: ['WGA strike', 'SAG-AFTRA strike', '2023 Hollywood labor dispute', 'residuals'] },
    { slug: 'hollywood-shot-in-india', en: 'Hollywood films shot in India', hi: 'भारत में शूट हुई हॉलीवुड फ़िल्में', qids: ['Q658944'], keywords: ['Hollywood films shot in India', 'Gandhi 1982', 'The Darjeeling Limited', 'Octopussy Udaipur'] },
  ],
};
