import type { CategoryDef } from '../taxonomy-types.js';

export const space: CategoryDef = {
  id: 13,
  slug: 'space-astronomy',
  en: 'Space & Astronomy',
  hi: 'अंतरिक्ष और खगोल विज्ञान',
  emoji: '🪐',
  kidsSafe: true,
  subtopics: [
    { slug: 'the-sun', en: 'The Sun', hi: 'सूरज', qids: ['Q525'], keywords: ['Sun', 'sunspot', 'solar flare', 'corona'] },
    { slug: 'the-moon', en: 'The Moon and its phases', hi: 'चाँद और उसकी कलाएँ', qids: ['Q405'], keywords: ['Moon', 'lunar phases', 'craters', 'tides'] },
    { slug: 'apollo-11', en: 'Apollo 11 and the first Moon landing', hi: 'अपोलो 11 और चाँद पर पहला कदम', qids: ['Q43653'], keywords: ['Apollo 11', 'Armstrong', 'Eagle lander', '1969'] },
    { slug: 'mars-and-its-rovers', en: 'Mars and its rovers', hi: 'मंगल ग्रह और उसके रोवर', qids: ['Q111'], keywords: ['Mars', 'Curiosity rover', 'Perseverance', 'Olympus Mons'] },
    { slug: 'jupiter-and-galilean-moons', en: 'Jupiter and the Galilean moons', hi: 'बृहस्पति और उसके चाँद', qids: ['Q319'], keywords: ['Jupiter', 'Europa', 'Io', 'Great Red Spot'] },
    { slug: 'saturn-and-its-rings', en: 'Saturn and its rings', hi: 'शनि और उसके छल्ले', qids: ['Q193'], keywords: ['Saturn', 'rings', 'Titan', 'Cassini'] },
    { slug: 'venus', en: 'Venus, the hottest planet', hi: 'शुक्र ग्रह, सबसे गर्म ग्रह', qids: ['Q313'], keywords: ['Venus', 'atmosphere', 'Venera', 'greenhouse'] },
    { slug: 'mercury', en: 'Mercury, closest to the Sun', hi: 'बुध ग्रह, सूरज के सबसे पास', qids: ['Q308'], keywords: ['Mercury', 'MESSENGER', 'orbit', 'crater'] },
    { slug: 'uranus-and-neptune', en: 'Uranus and Neptune', hi: 'यूरेनस और नेपच्यून', qids: ['Q324', 'Q332'], keywords: ['Uranus', 'Neptune', 'ice giant', 'Voyager 2'] },
    { slug: 'pluto-and-dwarf-planets', en: 'Pluto and the dwarf planets', hi: 'प्लूटो और बौने ग्रह', qids: ['Q339'], keywords: ['Pluto', 'New Horizons', 'Ceres', 'Kuiper belt'] },
    { slug: 'the-asteroid-belt', en: 'The asteroid belt', hi: 'ऐस्टेरॉइड बेल्ट', qids: ['Q3863'], keywords: ['asteroid', 'Vesta', 'Ceres', 'impact'] },
    { slug: 'comets', en: 'Comets and where they come from', hi: 'धूमकेतु कहाँ से आते हैं', qids: ['Q3559'], keywords: ['comet', 'Halley', 'Oort cloud', 'tail'] },
    { slug: 'meteor-showers', en: 'Meteor showers and meteorites', hi: 'टूटते तारे और उल्कापिंड', qids: ['Q105000'], keywords: ['meteor shower', 'Perseids', 'meteorite', 'Leonids'] },
    { slug: 'black-holes', en: 'Black holes', hi: 'ब्लैक होल', qids: ['Q589'], keywords: ['black hole', 'event horizon', 'Sagittarius A*', 'M87'] },
    { slug: 'neutron-stars-and-pulsars', en: 'Neutron stars and pulsars', hi: 'न्यूट्रॉन तारे और पल्सर', qids: ['Q4202'], keywords: ['neutron star', 'pulsar', 'magnetar', 'spin'] },
    { slug: 'supernovae', en: 'Supernovae', hi: 'सुपरनोवा धमाके', qids: ['Q28551746'], keywords: ['supernova', 'Crab Nebula', 'SN 1054', 'stellar death'] },
    { slug: 'the-milky-way', en: 'The Milky Way', hi: 'आकाशगंगा', qids: ['Q321'], keywords: ['Milky Way', 'galactic centre', 'spiral arm', 'stars'] },
    { slug: 'galaxies-and-andromeda', en: 'Galaxies and Andromeda', hi: 'गैलेक्सियाँ और एंड्रोमेडा', qids: ['Q318'], keywords: ['galaxy', 'Andromeda', 'collision', 'Hubble deep field'] },
    { slug: 'the-big-bang', en: 'The Big Bang', hi: 'बिग बैंग', qids: ['Q323'], keywords: ['Big Bang', 'cosmic microwave background', 'expansion', 'redshift'] },
    { slug: 'exoplanets', en: 'Exoplanets: planets around other stars', hi: 'एक्सोप्लैनेट: दूसरे तारों के ग्रह', qids: ['Q44559'], keywords: ['exoplanet', 'Kepler', 'TRAPPIST-1', 'habitable zone'] },
    { slug: 'constellations-and-star-names', en: 'Constellations and star names', hi: 'तारामंडल और तारों के नाम', qids: ['Q4637694'], keywords: ['constellation', 'Orion', 'Ursa Major', 'star names'] },
    { slug: 'eclipses', en: 'Solar and lunar eclipses', hi: 'सूर्य ग्रहण और चंद्र ग्रहण', qids: ['Q3887'], keywords: ['solar eclipse', 'lunar eclipse', 'totality', 'saros'] },
    { slug: 'hubble-space-telescope', en: 'The Hubble Space Telescope', hi: 'हबल स्पेस टेलीस्कोप', qids: ['Q2513'], keywords: ['Hubble', 'space telescope', 'deep field', 'servicing mission'] },
    { slug: 'james-webb-telescope', en: 'The James Webb Space Telescope', hi: 'जेम्स वेब स्पेस टेलीस्कोप', qids: ['Q186447'], keywords: ['JWST', 'infrared', 'L2 orbit', 'mirror segments'] },
    { slug: 'international-space-station', en: 'The International Space Station', hi: 'इंटरनेशनल स्पेस स्टेशन', qids: ['Q25956'], keywords: ['ISS', 'orbit', 'microgravity', 'expedition'] },
    { slug: 'the-space-race', en: 'The space race', hi: 'स्पेस रेस: अमेरिका बनाम सोवियत संघ', qids: ['Q109677004'], keywords: ['Sputnik', 'Gagarin', 'Cold War', 'Apollo programme'] },
    { slug: 'life-of-an-astronaut', en: 'How astronauts live in orbit', hi: 'अंतरिक्ष यात्री ऑर्बिट में कैसे रहते हैं', qids: ['Q11631'], keywords: ['astronaut', 'spacewalk', 'space food', 'spacesuit'] },
    { slug: 'chandrayaan-missions', en: 'The Chandrayaan Moon missions', hi: 'चंद्रयान मिशन', qids: ['Q65538184'], keywords: ['Chandrayaan', 'ISRO', 'Vikram lander', 'lunar south pole'] },
    { slug: 'mangalyaan', en: 'Mangalyaan, India at Mars', hi: 'मंगलयान: मंगल पर भारत', qids: ['Q2156739'], keywords: ['Mars Orbiter Mission', 'Mangalyaan', 'ISRO', '2013'] },
    { slug: 'pslv-and-gslv', en: 'PSLV and GSLV rockets', hi: 'पीएसएलवी और जीएसएलवी रॉकेट', qids: ['Q697175'], keywords: ['PSLV', 'GSLV', 'launch vehicle', 'Sriharikota'] },
    { slug: 'aryabhata-satellite', en: 'Aryabhata and India’s first satellites', hi: 'आर्यभट और भारत के पहले सैटेलाइट', qids: ['Q25254'], keywords: ['Aryabhata satellite', '1975', 'Bhaskara', 'INSAT'] },
    { slug: 'vikram-sarabhai-and-isro', en: 'Vikram Sarabhai and the birth of ISRO', hi: 'विक्रम साराभाई और इसरो की शुरुआत', qids: ['Q325470'], keywords: ['Vikram Sarabhai', 'ISRO', 'Thumba', 'INCOSPAR'] },
    { slug: 'gaganyaan', en: 'Gaganyaan and Indian human spaceflight', hi: 'गगनयान और भारत की मानव अंतरिक्ष उड़ान', qids: ['Q580809'], keywords: ['Gaganyaan', 'crew module', 'ISRO', 'astronaut training'] },
    { slug: 'rakesh-sharma', en: 'Rakesh Sharma, the first Indian in space', hi: 'राकेश शर्मा: अंतरिक्ष में पहला भारतीय', qids: ['Q50105464'], keywords: ['Rakesh Sharma', 'Soyuz T-11', '1984', 'Salyut 7'] },
    { slug: 'jantar-mantar-observatories', en: 'The Jantar Mantar observatories', hi: 'जंतर मंतर वेधशालाएँ', qids: ['Q508634'], keywords: ['Jantar Mantar', 'Jai Singh II', 'Samrat Yantra', 'sundial'] },
    { slug: 'ancient-indian-astronomy', en: 'Ancient Indian astronomy', hi: 'प्राचीन भारतीय खगोल विज्ञान', qids: ['Q3518429'], keywords: ['Aryabhatiya', 'Surya Siddhanta', 'nakshatra', 'Bhaskara II'] },
  ],
};
